### ISSUE TITLE
Make sure that long spotlight-descriptions get truncated

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#100]
Randomly testing this via DevTools and I noticed that if I enter a slightly longer `spotlight-description` the text overlaps the `spotlight-type` ("Last opened on iPhone" bit).

![nightly](https://cloud.githubusercontent.com/assets/557895/12986868/4e3e3226-d0ae-11e5-8ca4-3f23001a4618.png)

**Comment by k88hudson** [comment]
This should be fixed by https://github.com/mozilla/activity-streams/pull/82/files#diff-f830d86c5e7c8227efa9ff7c2a300493L36

**Comment by k88hudson** [comment]
Because I'm a bad person and threw style fixes in there :smiling_imp:

**Comment by pdehaan** [comment]
Verified in **gh12/fake-data branch**. :+1:

**Comment by k88hudson** [comment]
Resolved!
