### ISSUE TITLE
mutating the [[Prototype]] of an object will cause your code to run very slowly

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#103]
Running the server locally via `$ npm start` and noticed this guy buried in my DevTools console:

> mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create
> &mdash; via bundle.js:1007

This seems to be the mysterious contents of L1007:

> /* 160 */
> /***/ function(module, exports, __webpack_require__) {
>
>  eval("/* WEBPACK VAR INJECTION */(function(process) {'use strict';\n\nfunction _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError(\"Cannot call a class as a function\"); } }\n\nfunction _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError(\"this hasn't been initialised - super() hasn't been called\"); } return call && (typeof call === \"object\" || typeof call === \"function\") ? call : self; }\n\nfunction _inherits(subClass, superClass) { if (typeof superClass !== \"function\" && superClass !== null) { throw new TypeError(\"Super expression must either be null or a function, not \" + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }\n\nvar _require = __webpack_require__(1);\n\nvar Component = _require.Component;\nvar PropTypes = _require.PropTypes;\nvar Children = _require.Children;\n\nvar storeShape = __webpack_require__(161);\n\nif (process.env.NODE_ENV !== 'production') {\n  var warnAboutReceivingStore;\n\n  (function () {\n    var didWarnAboutReceivingStore = false;\n    /* eslint-disable no-var */\n\n    warnAboutReceivingStore = function warnAboutReceivingStore() {\n      /* eslint-enable no-var */\n      if (didWarnAboutReceivingStore) {\n        return;\n      }\n      didWarnAboutReceivingStore = true;\n\n      /* eslint-disable no-console */\n      if (typeof console !== 'undefined' && typeof console.error === 'function') {\n        console.error('<Provider> does not support changing `store` on the fly. ' + 'It is most likely that you see this error because you updated to ' + 'Redux 2.x and React Redux 2.x which no longer hot reload reducers ' + 'automatically. See https://github.com/rackt/react-redux/releases/' + 'tag/v2.0.0 for the migration instructions.');\n      }\n      /* eslint-disable no-console */\n    };\n  })();\n}\n\nvar Provider = function (_Component) {\n  _inherits(Provider, _Component);\n\n  Provider.prototype.getChildContext = function getChildContext() {\n    return { store: this.store };\n  };\n\n  function Provider(props, context) {\n    _classCallCheck(this, Provider);\n\n    var _this = _possibleConstructorReturn(this, _Component.call(this, props, context));\n\n    _this.store = props.store;\n    return _this;\n  }\n\n  Provider.prototype.render = function render() {\n    var children = this.props.children;\n\n    return Children.only(children);\n  };\n\n  return Provider;\n}(Component);\n\nif (process.env.NODE_ENV !== 'production') {\n  Provider.prototype.componentWillReceiveProps = function (nextProps) {\n    var store = this.store;\n    var nextStore = nextProps.store;\n\n    if (store !== nextStore) {\n      warnAboutReceivingStore();\n    }\n  };\n}\n\nProvider.propTypes = {\n  store: storeShape.isRequired,\n  children: PropTypes.element.isRequired\n};\nProvider.childContextTypes = {\n  store: storeShape.isRequired\n};\n\nmodule.exports = Provider;\n/* WEBPACK VAR INJECTION */}.call(exports, __webpack_require__(4)))\n\n/*****************\n ** WEBPACK FOOTER\n ** ./~/react-redux/lib/components/Provider.js\n ** module id = 160\n ** module chunks = 0\n **/\n//# sourceURL=webpack:///./~/react-redux/lib/components/Provider.js?");

That looks like the guts from react-redux to my untrained eyes. Not sure if there is anything actionable here.

**Comment by oyiptong** [comment]
I think you're right. There might not be much we can do

**Comment by pdehaan** [comment]
:beetle::gun:
