### ISSUE TITLE
UI shifts too much betweenst the Home and Timeline pages

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#104]
### Steps to reproduce:
1. git clone
2. `npm install`
3. `npm start`
4. <http://localhost:1963/activity-streams.html>

### Actual results:
Stuff shifts a lot vertically when switching between the two pages (especially on bigger screens/resolutions).

![nightly](https://cloud.githubusercontent.com/assets/557895/12995290/4035b91a-d0db-11e5-96de-bed5b9c8d2d4.png)
**Figure 1:** Vertically centered "Home" page.

---

![nightly](https://cloud.githubusercontent.com/assets/557895/12995307/51fd0d42-d0db-11e5-87b9-0f5e55db1764.png)
**Figure 2:** vtop aligned "Timeline" page.

**Comment by pdehaan** [comment]
#### Workaround:
Remove the `align-items: center` style from NewTabPage.scss:
```scss
main.new-tab {
  // align-items: center;
  justify-content: center;
}
```

![nightly](https://cloud.githubusercontent.com/assets/557895/12995436/28f0f58e-d0dc-11e5-9b5c-a7b74962230d.png)

**Comment by k88hudson** [comment]
Hm, yeah I guess top aligned looks fine :)

**Comment by k88hudson** [comment]
This will be resolved by https://github.com/mozilla/activity-streams/issues/163
