### ISSUE TITLE
Rename "Timeline" page header to "Activity Stream"

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#106]
Sounds easy enough, but I'm guessing it really isn't.

Per the UI spec at https://mozilla.invisionapp.com/share/GA5RW90CW#/screens/130804847, the page header should be "Activity Stream" in the dropdown. Currently it says "Timeline" (via the `title` prop at [/content-src/components/Routes/Routes.js:12](https://github.com/mozilla/activity-streams/blob/0e90f9d1f3166060349614eaebf32cfa7553ce01/content-src/components/Routes/Routes.js#L12)).

Not sure if that means you also want to rename [TimelinePage](https://github.com/mozilla/activity-streams/tree/0e90f9d1f3166060349614eaebf32cfa7553ce01/content-src/components/TimelinePage) to something else like ActivityFeedPage (since [ActivityFeed](https://github.com/mozilla/activity-streams/tree/0e90f9d1f3166060349614eaebf32cfa7553ce01/content-src/components/ActivityFeed) is already taken).

<img width="285" alt="timeline" src="https://cloud.githubusercontent.com/assets/557895/12996261/34ea0144-d0e3-11e5-89e6-66a246ab12c3.png">
**Figure 1:** [invision spec](https://mozilla.invisionapp.com/share/GA5RW90CW#/screens/130804847)

versus:
![nightly](https://cloud.githubusercontent.com/assets/557895/12996283/54b37bfe-d0e3-11e5-9a91-319049f2bd51.png)
**Figure 2:** current.

**Comment by pdehaan** [comment]
(Sorry, filing some annoying UI spec bugs so I can track issues to see if we need to write e2e tests for this stuff as it lands)

**Comment by k88hudson** [comment]
This will *probably* not be the case as "activity steam" is not the user-facing term we're going with, but I'm not sure what the actual label/navigation structure is going to be

**Comment by nchapman** [comment]
I think we're going to change the name a few times over :smile:. Calling it `Timeline` internally and in code is the right thing to do.

**Comment by k88hudson** [comment]
Ok, discussed with @bryanbell we are going to use the name `Timeline` internally but use `Activity Stream` in the UI.

**Comment by rlr** [comment]
fixed!
