### ISSUE TITLE
Add Downloads and Tabs to side nav on ActivityStream page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#107]
Similar to #106 

I notice that currently we have "All" and "Bookmarks" nav items ([source](https://github.com/mozilla/activity-streams/blob/0e90f9d1f3166060349614eaebf32cfa7553ce01/content-src/components/TimelinePage/TimelinePage.js#L13-L16)), but the [UI spec](https://mozilla.invisionapp.com/share/GA5RW90CW#/screens/130804847) also shows "Downloads" and "Tabs".

Not sure what is in scope for this iteration, just throwing that out there.

![nightly](https://cloud.githubusercontent.com/assets/557895/12996358/edb7399e-d0e3-11e5-893f-7ce359f42c94.png)

<img width="277" alt="timeline" src="https://cloud.githubusercontent.com/assets/557895/12996372/04ed238a-d0e4-11e5-8b21-896bbc040a96.png">

**Comment by pdehaan** [comment]
Not sure if that is meant to be a generic "Tabs" icon, or if it's a magic SVG where we can show the current number of ... tabs?

**Comment by k88hudson** [comment]
Also negotiated to remove for this version (again, UI spec is definitely not exact)
