### ISSUE TITLE
Add "Filter" and Show Highlights to Activity Stream view

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#108]
Per the [UI spec](https://mozilla.invisionapp.com/share/GA5RW90CW#/screens/130804847).

Not 100% what that view should look like yet if I'm filtering or what's buried behind the "Show Highlights" dropdown.

<img width="858" alt="timeline" src="https://cloud.githubusercontent.com/assets/557895/12996523/8c15dc48-d0e5-11e5-8d03-f85af03a8742.png">

**Comment by k88hudson** [comment]
We negotiated with product to remove these features for this version; the comps aren't updated/exact at the moment
