### ISSUE TITLE
Add more ESLint rules

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#112]
Ref: https://github.com/mozilla/activity-streams/pull/110#discussion_r52712168

This seems like a good start: https://github.com/walmartlabs/eslint-config-defaults

I also extended "defaults" and "airbnb/es6", but then had to fiddle a bunch of individual rules to get things passing and a good set of rules.

Just filing this to get some feedback before I enter the merge hell that is touching large number of files with adding spaces or extra parens (protip: `eslint . --fix` is your friend).

```js
{
  // When adding items to this file please check for effects on sub-directories.
  "plugins": [
    "mozilla",
    "react"
  ],
  "extends": [
    "eslint:recommended",
    "defaults",
    "defaults/configurations/airbnb/es6"
  ],
  "rules": {
    "mozilla/components-imports": 1,
    "mozilla/import-globals-from": 1,
    "mozilla/this-top-level-scope": 1,

    "react/jsx-uses-react": 1,

    "array-bracket-spacing": [2, "never"],
    "arrow-body-style": 0,
    "arrow-parens": [2, "always"],
    "camelcase": 0,
    "comma-dangle": 0,
    "computed-property-spacing": [2, "never"],
    "default-case": 0, // TODO: Remove this.
    "eqeqeq": [2, "smart"],
    "func-names": 0,
    "generator-star-spacing": [2, {"before": true, "after": false}],
    "max-len": 0,
    "new-cap": 0,
    "no-console": 1,
    "no-param-reassign": 0,
    "no-shadow": 0, // TODO: Set to warning or error?
    "no-trailing-spaces": [2, {"skipBlankLines": false}],
    "no-undef": 2,
    "no-unused-vars": [2, {"vars": "all", "args": "none"}],
    "no-use-before-define": [2, "nofunc"],
    "no-var": 1,
    "object-curly-spacing": [2, "never"],
    "prefer-arrow-callback": 0,
    "prefer-const": 0, // TODO: Remove this.
    "quote-props": 0,
    "quotes": [2, "double"],
    "semi": [2, "always"],
    "space-before-function-paren": [2, {"anonymous": "never", "named": "never"}],
    "strict": 0
  },
  "ecmaFeatures": {
    "jsx": true
  },
  "env": {
    "browser": true,
    "es6": true,
    "mocha": true,
    "node": true,
  },
  "globals": {
    "StopIteration": true,
    "__CONFIG__": true
  }
}
```

**Comment by pdehaan** [comment]
Running the above set or rules gives 79 errors (and 6 warnings) against current master. Running ESLint with the glorious `--fix` flag, auto-fixes 22 of those errors.

There isn't anything TOO interesting in the results, but a few places where it looks like we're _potentially_ using a variable before it is defined (but everything is wrapped in functions and promises, so it may not be a race condition).

We should probably also discuss the following 3 rules which I added to the .eslintrc file but then had to pref-off:
1.     `"default-case": 0, // TODO: Remove this.`
2.    `"no-shadow": 0, // TODO: Set to warning or error?`
3.    `"prefer-const": 0, // TODO: Remove this.`

The first rule, [`default-case`](http://eslint.org/docs/rules/default-case.html), controls whether having a `default` case in a `switch` statement is desired. Should we log any unhandled or unexpected cases? Throw an error? Do nothing?

The second rule, [`no-shadow`](http://eslint.org/docs/rules/no-shadow.html), controls whether a local variable shares the same name as a variable in its containing scope. Not a big deal, but could potentially be confusing.

The third rule, [`prefer-const`](http://eslint.org/docs/rules/prefer-const.html), is just a whimsical rule which specifies that if a variable is never modified, we should use `const` instead of `let`. Probably no performance or any sort of gains, but could make code more readable by signaling a variable's intent.

---

I'm happy to take a stab at updating the .eslintrc and submitting a PR if people think it's worthwhile. Or if people don't, I'm happy to go look at animated cat GIFs instead. :8ball:

**Comment by pdehaan** [comment]
Note to self: Make sure we remove any references to "JSHint" rule exclusions: https://github.com/mozilla/activity-streams/search?utf8=%E2%9C%93&q=jshint

**Comment by oyiptong** [comment]
youch: 79 errors.

> The first rule, default-case, controls whether having a default case in a switch statement is desired. Should we log any unhandled or unexpected cases? Throw an error? Do nothing?

I vote for leaving this to the implementor. to me, accidental switch/case fall-throughs are more dangerous

> The second rule, no-shadow, controls whether a local variable shares the same name as a variable in its containing scope. Not a big deal, but could potentially be confusing.

I think that is a good idea as an error. It makes reviewing code easier as well

> The third rule, prefer-const, is just a whimsical rule which specifies that if a variable is never modified, we should use const instead of let. Probably no performance or any sort of gains, but could make code more readable by signaling a variable's intent

I think the intention is right, however, it still doesn't prevent someone from modifying the variable. If a `const` is assigned an object, one could modify the contents of the object. Having the expectation that a `const` won't be modified might give the wrong picture.

Keeping `const` for globals, and `let` for scoped variables  is a more sane rule of thumb IMHO

> I'm happy to take a stab at updating the .eslintrc and submitting a PR if people think it's worthwhile. Or if people don't, I'm happy to go look at animated cat GIFs instead.

Please do! Your contributions are appreciated!

**Comment by pdehaan** [comment]
In other news, **eslint@2** was just released: http://eslint.org/blog/2016/02/eslint-v2.0.0-released

**Comment by oyiptong** [comment]
The JS world moves so fast!

**Comment by oyiptong** [comment]
Do we know if our rules will transfer to eslint v2?

**Comment by oyiptong** [comment]
Looks like there are some minor changes: http://eslint.org/docs/user-guide/migrating-to-2.0.0

**Comment by oyiptong** [comment]
However, the rule sets we depend upon may require more invasive changes

**Comment by pdehaan** [comment]
So far it doesn't look like a straight forward port.
I have the following YAML based .eslintrc and it seems to say that the React themed vars are unused, even though we use them in JSX:

```yaml
env:
  browser: true
  es6: true
  mocha: true
  node: true

extends:
  - eslint:recommended

globals:
  __CONFIG__: true
  StopIteration: true

parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true

plugins:
  - mozilla
  - react

rules:
  mozilla/components-imports: 1
  mozilla/import-globals-from: 1
  mozilla/this-top-level-scope: 1

  react/jsx-uses-react: 1

  array-bracket-spacing: [2, never]
  comma-dangle: 0
  computed-property-spacing: [2, never]
  no-console: 1
  no-trailing-spaces: [2, {skipBlankLines: false}]
  no-undef: 2
  no-unused-vars: 2
  object-curly-spacing: [2, never]
  semi: [2, never]
  space-before-function-paren: [2, {anonymous: never, named: never}]
```

```sh
➜  activity-streams git:(master) ✗ ./node_modules/.bin/eslint --version
v2.0.0


➜  activity-streams git:(master) ✗ ./node_modules/.bin/eslint .

/Users/pdehaan/dev/github/activity-streams/content-src/components/Base/Base.js
  5:7  error  'Header' is defined but never used  no-unused-vars

/Users/pdehaan/dev/github/activity-streams/content-src/components/Header/Header.js
  2:8  error  'Link' is defined but never used  no-unused-vars

/Users/pdehaan/dev/github/activity-streams/content-src/components/NewTabPage/NewTabPage.js
  4:7  error  'TopSites' is defined but never used      no-unused-vars
  5:7  error  'ActivityFeed' is defined but never used  no-unused-vars
  6:7  error  'Spotlight' is defined but never used     no-unused-vars

/Users/pdehaan/dev/github/activity-streams/content-src/components/Routes/Routes.js
  2:8   error  'Router' is defined but never used      no-unused-vars
  2:16  error  'Route' is defined but never used       no-unused-vars
  2:23  error  'IndexRoute' is defined but never used  no-unused-vars

/Users/pdehaan/dev/github/activity-streams/content-src/components/TimelinePage/TimelinePage.js
  4:7  error  'ActivityFeed' is defined but never used  no-unused-vars
  5:7  error  'Spotlight' is defined but never used     no-unused-vars

/Users/pdehaan/dev/github/activity-streams/content-src/main.js
   3:8  error  'Provider' is defined but never used  no-unused-vars
   5:7  error  'Routes' is defined but never used    no-unused-vars
  10:7  error  'Root' is defined but never used      no-unused-vars

/Users/pdehaan/dev/github/activity-streams/content-test/components/Header.test.js
  4:7  error  'Header' is defined but never used  no-unused-vars

/Users/pdehaan/dev/github/activity-streams/content-test/components/Routes.test.js
  6:7  error  'Routes' is defined but never used    no-unused-vars
  8:7  error  'Provider' is defined but never used  no-unused-vars

/Users/pdehaan/dev/github/activity-streams/content-test/test-utils.js
  2:8  error  'Provider' is defined but never used  no-unused-vars

✖ 17 problems (17 errors, 0 warnings)
```
