### ISSUE TITLE
Use rimraf instead of rm -rf

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#125]
Currently we're using [`rm -rf data/content/*`](https://github.com/mozilla/activity-streams/blob/d083dabacb069703e71d5aaf35a25ff21a3a12cd/package.json#L84) in the package.json file (via [./yamscripts.yml:11](https://github.com/mozilla/activity-streams/blob/d083dabacb069703e71d5aaf35a25ff21a3a12cd/yamscripts.yml#L11)).
We should probably switch to the [**rimraf**](https://github.com/isaacs/rimraf) module for better OS support (lookin' at you, Windows).

I still need to hack on my Windows 10 laptop to try and get this all working. I fell down a sharp well of Node 4+ support and needing specific versions of Python.

**Comment by yash14123** [comment]
I would like to work on this. So we need to add the rimraf module first in package.json using something like: 
npm install rimraf

which adds it to the package.json list of dependencies. Then we remove the line rm -rf with something like:
rimraf('/data/content/*', function(err) {
  if (err) { throw err; }
  // done
})

**Comment by pdehaan** [comment]
@yash14123, if you're interesting in attempting this, I _think_ it's probably as easy as:

1. `npm install rimraf -D` (So it gets set as a devDependency in the package.json file. You'll also want to make sure you have npm@3 (or use [**npm-next**](https://www.npmjs.com/package/npm-next) if you're still using npm@2 globally).
2. Edit the [./yamscripts.yml](https://github.com/mozilla/activity-streams/blob/c8068d2f439b1c6cbc6466339bfede222c5777d1/yamscripts.yml#L11) file and change `clean: rm -rf data/content/*` to `clean: rimraf data/content/*`.
3. Run `npm run yamscripts` to update the package.json scripts section based on the yamscripts.yml tweak.
4. Regenerate the [npm-shrinkwrap.json](https://github.com/mozilla/activity-streams/blob/c8068d2f439b1c6cbc6466339bfede222c5777d1/npm-shrinkwrap.json) with the new changes made to the devDeps in step 1 above (`npm shrinkwrap --dev` -- and again make sure you do this w/ npm@3).

**Comment by yash14123** [comment]
On it. :)

**Comment by yash14123** [comment]
I am getting error in the last step. 
![error](https://cloud.githubusercontent.com/assets/9817962/13133165/f75a1148-d61e-11e5-85c7-b690a07e67d7.PNG)

**Comment by pdehaan** [comment]
@yash14123, are you still getting an error w/ shrinkwrap?
We removed the npm-shrinkwrap.json file in https://github.com/mozilla/activity-streams/commit/96672897342dddbba7dab5e899ad6861564898f3 so you may need to rebase.

**Comment by gasolin** [comment]
how about replace mkdir and rm with https://github.com/shelljs/shelljs ?
