### ISSUE TITLE
Travis-CI occasionally uses old Firefox 31 build

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#131]
Sometimes we use [**Mozilla Firefox 47.0a1**](https://travis-ci.org/mozilla/activity-streams/builds/109927671#L1726-L1727) but other times it randomly reverts to [**Mozilla Firefox 31**](https://travis-ci.org/mozilla/activity-streams/builds/109784117#L1726-L1727) (which is the default Firefox version for Travis-CI's Ubuntu).

---

![](https://lh3.googleusercontent.com/shAbDESZzkuz6VuLsVuS642gF0kRAujgxhb0jwkX9ltye6SskHKm7To9vRyGlQzkZ8zy_03_olmOlXRV7q_lik188DA)

**Comment by k88hudson** [comment]
Now that we're using the travis addon, this should no longer be an issue
