### ISSUE TITLE
Use Clearbit for site logos?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#132]
I believe the devilishly handsome (and disarmingly tall) @nchapman mentioned Clearbit's [logo api](http://blog.clearbit.com/logo/) in the meeting this morning. So far it looks like a pretty sweet API, with one odd twist.

Site images are super easy to fetch using `//logo.clearbit.com/{site}`, but it can be a bit tricky to detect cases where we can't fetch an image.

```html
<img src="//logo.clearbit.com/spotify.com">
```

produces this:
![](https://logo.clearbit.com/spotify.com)

And we can specify a width/height using the `size` parameter, a la:
```html
<img src="//logo.clearbit.com/spotify.com?size=80">
```

So far the images seem a bit crisper than what we're getting from embedly (see screenshot below), but it seems a bit tricky to detect when an image is un-fetchable, such as:

```html
<img src="https://logo.clearbit.com/blog.ibangspacebar.com?s=100">
```

which gives us:
![](https://logo.clearbit.com/blog.ibangspacebar.com?s=100)

#### So what's the "twist"?

> To specify a default image (for when we don't have logo handy) you can use the image's `onerror` event--we've put together [an example here](https://jsfiddle.net/maccman/2kxxgjk8/3/).
> &mdash; via [blog.clearbit.com/logo/#configuration](http://blog.clearbit.com/logo/#configuration)

Since we're generally setting images/logos via CSS and `background-image`, not sure if there is an easy way for us to detect when an image 404s and we have no logo (like the "ibangspacebar.com" example above).

---

![new_tab](https://cloud.githubusercontent.com/assets/557895/13124282/5072ee26-d575-11e5-9898-167bbba095eb.png)
**Figure 1:** You can see in the larger "Top Sites" images, the Clearbit logo is slightly clearer than the embedly image. Likewise in the favicon'esque logos in the Spotlight section. The Clearbit is a bit nicer and clearer, whereas the Embedly image has an odd radial gradient that makes it look a bit fuzzy.

**Comment by oyiptong** [comment]
There might be a privacy issue here. We'd be exposing user history if we don't proxy

**Comment by pdehaan** [comment]
I think we're leaning towards "no" for this, and focusing on our own proxy stuff.

**Comment by pdehaan** [comment]
I'm going to go ahead and say "no" and close this. I'm guessing this will be resolved by our Tippy-Top-Sites repo for now.
