### ISSUE TITLE
Placeholder boxes for spotlight and top sites components causing React errors in DevTools console

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#133]
Re: https://github.com/mozilla/activity-streams/pull/128#discussion_r53207371

It looks like #128 caused the following errors in the DevTools console:

> "Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `Spotlight`. See https://fb.me/react-warning-keys for more information."
> &mdash; via Spotlight.js#render():L89

I'm not sure exactly what line the error is on in the `render()` method, because it looks like the React code is getting transpiled down into this:

```js
      React.createElement(
        "ul",
        null,
        sites.map(site => React.createElement(SpotlightItem, _extends({ key: site.url }, site))),
        blankSites
      )
```
([source](https://github.com/mozilla/activity-streams/blob/c8068d2f439b1c6cbc6466339bfede222c5777d1/content-src/components/Spotlight/Spotlight.js#L57-L60))

---

I fixed it locally by being a hack and just adding the following `key={Math.random()}` in my Spotlight.js and TopSites.js files:

```js
blankSites.push(<li className="spotlight-item spotlight-placeholder" key={Math.random()} />);
```
([source: ./content-src/components/Spotlight/Spotlight.js:53](https://github.com/mozilla/activity-streams/blob/c8068d2f439b1c6cbc6466339bfede222c5777d1/content-src/components/Spotlight/Spotlight.js#L53))

and:

```js
blankSites.push(<div className="tile tile-placeholder" key={Math.random()} />);
```
([source: ./content-src/components/TopSites/TopSites.js:13](https://github.com/mozilla/activity-streams/blob/c8068d2f439b1c6cbc6466339bfede222c5777d1/content-src/components/TopSites/TopSites.js#L13))

**Comment by rlr** [comment]
fix0rd ^
