### ISSUE TITLE
Remove "https://www." from activity feed URLs?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#134]
Currently the URLs are a bit hard to read, because they all start with http:// or https:// and some have a pesky "www." which is like 12 semi-useless characters.

#### Current:

![new_tab](https://cloud.githubusercontent.com/assets/557895/13126987/e1d5c9cc-d581-11e5-9e08-b38203a192e5.png)

#### Proposed:

![new_tab](https://cloud.githubusercontent.com/assets/557895/13126930/8b4a7972-d581-11e5-9734-83ca99075905.png)

#### Workaround (Everybody Loves RegExes):
```js
<a className="feed-link" href={site.url} ref="link">{site.url.replace(/https?:\/\/(www\.)?/i, '')}</a>
```
&mdash; source [./content-src/components/ActivityFeed/ActivityFeed.js:15](https://github.com/mozilla/activity-streams/blob/c8068d2f439b1c6cbc6466339bfede222c5777d1/content-src/components/ActivityFeed/ActivityFeed.js#L15)

**Comment by oyiptong** [comment]
:+1:
