### ISSUE TITLE
Activity Streams does not work in FF Beta (45.0b6)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#138]
Currently working w/ shim data in FF Nightly (47.0a1 (2016-02-17)) and localhost, but when I try in Beta (45.0b6), I get the following error in my DevTools console:

> ### TypeError: arguments is not iterable

Digging into the error, it seems to be coming from this line:

```js
return compose([..._this.validators, definition], _this)(...arguments);
```

Which is located in [./content-src/lib/ActionManager.js:28-33](https://github.com/mozilla/activity-streams/blob/c8068d2f439b1c6cbc6466339bfede222c5777d1/content-src/lib/ActionManager.js#L28-L33).

**Comment by k88hudson** [comment]
I think the transform to add would be this `transform-object-rest-spread`
