### ISSUE TITLE
Basic add-on functionality

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-streams#15]
Some add-on specific stuff:
* override the new tab
* button in the toolbar for launching the Timeline
* launching `about:timeline` or something similar for Timeline

**Comment by oyiptong** [comment]
@k88hudson are we doing the toolbar? I thought that was just for sharing

**Comment by oyiptong** [comment]
how about this: we leave the about: url until later.

Are we doing two about: urls for timeline and newtab? or is it just one page with two "views"?

**Comment by oyiptong** [comment]
To get going, I pushed an initial add-on to master: 2591daa5a8e5c6b9dc44cdd6d8168dd2a0718e77
Additional code will be done via feature branches.

**Comment by oyiptong** [comment]
So, the initial code has:

* initial app structure
* content worker resource management
* message passing between addon and content
  * point-2-point messaging
  * broadcast messaging
* basic event handling
* places top frecent query
* places updates
* UUID generation for reporting
* some automation

**Comment by oyiptong** [comment]
Going to mark this as closed
