### ISSUE TITLE
Implement Search for the newtab page

### ISSUE THREAD

**Issue by oyiptong** [mozilla/activity-streams#150]
We need to implement search in the newtab page of Activity Streams.

We can port over the implementation of the search bar from the remote-newtab implementation, both chrome-side and content-side.

**Comment by k88hudson** [comment]
I think it would be a good idea to limit the scope of what's being ported over here. During the workweek, @nchapman and @bryanbell indicated it would be sufficient for this version to limit the scope to launching the right search provider, with autocomplete results as a nice to have.

What do you think about this @sarracini @oyiptong?

**Comment by oyiptong** [comment]
Actually, i was wrong. @sarracini just told me on IRC that she can do the engine-selected search using the correct `ContentSearch.jsm` without porting. Suggestions would require porting.

AND she already has a pull request. We should ship that.
