### ISSUE TITLE
Setup add-on pref to toggle all telemetry

### ISSUE THREAD

**Issue by oyiptong** [mozilla/activity-streams#152]
Create and use a boolean add-on pref that toggles all add-on telemetry.

This pref would be setup in `package.json` and can be accessed using [simple-prefs](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/simple-prefs)

This will involve obtaining the prefs in `main.js` and passing them in the ActivityStreams's `option` parameter object.

All telemetry-related code needs to be done within an init function in `ActivityStream`

**Comment by k88hudson** [comment]
This is resolved
