### ISSUE TITLE
Switch embedly URL over to use dev-server 

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-streams#157]
The new endpoint is: `http://embedly-proxy.dev.mozaws.net/extract`, we should use this instead of localhost.

It would be good to add this to `default-config.yml` and leave it configurable.

**Comment by pdehaan** [comment]
Is HTTPS configured for that? (It doesn't seem to be responding for me, but :100: if we can do it over HTTPS instead of vanilla HTTP.)

**Comment by oyiptong** [comment]
We should definitely do HTTPS. We'll have a more 'productionized' version soon. HTTP is most definitely not good enough for beyond dev use.

**Comment by k88hudson** [comment]
:+1:

**Comment by k88hudson** [comment]
(this endpoint is definitely just for dev)

**Comment by jaredkerim** [comment]
See #4 for details

**Comment by pdehaan** [comment]
See #168 for concerns (**tl;dr:** can we limit who can pass searches through the API, so we're not just providing a free version of Embedly for the world)

**Comment by k88hudson** [comment]
Blocked on https://github.com/mozilla/embedly-proxy/issues/3 and https://github.com/mozilla/embedly-proxy/issues/4
