### ISSUE TITLE
Time-constrained top frecent links API

### ISSUE THREAD

**Issue by oyiptong** [mozilla/activity-streams#164]
We need a new API to power the "top activity" rubric instead of the recent bookmark API.

Here's a cartoon sketch of a query, using postgres operators for datetime. Probably needs work.

```sql
SELECT p.url, p.title, p.frecency,
               p.last_visit_date as lastVisitDate,
                b.id as bookmarkId,
                b.guid as bookmarkGuid,
                f.data as favicon,
                f.mime_type as mimeType,
                "history" as type
FROM moz_places p
LEFT JOIN moz_bookmark m
ON m.fk = p.id
LEFT JOIN moz_favicons f
ON p.favicon_id = f.id
WHERE p.last_visit_date > current_date - interval '72' hour
AND  p.hidden = 0 AND p.last_visit_date NOTNULL
ORDER BY frecency DESC, lastVisitDate DESC, url;
```

It is a history type of query, with bookmarkGuid and id as a marker of whether or not the link has been bookmarked.

The context surrounding this task is explained in #158.

**Comment by oyiptong** [comment]
I'm adding this to Alpha right now, but given the time constraints, this might need to be shifted over to Beta

**Comment by k88hudson** [comment]
There are more details in https://github.com/mozilla/activity-streams/issues/158, if you need more clarification let me know
