### ISSUE TITLE
Filter access to Embedly proxy?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#168]
Currently we have a dev-esque Embedly proxy server (see https://github.com/mozilla/activity-streams/issues/157) to proxy our calls to the Embedly API.

Do we have any plans (or abilities) to limit who can use the API endpoint?
This server seems like an excellent free alternative to me having to set up and pay for an Embedly account (for other unrelated projects) if I can just pipe all my requests through a Mozilla sponsored proxy and make those suckers pay the bills.

**Comment by tspurway** [comment]
embedly is going away post-release - wontfix
