### ISSUE TITLE
Set up internal download for addon

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-streams#169]
Starting on March 1, we'd like to distribute a version of the add-on for internal testing.

We'll need to:
* [ ] prepare the add-on 
* [ ] figure out how we're going to ship updates -- see #167
* [ ] upload it somewhere
* [ ] prepare an email and send it out

Note that we would like to put this somewhere that can only be accessed by staff.

cc @oyiptong @tspurway

**Comment by pdehaan** [comment]
Aren't we hosting this w/ Test Pilot? Or are we doing an internal launch before them?

**Comment by oyiptong** [comment]
@pdehaan this is for an internal launch.

We could put it up on people.mozilla.org with an htpassword, or on intranet.mozilla.org which requires LDAP auth.
