### ISSUE TITLE
this._addHiddenURLsTo is not a function 

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-streams#174]
When I create an xpi with `npm run package`, if I try to run it in Nightly (47.0a1), I get the following error on a new tab page:

```
NS_ERROR_MALFORMED_URI:  DOMUtils.js:37:0
TypeError: this._addHiddenURLsTo is not a function ActivityStreams.js:239:13
```

The `Timeline` page works fine.

Both pages work fine on Beta.

**Comment by k88hudson** [comment]
Actually, that makes sense -- the context https://github.com/mozilla/activity-streams/blob/master/lib/ActivityStreams.js#L239 is going to be the parent context, not the instance. I guess this function isn't getting hit most of the time, is that expected?

**Comment by rlr** [comment]
That specific one runs on new windows you open. There is another place where we call it on all open windows when things get inited. Or that's the intention!

**Comment by rlr** [comment]
oh I see what you are saying... `this` is effed because javascript

**Comment by k88hudson** [comment]
@rlr ahhh that must be it. but yeah, the context needs to be fixed up

**Comment by k88hudson** [comment]
Adding this to alpha since it's a breaking bug

**Comment by oyiptong** [comment]
Damn JavaScript

**Comment by k88hudson** [comment]
Yeah `this` bug is such a pain isn't it? :stuck_out_tongue_winking_eye:

**Comment by k88hudson** [comment]
JAVASCRIPT PUNS

**Comment by oyiptong** [comment]
Lol

**Comment by rlr** [comment]
grabbing to fix.
