### ISSUE TITLE
Implement identity services PR/commit style practices 

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-streams#18]
See https://github.com/mozilla/fxa/blob/master/CONTRIBUTING.md

**Comment by k88hudson** [comment]
Can you add a contributing.md for us? :dancer:

**Comment by marcoscaceres** [comment]
Will try to put something together later today.

**Comment by marcoscaceres** [comment]
Will just recycle https://github.com/mozilla/fxa/blob/master/CONTRIBUTING.md
