### ISSUE TITLE
Use the first letter of host for icon fallback

### ISSUE THREAD

**Issue by nchapman** [mozilla/activity-streams#180]
My embedly data isn't always showing up so this appears to be the very last fallback, but I think these should be the first letter of the host (B and G) rather than the first letter of the title (1 and 5).

![screen shot 2016-02-23 at 8 22 30 am](https://cloud.githubusercontent.com/assets/3095/13258128/b40d0ae4-da06-11e5-8f5c-39cb2af643f6.png)

**Comment by k88hudson** [comment]
Right now we're using the first letter of the `provider_name`, we should definitely use the first letter of the host at least as a fallback -- do you think `provider_name` is good if we have it?

**Comment by nchapman** [comment]
> we should definitely use the first letter of the host at least as a fallback -- do you think provider_name is good if we have it?

Cool, yeah `provider_name` should be good if it's there.

**Comment by pdehaan** [comment]
Odd, I thought it was falling back to the provider name, [./content-src/components/SiteIcon/SiteIcon.js:53](https://github.com/mozilla/activity-streams/blob/5fb7c704f92fd2a39dba4a3c5d92cb9d03c12cd1/content-src/components/SiteIcon/SiteIcon.js#L53):

```js
const letter = (provider_name || provider_display || title || "")[0];
```

http://embedly-proxy.dev.mozaws.net/extract?urls=https://bugzilla.mozilla.org/show_bug.cgi?id=1241319

```js
{
  'https://bugzilla.mozilla.org/show_bug.cgi?id=1241319': {
    app_links: [ ],
    authors: [ ],
    cache_age: 86394,
    content: null,
    description: null,
    embeds: [ ],
    entities: [ ],
    favicon_colors: [],
    favicon_url: "https://bugzilla.mozilla.org/extensions/BMO/web/images/favicon.ico",
    images: [],
    keywords: [ ],
    language: null,
    lead: null,
    media: { },
    offset: null,
    original_url: "https://bugzilla.mozilla.org/show_bug.cgi?id=1241319",
    provider_display: "bugzilla.mozilla.org",
    provider_name: "Mozilla",
    provider_url: "https://bugzilla.mozilla.org",
    published: null,
    related: [ ],
    safe: true,
    title: "1241319 - Synced tabs menu panel looks like I'm not logged in when I only have one device connected",
    type: "html",
    url: "https://bugzilla.mozilla.org/show_bug.cgi?id=1241319"
  }
}
```

**Comment by nchapman** [comment]
> provider_name || provider_display || title

It does fall back to `provider_name` but eventually hits the title. It should be `host` there instead. In fact we might find that using host is always the best thing to do. For example if `docs.google.com` has the provider name of "Google Docs" then we'll get a G for every Google thing which would be less useful.

**Comment by pdehaan** [comment]
Optimizing for "Google Docs". Spoken like a true manager. #sellout #youmakemesick
