### ISSUE TITLE
Top Sites Icon Issues

### ISSUE THREAD

**Issue by bryanbell** [mozilla/activity-streams#183]
![pasted_image_2_23_16__10_57_am](https://cloud.githubusercontent.com/assets/228979/13262987/8191b8c4-da1c-11e5-9485-f1d1f6d4dece.png)

getting some dark icons on dark backgrounds

**Comment by pdehaan** [comment]
![new_tab](https://cloud.githubusercontent.com/assets/557895/13543290/a5baeab8-e21e-11e5-9433-77ff9f92adeb.png)

Here's what a few different alpha values look on my screen (default alpha is currently [0.8](https://github.com/mozilla/activity-streams/blob/603206245c82b14f459b989a30ec9cde6fa571e8/content-src/components/TopSites/TopSites.js#L35)).

**Comment by k88hudson** [comment]
This should be resolved by https://github.com/mozilla/activity-streams/commit/77d30543b250afa200cfd7ca27d45f65c31988b3
