### ISSUE TITLE
Entropy isn't a great metric for how relevant an image is

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#192]
I've been playing with `npm run once` since it gives me a nice clean profile each time, and I'm [starting to notice](https://github.com/mozilla/activity-streams/pull/170#issuecomment-187414998) that it isn't always choosing the most relevant photo, just the [most complex](http://docs.embed.ly/docs/extract#response-attributes).

> "Image entropy can be roughly thought of as how "busy" an image is. Image entropy can be useful in programmatically choosing the type of image to display. For instance, if an API user wants to display photographic type images, but not logos, they can ignore images with lower entropy."
>
> &mdash; via http://docs.embed.ly/docs/extract#response-attributes (see `images` attribute docs)

I've been browsing www.ign.com reviews and am anecdotally noticing that the first image in the `images[]` array is usually the most accurate. In my case, the image with the highest entropy that gets chosen, is a random avatar on the page, rather than the massive header image for the article.

![new_tab](https://cloud.githubusercontent.com/assets/557895/13270813/62195f32-da45-11e5-9e71-afb1fdfa72ea.png)

**Comment by k88hudson** [comment]
Hmm, interesting! Perhaps we could try an entropy threshold instead, or just always go with the first image. Any thoughts @nchapman @bryanbell?

**Comment by nchapman** [comment]
First image is probably fine. I used a minimum threshold of 1.75 [previously](https://github.com/nchapman/chronicle/blob/master/app/models/page.rb#L5).

**Comment by pdehaan** [comment]
Yeah, the funny bit here was that all images had an entropy of 6.2 to 6.7, but it turns out the lowest entropy image in this case was the most relevant (from this limited sampling of 1-2 pages).
