### ISSUE TITLE
Improve ActivityStream icons

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#193]
Running the latest code from master (0e6e8f7) and I just noticed that all my ActivityFeed items always use the fallback icon instead of the site's favicon (which is used in Top Sites, and Spotlight results).

![new_tab](https://cloud.githubusercontent.com/assets/557895/13272190/2f946a34-da4f-11e5-9130-b0127b4c6377.png)

**Comment by k88hudson** [comment]
We need to clarify exact requirements here, design is here:
![image](https://cloud.githubusercontent.com/assets/1455535/13399917/754e3d74-ded3-11e5-963c-32115e18ea1f.png)
