### ISSUE TITLE
Remove basic auth and query string for embedly requests

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-streams#196]
I'm a little bit concerned about us leaking really sensitive stuff in urls the embedly requests, so I'm wondering if we should see how good the results are if we remove basic auth/query strings (just for embedly). We can still show the full URL locally, just not send it out over the wire.

It could be that this is *too* restrictive, but let's play with this/try something out.

**Comment by oyiptong** [comment]
I think this is very important and relatively easy to implement

:+1:

**Comment by pdehaan** [comment]
Sounds smart (I was playing w/ some basic auth URLs the other day and wasn't seeing those results showing up in my history, but I may have been missing something), but I was just thinking that this may break a few sites if we remove _all_ of the query string.
For example, WordPress has the option to use something like `/?p=123` for permalinks, so if we blindly remove ALL the query variables, presumably we'd only ever be able to scrape the front page of several blogs. Not sure how many other sites out there do similar things, but it may be something to consider.

```js
const urlParse = require("url-parse");

function sanitizeUrl(url) {
  const REMOVE_KEYS = ["query", "username", "password", "auth"];
  const parsedUrl = urlParse(url);

  REMOVE_KEYS.forEach((key) => parsedUrl.set(key, ""));
  if (!parsedUrl.protocol) {
    parsedUrl.set("protocol", "https:");
  }
  return parsedUrl.toString();
}
```

**Comment by pdehaan** [comment]
I guess the other use case would be search queries.
For example, searching for "bananas" via the awesome bar gives the following URLs:
- https://search.yahoo.com/yhs/search?p=bananas&ei=UTF-8&hspart=mozilla&hsimp=yhs-002 (Yahoo!) 
- https://www.google.com/search?q=bananas&ie=utf-8&oe=utf-8 (Google)
- https://duckduckgo.com/?q=bananas&t=ffsb&ia=meanings (DuckDuckGo)
- https://www.bing.com/search?q=bananas&pc=MOZI&form=MOZSBR (Bing)
- https://www.amazon.com/s/184-5029709-2090817?ie=UTF8&field-keywords=bananas&index=blended&link_code=qs&sourceid=Mozilla-search&tag=mozilla-20 (Amazon)
- https://en.wikipedia.org/wiki/Banana (Wikipedia)
- https://twitter.com/search?q=bananas&partner=Firefox&source=desktop-search (Twitter)

If we remove the query string, we'd probably just scrape the main pages and not get accurate Embedly results back (unless we add special logic to try and preserve the `?p=` and `?q=` params and see how many search engines that works for (spoiler alert: not Amazon)).

**Comment by k88hudson** [comment]
@pdehaan keeping `p`/`q` might be a good idea. I think in general the images/embedly data for searches tends not to be that interesting anyway...but yeah, worth seeing what this breaks

**Comment by k88hudson** [comment]
Also I think we should definitely land this before shipping our internal alpha. Marking as critical

**Comment by pdehaan** [comment]
A few more casual observations from my random browsing habits:
1. [//news.ycombinator.com/item?id={term}](https://news.ycombinator.com/item?id=11175258) &mdash; Hacker News uses `?id=` to specify articles/pages.
2. [//chipotle.com/searches/#/?query={term}](http://www.chipotle.com/searches/#/?query=barbacoa) &mdash; Chipotle uses `?query=` for search results.

I think it's _imperative_ that we support a Chipotle workflow for V1.

Current proposed "allowed" query params:
- `?q=`
- `?p=` (for Yahoo! and WordPress support)
- `?id=`
- `?query=`

**Comment by oyiptong** [comment]
that sounds good. we can make this a whitelist of query parameters to let through

**Comment by pdehaan** [comment]
Not pretty, but maybe "good enough" for now:
```js
function sanitizeUrl(url) {
  const ALLOWED_PARAMS = new Set(["id", "p", "q", "query", "s", "search", "sitesearch"]);
  const REMOVE_KEYS = ["auth", "password", "username"];
  const parsedUrl = urlParse(url, true);
  const safeQueryParams = {};

  REMOVE_KEYS.forEach((key) => parsedUrl.set(key, ""));

  Object.keys(parsedUrl.query)
    .filter((param) => ALLOWED_PARAMS.has(param))
    .forEach((param) => safeQueryParams[param] = parsedUrl.query[param]);
  parsedUrl.set("query", safeQueryParams);

  if (!parsedUrl.protocol) {
    parsedUrl.set("protocol", "https:");
  }

  return parsedUrl.toString();
}
```

**Comment by k88hudson** [comment]
@pdehaan if you make this function take a `site`, you can use the `.parsedUrl` object (the [middleware here](https://github.com/mozilla/activity-streams/blob/master/content-src/lib/parse-url-middleware.js) now adds it so it doesn't have to be regenerated every time we need it)

**Comment by k88hudson** [comment]
@pdehaan also, feel free to put up a PR
