### ISSUE TITLE
Add some sort of pagination to Recent Links API query

### ISSUE THREAD

**Issue by rlr** [mozilla/activity-streams#198]
We need a way to go further back in history. We also probably need a way to get "future" activity after the last time we queried. @k88hudson suggested we could just have a AFTER/BEFORE=&lt;timestamp&gt; parameter.

**Comment by oyiptong** [comment]
`BEFORE` is probably what we want here for the simple case, but it might produce more results than we need still, so we need a `LIMIT` parameter as well, to cater for larger resolutions.

This is for "infinite" scrolling, right? Having the total number of pages is not important here, I assume.

**Comment by rlr** [comment]
Yeah, I am not sure what the UI looks like but some sort of infinite scroll is what I am guessing...

Say we get notified of newer history, don't we want to just grab the stuff newer than what we have?

**Comment by oyiptong** [comment]
We can add the history items to our internal representation as they happen, right?

**Comment by oyiptong** [comment]
If everything else fails, we can always request the most recent links on pageload. that would guarantee freshness.

**Comment by rlr** [comment]
Truth :+1:
