### ISSUE TITLE
Improve first run experience for empty profile

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#200]
I'm becoming disturbingly obsessed with `npm run once` and noticed that the "New Tab" page looks exceedingly barren if you have no browsing history.

Not sure if we want to hide the empty sections (or if they're all placeholders) or have some sort of whimsical splash for brand new Firefox installs &mdash; or maybe even add some sponsored tiles(tm)!

Currently my brand new Firefox Profile looks like this:

![new_tab](https://cloud.githubusercontent.com/assets/557895/13305682/f49ea7be-db11-11e5-9be5-7bc37b4f91f7.png)

**Comment by pdehaan** [comment]
IIRC, we're losing the "Top Activity" section there with the two default Firefox bookmarks (ref: https://github.com/mozilla/activity-streams/pull/197#discussion-diff-53992295)

**Comment by oyiptong** [comment]
Good observation. I can only agree.

It might make sense to pre populate the top sites section at least, with say the Alexa top N.

First site will probably be Facebook, followed by YouTube or something for most people.

**Comment by pdehaan** [comment]
/summon @nchapman (so he can enjoy my "sponsored tiles" quip... and give some direction)

**Comment by nchapman** [comment]
Default top sites should be:

1. Facebook
2. YouTube
3. Amazon
4. Yahoo
5. eBay
6. Twitter

Spotlight will borrow from our existing directory tiles. Want to use "android", "sync", and "add-ons":

![screen shot 2016-02-29 at 2 49 48 pm](https://cloud.githubusercontent.com/assets/3095/13411732/b391ed40-def3-11e5-8255-636afd158805.png)

@bryanbell will provide a design for those spotlight cards.

Hide recent activity if there's no data, although I think we'll always end up showing the default bookmarks.

**Comment by pdehaan** [comment]
@nchapman had an alternate proposal in IRC with the following "Top Sites" URLs:

1. Facebook
1. YouTube
1. Amazon
1. Twitter
1. Reddit
1. Netflix

**Comment by bryanbell** [comment]
![example](https://cloud.githubusercontent.com/assets/228979/13514532/96c6cc4a-e15e-11e5-9617-0f35c3204438.png)
example

**Comment by edmoz** [comment]
@k88hudson do we need anymore input from PM/UX?  I'm not sure where we get those spotlight images or icons.

**Comment by nchapman** [comment]
> I'm not sure where we get those spotlight images or icons.

@bryanbell can provide assets.

**Comment by nchapman** [comment]
We should hide Top Activity when there's no history.
