### ISSUE TITLE
Initial New Tab is always blank when running npm run once

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#201]
Not sure if this is just me, but whenever I run `$ npm run once`, the first "New Tab" tab is blank (as in, nothing visible or no content in <<view-source:about:blank>>).

Opening a new tab shows the correct/expected content.

![mozilla_firefox](https://cloud.githubusercontent.com/assets/557895/13305760/9ce89f38-db12-11e5-8aaa-d4df8bfa2397.png)

I'm thinking this may be due to my about:preferences#general "Home Page" being set (or defaulted) to "about:blank". I assume JPM may be setting that config. If I click the [Restore to Default] button in preferences, the Home Page gets set to _Mozilla Firefox Start Page_, but then always resets the next time I run `$ npm run once`.

![preferences](https://cloud.githubusercontent.com/assets/557895/13305848/7790c7fa-db13-11e5-815c-3e8859de20ec.png)

**Comment by k88hudson** [comment]
This seems to be the case for the default profile used by `jpm run`, so I don't think this needs to be fixed
