### ISSUE TITLE
Remove "Last opened on iPhone" placeholder text

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#202]
Currently we have a _"Last opened on iPhone"_ string hardcoded in [./content-src/components/Spotlight/Spotlight.js:52](https://github.com/mozilla/activity-streams/blob/95390eb65232c0e64087faa841174fd8def58575/content-src/components/Spotlight/Spotlight.js#L52).

Not sure if we want to remove that text (or replace it with a prettified `provider_display`) until it shows real data (and we can sync w/ mobile devices to get that information). Or something.

![new_tab](https://cloud.githubusercontent.com/assets/557895/13306473/d908f2aa-db18-11e5-843f-d7308a3a5cd6.png)

**Comment by k88hudson** [comment]
I think what we should do for now is after https://github.com/mozilla/activity-streams/pull/186 lands, as well as @rlr's moment.js patch, we should

* show `"Visited [relative time]` if it was not bookmarked recently
* show `"Bookmarked [relative time]` if it was bookmarked 

e.g. `Visited 2 hours ago` `Visited yesterday` etc.
