### ISSUE TITLE
Unify timestamps across PlacesProvider queries and tests

### ISSUE THREAD

**Issue by mzhilyaev** [mozilla/activity-streams#204]
FX keeps dates in microseconds, but PlacesProvider and corresponding tests insert/retrieve timestamps in milliseconds.  Some of the queries retrieve some dates and convert them into milliseconds and some do not....  So, this mess needs a cleanup and unification

**Comment by oyiptong** [comment]
We also need to fix the front-end in this commit

**Comment by pdehaan** [comment]
Handy little search that shows all the places we're doing some date magic with `1000`:
https://github.com/mozilla/activity-streams/search?q=1000&type=Code&utf8=%E2%9C%93
