### ISSUE TITLE
Removing the add-on doesn't restore the new tab page

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-streams#206]
STR:

1. Install add-on, add-on is working
2. Remove add-on
3. Visit new tab page

Actual: new tab is blank
Expected: new tab page should be old new tab page

**Comment by rlr** [comment]
I tried adding `NewTabURL.reset();` to the `unload()` of `ActivityStreams` but no luck.

**Comment by rlr** [comment]
After restarting the browser the normal newtab page is back though. Seems like possibly a bug in the reset code?

**Comment by rlr** [comment]
landed
