### ISSUE TITLE
Deployment script for addons

### ISSUE THREAD

**Issue by oyiptong** [mozilla/activity-streams#219]
We need a deployment script that will:

1. package the addon
2. sign the addon
3. set the upload URL
4. upload to s3

**Comment by pdehaan** [comment]
Related: https://github.com/mozilla/testpilot/issues/406 and https://github.com/mozilla/testpilot/issues/92

**Comment by oyiptong** [comment]
very relevant indeed

this deployment script will be temporary until mozilla/testpilot#406 is complete

**Comment by lmorchard** [comment]
Also, we should share notes. Whatever ends up working for you is probably the kind of thing we want to do for Test Pilot itself - and hopefully we make it as convenient as possible!
