### ISSUE TITLE
Delete UI MVP

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-streams#221]
This is the MVP spec for April first launch (discussed with @bryanbell):

#### Functionality

Delete buttons should **delete the individual history entry** (not bookmarks, if they exist).

#### Spotlight UI
![image](https://cloud.githubusercontent.com/assets/1455535/13404507/dfe3a520-dee7-11e5-8204-4a5ba624be49.png)

#### Activity Feed UI
* comp (show on hover, delay showing menu by `250ms`) ![image](https://cloud.githubusercontent.com/assets/1455535/13404330/248e24da-dee7-11e5-853e-aaae0b07d153.png)
*  Share button could just use a [twitter intent](https://dev.twitter.com/web/tweet-button/web-intent) for now
* `...` could be an alert saying "we're working on a better/blocking delete solution"

Note that this will all be expanded via https://github.com/mozilla/activity-streams/issues/105 post-MVP.

**Comment by rlr** [comment]
landed. :rocket:
