### ISSUE TITLE
Add pagination UI

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-streams#222]
Blocked on https://github.com/mozilla/activity-streams/issues/198 for implementation

We just need some UI for loading more stuff/next on the Timeline

**Comment by pdehaan** [comment]
Not sure how relevant [the invision spec](https://mozilla.invisionapp.com/share/GA5RW90CW#/screens/130804847) is anymore, but it shows a "Show 7 more" link at the bottom of the page.

**Comment by bryanbell** [comment]
When the user gets to the bottom we should show a "loading more items" spinner. Hopefully, it will load so fast that they never get to see that. 

When in doubt it should work like the Twitter Feed.

**Comment by bryanbell** [comment]
![pasted_image_3_2_16__9_44_am](https://cloud.githubusercontent.com/assets/228979/13469247/539f8226-e05b-11e5-9bd6-152dacddd9a6.png)

example

**Comment by k88hudson** [comment]
Blocked don https://github.com/mozilla/activity-streams/issues/312

**Comment by pdehaan** [comment]
@k88hudson Is this finished now that #318 has merged, or are we still blocked on something?

**Comment by k88hudson** [comment]
This is mostly completed by #318, we just need to add pagination to the bookmarks view
