### ISSUE TITLE
opening new tab should have url selected

### ISSUE THREAD

**Issue by edmoz** [mozilla/activity-streams#223]
1. open a new tab
2. start typing

actual: when i type - it appends it to the end of the current url as such:
resource://activity-streams/data/content/activity-streams.html#/<MY_INPUT_GOES_HERE>

this is a regression from current Release Firefox - this is my normal flow for opening new URLs

expected: the URL should be selected or delete the current URL upon text input.

**Comment by k88hudson** [comment]
See https://github.com/mozilla/activity-streams/issues/236 for more details

**Comment by edmoz** [comment]
word is that there's an upstream change that broke us...

**Comment by oyiptong** [comment]
@rlr says this broke our url bar clearing logic: https://github.com/mozilla/gecko-dev/commit/96797e42b2ed2ead220c6fbb7008f05cb6331bd9

**Comment by rlr** [comment]
landed!

**Comment by k88hudson** [comment]
Nice work @rlr!
