### ISSUE TITLE
Inconsistent SiteFallbackIcon behavior

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#229]
I noticed in a recent PR that I'm not getting consistent SiteFallbackIcon behavior.
The current flow should be:
```js
const letter = (provider_name || provider_display || title || "")[0];
```
&mdash; via [./content-src/components/SiteIcon/SiteIcon.js:53](https://github.com/mozilla/activity-streams/blob/e4d3ec3e303607594640e50055fa26f9ecb31607/content-src/components/SiteIcon/SiteIcon.js#L53)

![new_tab](https://cloud.githubusercontent.com/assets/557895/13410291/cad3042e-deeb-11e5-8a5b-bf1f46d1bbfe.png)

As you can see in the above screenshot, I get favicon colors and a fallback letter of "Y" for https://search.yahoo.com/search?p=barbacoa but for my https://search.yahoo.com/yhs/search?p=cornbread+recipes it has a fallback letter of "C" (presumably for cornbread).

I added some local logging, and it looks like my `this.props` from `SiteIconFallback#render()` looks something like this:
```js
console.log(JSON.stringify(this.props, null, 2));
const letter = (provider_name || provider_display || title || "")[0];
```

#### Output:
```json
{
  "url": "https://search.yahoo.com/yhs/search?p=cornbread+recipes&ei=UTF-8&hspart=mozilla&hsimp=yhs-001",
  "title": "cornbread recipes - - Yahoo Search Results",
  "lastVisitDate": 1456782311254,
  "frecency": 100,
  "favicon": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAADA0lEQVQ4jV2RS0xcZRiG3/l7zn9Ku4F127hyqUFnzthTGFJoGaZOmCmkHVqKMdq68EKRAGFahVKSUsCApoPdcDOOYoSZJk2KXVgSKaVNmhiN2jQYoxvZGRftmnlcIFPjl7z57pc3n8LqJKIuwupaC6vnnK8PDlRrqHIHtcpW1epqVbWGKl/R0P6Ius+G1fVgu6cTRZUlpo9o0BRx+ymHQ5PEzCgxM0qtuUKtuVL2D4cmaVCOBk0R0zhRZVGgS8T1GcdDN/nzt78BSDsFUs4Sze7XpNxFUs4Sx20RSvD7L3+R1k0aNUegSyjQMEkt0eZ8x4ev32NHTtu7nLKrnLKrtHt3y/GBN++RMasktUSgYRToMsnQIm1mjdfchzz64Q8Apt59RId3nw7vPhNv/ATA52Pf0+E8pM2s8WroKwJdRoEGnqRMkZPOCu3uOmfssyvOeOt07F5/5tt12t11TjorpEyBQANPdFAXN5vMPK3ON2Tst7R5d5gdfgxAfvxXPnnrZ0olmB1+TJu3QsbeocVZpsnMc1AXNxVVdqPJzJN2i7TaW5zwlsnsuc1/pVSCzJ7bnPCWabW3SLkFmsw8UWU3FFV2I26mSboLpG2BFq9Ia0WxzBtg7MyPtFbcoMUrkLYFku6XxM309gBf/ZsNJkfCmSdp8zR7edIVC5x+vri9fatE5rlF0hULNHt5kjZPwpmjwVzDV/+mIup/WmcmaHSuE3enSdgZjnkzJPfOAbC1VSK5d45j3iwJO0PcnabRuU6dmSCi/qfy1UdNaIR68zFHnBxH7TXiNkfcmypTiHtTxG2OozbHESdHvZmkJjSCrz4UUQ+BhqgxI8R2jVLnjFHvjtNckS9TaN79BfXuGHXOGLFdo9SYqwQaIqIeFFY3UV0g0ACBGSQwgxxyB0nsmyx/ILFvkkPOYDkfaJCoLhBWNwqrC1+9+OrDVx/RUC++6SX6P/imdzv3b52vXsLqQmF1so3za2GdP+frnQPVer/yBb1dtaN37BfVuf8lvXf2ZXU+2On7B+kzEw3V663qAAAAAElFTkSuQmCC",
  "type": "history",
  "parsedUrl": {
    "hash": "",
    "query": {
      "p": "cornbread+recipes"
    },
    "protocol": "https:",
    "pathname": "/yhs/search",
    "auth": "",
    "host": "search.yahoo.com",
    "port": "",
    "hostname": "search.yahoo.com",
    "password": "",
    "username": "",
    "href": "https://search.yahoo.com/yhs/search?p=cornbread%2Brecipes"
  },
  "width": 32
}
```

So you can see that this response doesn't have a `provider_name`, or `provider_display`  key, so it falls back to `title`.

In an unexpected twist, here's my devtools proxy response from the embedly server:
![new_tab_and_inbox__2_162__-_pdehaan_mozilla_com_-_mozilla_mail](https://cloud.githubusercontent.com/assets/557895/13410488/eb21fa0e-deec-11e5-9ed8-435f48cfe610.png)

**Comment by pdehaan** [comment]
Another use case from me browsing some Facebook pages. Turns out that we handle private Facebook pages beautifully &mdash; but we get all sorts of random fallback letters:

![new_tab](https://cloud.githubusercontent.com/assets/557895/13469760/8cb59eae-e05d-11e5-9b17-95c639adf36a.png)

So I have two "Top Sites" results for "facebook.com" which go to different pages, but only 1 shows the facebook favicon and colors.
Most Facebook results seem to be falling back to the page title, which is the user's name. So it looks like we're never getting the correct favicons or colors.

**Comment by pdehaan** [comment]
In fact, here's a better example... I've been using this Firefox profile today to do some basic tasks and I flagged all the fallback site icons which I think are incorrect (not using the site provider name and reverting to `title`, not using the favicon colors, etc). I'll need to dig in a bit deeper to see if we just aren't getting correct data back from the embedly proxy, or if we're just not passing the data along far enough in the pipeline.

![new_tab](https://cloud.githubusercontent.com/assets/557895/13476686/d83bae66-e07d-11e5-9075-a3d85c95fdcf.png)

**Comment by Soche89** [comment]
I think I got something similar on my end when I used my personal profile with lots of history and bookmarks for testing the import of information. The Yahoo email page is strangely displayed in "top sites" and "top activity" when logged in (new tab).

![logged in yahoo mail issue](https://cloud.githubusercontent.com/assets/17258026/13527853/e53961c8-e21a-11e5-9fe7-eaed6462f0e6.png)

**Comment by edmoz** [comment]
@pdehaan Kate believes this is fixed, can you confirm?

**Comment by pdehaan** [comment]
Assigning to @pdehaan for re-triage to see if this was addressed by recent PRs.

**Comment by pdehaan** [comment]
This looks good to me in recent builds, and I'm not seeing the fallback behavior for any of my sites.
I think there is still an issue with it not consistently using a favicon background color (note that my 6 Facebook results use 2 different background colors, as do my npmjs.com results -- but I think that is currently tracked in #337 and #338).

![activity_stream](https://cloud.githubusercontent.com/assets/557895/13932510/8a00c17c-ef65-11e5-965c-f6c26c0c87ca.png)

Closing.
