### ISSUE TITLE
Duplicate items in spotlight 

### ISSUE THREAD

**Issue by bryanbell** [mozilla/activity-streams#232]
![pasted_image_2_29_16__4_20_pm](https://cloud.githubusercontent.com/assets/228979/13413608/ab4d771e-df00-11e5-855c-4532dd0d78cc.png)

and subsequent pages in a single story. 

![pasted_image_2_29_16__4_32_pm](https://cloud.githubusercontent.com/assets/228979/13413770/05a839fa-df02-11e5-8eea-0e32fd7b7cdb.png)

**Comment by pdehaan** [comment]
I'm not certain if subsequent pages in a single story are "duplicate". If they have different URLs, how would we know if they are a single [continued] article vs two separate articles?

**Comment by oyiptong** [comment]
In this specific instance, it doesn't seem these two URL's are duplicates of each other.

One points to slate's home page, another points to an article page.

However, the issue of url parameters remains. We should probably obtain the 'canonical url' if it exists, from the page's metadata.

**Comment by edmoz** [comment]
@bryanbell I believe this is fixed, can you retest.

**Comment by tspurway** [comment]
totally fixed
