### ISSUE TITLE
New tab page leaves an item in the history stack.

### ISSUE THREAD

**Issue by rlr** [mozilla/activity-streams#247]
Not sure if I am using the right terminology, but pretty sure this shouldn't happen:
<img width="150" alt="screen shot 2016-03-01 at 5 45 14 pm" src="https://cloud.githubusercontent.com/assets/36629/13446380/196773ae-dfe1-11e5-8b83-1f99af1131ec.png">

I'm not sure if the Timeline and Bookmark pages should be in the history, but they currently are too.

**Comment by oyiptong** [comment]
It seems that resource urls are not stored in places.sqlite. The history is only saved for the tab's session, which is OK.

Closing this issue.

**Comment by oyiptong** [comment]
```sql
sqlite> select count(*) from moz_places where url like 'resource://%';
count(*)
----------
0
```
