### ISSUE TITLE
Odd UI in Activity Stream when a page doesn't have a usable title

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#248]
During random browsing I noticed that certain sites don't seem to have a title (whether they were an image, JSON, or a redirect), that you end up with just a mis-aligned looking link.

![new_tab](https://cloud.githubusercontent.com/assets/557895/13446995/ce55c276-dfcc-11e5-91da-e780771eee2a.png)

Not sure  how/if we want to fix that, but thought I'd file it for giggles so we can see if we want to fall back to a `provider_name` or `provider_display` or something (assuming it isn't too redundant).

1. http://embedly-proxy.dev.mozaws.net/extract?urls=https://raw.githubusercontent.com/mozilla/activity-streams/master/dev-prefs.json

  ```js
{
  "https://raw.githubusercontent.com/mozilla/activity-streams/master/dev-prefs.json": {
    provider_display: "raw.githubusercontent.com",
    provider_name: "Raw",
    provider_url: "https://raw.githubusercontent.com",
    title: null,
    type: "text",
    url: "https://raw.githubusercontent.com/mozilla/activity-streams/master/dev-prefs.json",
    // ....
  }
}
```

2. http://embedly-proxy.dev.mozaws.net/extract?urls=https://christianalfoni.github.io/react-webpack-cookbook/Structuring-configuration.html

  ```js
{
  "https://christianalfoni.github.io/react-webpack-cookbook/Structuring-configuration.html": {
    provider_display: "christianalfoni.github.io",
    provider_name: "Christianalfoni",
    provider_url: "https://christianalfoni.github.io",
    title: null,
    type: "html",
    url: "https://christianalfoni.github.io/react-webpack-cookbook/Structuring-configuration.html",
  }
}
```

**Comment by oyiptong** [comment]
I would defer to the designers on the team. My personal opinion would be to have the URL be laid out where it would be if there were a title.

**Comment by bryanbell** [comment]
<img width="720" alt="no_title_example" src="https://cloud.githubusercontent.com/assets/228979/13583294/54481996-e465-11e5-9f7f-35ea1efd4b35.png">

If we're missing a title we should use the qualified domain name as the title. followed by the full URL in the usual position. 

Replacement fav icons should use the first letter of the sub-domain if applicable, or the first letter of the domain name. In this example "C" is the first letter of the sub-domain.
