### ISSUE TITLE
Try and merge embedly proxy requests?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#250]
Currently it looks like we're making _3_ requests to our [embedly-proxy](https://github.com/mozilla/embedly-proxy) each time you open the **New Tab** page.

It looks like my first embedly proxy request is for 8 URLs (presumably for Top Sites results)
The second embedly proxy request is for 16 URLs (presumably for Top Activity/Spotlight results)
The third embedly proxy request is for 5 URLs (which I think are unused since they are all mozilla.org/ links &mdash; see #228)

Since many of the URLs are currently duplicated in the first 2 requests, not sure if it's possible to try and merge the embedly proxy requests into a single request to reduce the number of in flight requests, bandwith, and wasted data.

![new_tab_and_new_tab_-__private_browsing_](https://cloud.githubusercontent.com/assets/557895/13472831/6a0b4bca-e06b-11e5-8c99-7767d587e0a0.png)
**Request 1:** 8 `?urls=`; 23.48 KB response

---

![new_tab_and_new_tab_-__private_browsing_](https://cloud.githubusercontent.com/assets/557895/13472860/95ffe006-e06b-11e5-8826-a962dd03863c.png)
**Request 2:** 16 `?urls=`; 34.79 KB response

---

![new_tab_and_new_tab_-__private_browsing_](https://cloud.githubusercontent.com/assets/557895/13472890/ba5cc676-e06b-11e5-88ff-2879ed9582b7.png)
**Request 3:** 5 `?urls=`; 16.81 KB response (which is piped to /dev/null)

**Comment by k88hudson** [comment]
This should be resolved by caching results from embedly, i.e. https://github.com/mozilla/activity-streams/issues/5
