### ISSUE TITLE
Modify timeout limit for failed embedly proxy fetches

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#251]
Not sure what happened here, but I was waiting ~30s for the embedly proxy to respond to one of my requests (which eventually 502ed) and noticed that rendering of the page seemed to wait until I got that response.

I've seen other cases of responses being slow (5-8s) but this was the first time I've had to wait 30s. We should probably see if we can set some `fetch()` timeout limit on that request so it fails faster.

![new_tab](https://cloud.githubusercontent.com/assets/557895/13475220/82f5ae72-e076-11e5-8173-19f611a2c551.png)

**Comment by pdehaan** [comment]
URL in question was:

http://embedly-proxy.dev.mozaws.net/extract?urls=http%3A%2F%2Fwww.converse.com%2Fus%2Fen%2Fregular%2Fchuck-taylor-all-star-%252770-sir-tom-baker%2F153037C_065.html&urls=http%3A%2F%2Fwww.converse.com%2Fus%2Fen%2Fregular%2Fchuck-taylor-all-star-%252770-creeper%2F153068C.html&urls=https%3A%2F%2Fwww.google.com%2Fsearch%3Fq%3Dso%252Bmote%252Bbe%252Bit&urls=http%3A%2F%2Fwww.converse.com%2Fus%2Fen%2Flanding-limited-edition&urls=http%3A%2F%2Fwww.converse.com%2Fus%2Fen%2Fregular%2Fchuck-taylor-all-star-ii-reflective-camo-%2FID00113.html&urls=http%3A%2F%2Fwww.converse.com%2Fus%2Fen%2Fproducts%2Fconverse%2Fchuck-taylor-all-star-ii-2&urls=http%3A%2F%2Fwww.converse.com%2Fus&urls=http%3A%2F%2Fwww.converse.com%2F&urls=http%3A%2F%2Fmashable.com%2F2016%2F03%2F02%2Fconverse-s-new-chuck-taylors-will-light-up-your-night%2F%23qaX7xJijnGqc&urls=https%3A%2F%2Fnodejs.org%2Fdist%2F&urls=https%3A%2F%2Fnodejs.org%2Fen%2Fdownload%2F&urls=https%3A%2F%2Fnodejs.org%2Fen%2Fdownload%2Fstable%2F&urls=https%3A%2F%2Fgithub.com%2Fnodejs%2FLTS%23lts_schedule&urls=https%3A%2F%2Fnodejs.org%2Fen%2F&urls=https%3A%2F%2Fnodejs.org%2F

Or the prettier list is:

![new_tab_and_webpack_config_js_ _activity-streams](https://cloud.githubusercontent.com/assets/557895/13475289/df7a694e-e076-11e5-93ba-c295167e0b6f.png)

**Comment by pdehaan** [comment]
Also filed https://github.com/mozilla/embedly-proxy/issues/42, in case it is easier to handle from the nginx proxy side rather than abort a sent `fetch()` request (which seems either poorly documented at best or undocumented at worst -- if it's even possible at all).

**Comment by oyiptong** [comment]
we should have a timeout in #258. Since our client works async, this timeout can be fairly high, in the order of multiple seconds.

**Comment by oyiptong** [comment]
@pdehaan can you please verify if this is still an issue?

**Comment by pdehaan** [comment]
With all the added caching and perf tweaks, I'm not able to repro this anymore. Closing for meow.
