### ISSUE TITLE
Use POST instead of GET when sending requests to embedly-proxy

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#259]
Re: https://github.com/mozilla/embedly-proxy/pull/41#discussion_r54796687,

We should switch from GET to POST when sending URLs to the proxy.

So we'll need to update the [`fetch()`](https://github.com/mozilla/activity-streams/blob/e4d3ec3e303607594640e50055fa26f9ecb31607/content-src/lib/embedly-middleware.js#L41) code in the embedly-middleware, as well as the artificial max line length check in [./content-src/lib/filters.js:30-32](https://github.com/mozilla/activity-streams/blob/aef8f31de7d757ad69120560ea4954aed9ccd4cc/content-src/lib/filters.js#L30-L32).

**Comment by oyiptong** [comment]
this will be handled in #258. I'll close as a duplicate

**Comment by pdehaan** [comment]
We now support POST on the proxy (via a /v2/extract route currently)!
For my own `fetch()` reference, here was my dirty test script:
```js
fetch("https://embedly-proxy.dev.mozaws.net/v2/extract", {
  method: "POST",
  headers: new Headers({
    "Content-Type": "application/json"
  }),
  data: JSON.stringify({
    urls: [
      "https://bing.com/"
    ]
  })
}).then(console.log);
```

Or the same nonsense with cURL:
```bash
curl -XPOST 'https://embedly-proxy.dev.mozaws.net/v2/extract' -d '{"urls":["https://www.mozilla.org/","https://developer.mozilla.org/en-US/docs/Web/JavaScript"]}' -H "Content-Type: application/json"
```
