### ISSUE TITLE
manually updating addon and opening a new tab causes browser to hang

### ISSUE THREAD

**Issue by edmoz** [mozilla/activity-streams#267]
1. I'm on mac. install an old version of ActStm addon
2. goto about:addons > click on gear icon > check for updates
3. watch it download and update. wait for it to complete
4. open a new tab

actual: browser hangs or is unresponsive, i can't close tabs or get to prefs, I force quit.

expected: browser should be responsive and new tab should open with ActStm

**Comment by rlr** [comment]
@edmoz I am unable to reproduce this locally. Can you see if it still happens for you?

I've been starting with v1.0.1 (https://s3.amazonaws.com/moz-activity-streams/dist/activity_streams_experiment-1.0.1-fx.xpi). I install it, open new tab page and make sure it works. Go to about:addons and make sure version is 1.0.1. I check for updates and it updates to 1.0.2. Then I make sure new tab page still works and it does.

**Comment by edmoz** [comment]
I can't repro this anymore, closing as fixed.
