### ISSUE TITLE
Determine constraints/what needs to be collected in our data pipeline

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-streams#27]
If we are collecting data in splice:

* what data do we need
* what are the constraints?

Notes:
* legal constraints are determined by TestPilot
* Product to fill in exact data requirements/KPIs

@tspurway do you want to add some clarification here?

**Comment by k88hudson** [comment]
@nchapman can you help wrap up the requirements here?

**Comment by ncloudioj** [comment]
## Target metrics
- [ ] GUID
- [ ] duration (in millisecond?)
- [ ] position (click position: [spotlight | top sites | top activity | timeline])
- [ ] scroll depth
- [ ] device
- [ ] OS
- [ ] browser
- [ ] version
- [ ] country
- [ ] locale
- [x] time stamp

## Other metrics (TBD)
- [ ] number of newtabs opened per user
- [ ] number of opt-out users
- [ ] disable or remove content
- [ ] retention rate ??

Thoughts? @oyiptong @tspurway @nchapman @k88hudson @emtwo

**Comment by tspurway** [comment]
GUID needs to persist over time.  Initially could be FxA ID?  Test Pilot ID?

Scroll position could always be tracked with 'click' metrics.

quick and dirty duration could be (start timer on newtab) - (stop timer on 'defocus') (send ping)

Basic navigation and interaction events should be tracked.

On click we will track what position the clicked item was and scroll depth.

how old are the items that users are clicking on (ages should be client time differences (in seconds))?

check out mixpanel and GA data formats (use standard ping/metrics formats)

add-on version, experiment versions, cohort id, etc.

performance metrics - load times, latencies, 

size of history, number of bookmarks, time spent in the browser (active usage hours)

**Comment by tspurway** [comment]
We are defining an Activity Stream `session` as the time between when the newtab page gains and looses focus.  We will grab a timestamp on each of these events and report the difference as `session_duration` for every ping.

A ping will be sent whenever the session ends (which will be when the tab looses focus).  The ping will contain the following data:

- client_id (unique id for user)
- tab_id (unique id for that user's newtab)
- load_reason (newtab, refocus, restore)
- source (timeline or activity_stream)
- search (indicates a search was performed)
- top_site_click (0 or 1)
- max_scroll_depth (int)
- click_position (index of object clicked on a click event or -1)
- spotlight_click (0 or 1)
- recent_item_click (0 or 1)
- total_bookmarks (total number of bookmarks for this user)
- total_history_size (number of entries in user's history)
- session_duration (int in milliseconds)

**Comment by tspurway** [comment]
- crash data over a shortish time period might be useful
- let's make sure metrics team has access to the redshift instance

**Comment by ncloudioj** [comment]
Based on the feedback of @oyiptong

- client_id (unique id for user)
- tab_id (unique id for that user's newtab)
- addon_version (e.g. "1.0")
- load_reason (newtab, focus, restore)
- source (recent_links, recent_bookmarks, frecent_links, top_sites, spotlight)
- search (indicates a search was performed)
- max_scroll_depth (int)
- click_position (index of object clicked on a click event or -1? or 2D coordinates e.g. 200x400?)
- total_bookmarks (total number of bookmarks for this user)
- total_history_size (number of entries in user's history)
- session_duration (int in milliseconds)
- unload_reason (click, search, close, unfocus? navigation? refresh? crash?)

FYI, @tspurway @emtwo

**Comment by emtwo** [comment]
Do we think we'll want to do any analytics on the time of day of activations? I was keeping track of a start timestamp, wondering if it's worth keeping?

**Comment by oyiptong** [comment]
The assumption is that the server-side will take note of the receipt time of a ping.
The receipt time is then taken as as the datetime of note.

The client doesn't need to keep track of the start time.

**Comment by ncloudioj** [comment]
@emtwo FYI, the Onyx endpoint for AS is live in stage:

"https://onyx_tiles.stage.mozaws.net/v3/links/activity-stream"

In production, it will be "https://tiles.services.mozilla.com/v3/links/activity-stream"  

The add-on can send pings to Onyx via HTTP POST, it returns status code 200 upon success with an empty response, otherwise, it returns 400 if any error occurs.

**Comment by emtwo** [comment]
@oyiptong is the server aware of the timezone of the client? If not, then the server doesn't actually know what time of day a given user is browsing right?

**Comment by oyiptong** [comment]
I see what you mean. The local datetime. And yes, we obtain the country data on the server-side.
To obtain timezone awareness, we should store the state level information as well.

**Comment by ncloudioj** [comment]
Usually it doesn't make sense to save time stamp from the clients, as we can't control how they set their local time. I will try to get the timezone from the geo, which in turn generated by IP address.

**Comment by tspurway** [comment]
The MaxMind GeoIP database we use has Timezone as a field (https://www.maxmind.com/en/geoip2-city#features)

**Comment by oyiptong** [comment]
AFAIK, our servers are provisioned with the country db. We'll need to ensure they are provisioned with the city DB

**Comment by tspurway** [comment]
That's a good point - I will doublecheck with travis we have the proper license somewhere

**Comment by ncloudioj** [comment]
Looking to add a filter for `session_duration`, if it goes beyond a certain threshold, say, 20 minutes, we treat it as an outlier and discard this ping.

What do you think? @tspurway @oyiptong

**Comment by oyiptong** [comment]
We can capture the ping and just not count it when we do our aggregate queries. The information could still be useful.

**Comment by ncloudioj** [comment]
Moving the duration filtering to the query level, that also sounds viable. Plus keeping the long-lived session pings could facilitate the further investigation. OK, will take out this filter in Infernyx. Thanks!

**Comment by ncloudioj** [comment]
Just confirm that the timezone is not available in the `country` database in GeoIP2. It only comes with the `city` one.

**Comment by tspurway** [comment]
I just noticed there was a question about the `click_position` above that was never answered @ncloudioj @emtwo .  It should definitely be an index, and *not* an x-y coordinate.  We also need to know what was clicked, whether it was `click_top_site`, `click_spotlight` or `click_top_activity`.  Maybe these alternatives should be in the `unload_reason` field instead of the generic `click`?

**Comment by ncloudioj** [comment]
Yes, I've asked @oyiptong about this in the last meeting. Sounds like those are not that urgent comparing to the other metrics. But we can definitely include them in the ping now.

@oyiptong can you confirm this please?

**Comment by mzhilyaev** [comment]
Yes,  we can attach performance events or any metric computable from them to the ping

**Comment by ncloudioj** [comment]
@emtwo @tspurway FYI, based on the discussion we had today,

- client_id (int: unique id for user)
- tab_id (str: unique id for that user's newtab)
- addon_version (str: e.g. "1.0")
- load_reason (str: newtab, focus, restore, other)
- source (str: recent_links, recent_bookmarks, frecent_links, top_sites, spotlight, other)
- max_scroll_depth (int: use -1 for "N/A")
- click_position (int: index of object clicked on a click event, use -1 for non-click ping)
- total_bookmarks (int: total number of bookmarks for this user, use -1 for "N/A")
- total_history_size (int: number of entries in user's history, use -1 for "N/A")
- session_duration (int: in milliseconds) 
- unload_reason (str: click, search, close, unfocus, navigation, refresh, crash, other)

Note:
 - We decide not to include the telemetry in #19 for now

Question:
 - Regarding `click_position`, do we want to use the global index for each item on the page, or the local index for each section?  @k88hudson Thoughts? I like the global one, easier to query in the database :)

**Comment by ncloudioj** [comment]
Performance metrics to be included in the ping:

- load_latency (int: in millisecond)

@oyiptong @mzhilyaev could you add other interested metrics to the list above please?

**Comment by mzhilyaev** [comment]
load time metric is Milliseconds , client default is null.

**Comment by ncloudioj** [comment]
Update: Add-on telemetry has been enabled since 1.0.4, data processing and persistence look good so far. Will keep watching it as more metrics will be brought to the pipeline.
