### ISSUE TITLE
Do not use maxcdn

### ISSUE THREAD

**Issue by oyiptong** [mozilla/activity-streams#270]
We are loading https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css

This is a security hole. This page is priviledged. We should use a version hosted in our addon.

Edit: since we don't serve remotely, it should be that we serve this from our _addon_ (instead of domain as I previously wrote).

**Comment by pdehaan** [comment]
Ref: #83

**Comment by pdehaan** [comment]
I found the following FontAwesome [references in the code](https://github.com/mozilla/activity-streams/search?utf8=%E2%9C%93&q=fa):

| ICON | FILE |
|----|----|
| `fa-search` | [/content-src/components/Search/Search.js:17](https://github.com/mozilla/activity-streams/blob/a7f93917b357379b5c3c4f195439f978159e26e5/content-src/components/Search/Search.js#L17)
| `fa-arrow-right` | [/content-src/components/Search/Search.js:20](https://github.com/mozilla/activity-streams/blob/a7f93917b357379b5c3c4f195439f978159e26e5/content-src/components/Search/Search.js#L20)
| `fa-firefox` | [/content-src/components/TimelinePage/TimelinePage.js:11](https://github.com/mozilla/activity-streams/blob/728749aec929a441ac455672f0f2e8face945fcf/content-src/components/TimelinePage/TimelinePage.js#L11)
| `fa-star` | [/content-src/components/TimelinePage/TimelinePage.js:12](https://github.com/mozilla/activity-streams/blob/728749aec929a441ac455672f0f2e8face945fcf/content-src/components/TimelinePage/TimelinePage.js#L12)
| `fa-timeline` | [/content-src/components/TimelinePage/TimelinePage.js:17](https://github.com/mozilla/activity-streams/blob/728749aec929a441ac455672f0f2e8face945fcf/content-src/components/TimelinePage/TimelinePage.js#L17)
| `fa-chevron-down` | [/content-src/components/Header/Header.js:19](https://github.com/mozilla/activity-streams/blob/728749aec929a441ac455672f0f2e8face945fcf/content-src/components/Header/Header.js#L19)

**Comment by jdorfman** [comment]
@oyiptong Justin from MaxCDN here, I can understand your concern and but can assure you we take security seriously.  If you would like a free MaxCDN account that you and only you (+ sub accounts) can control please let me know and we would be more than happy to accommodate.  If not, no hard feelings.

Thanks and good luck with your project. =)

**Comment by oyiptong** [comment]
Thanks for chiming in @jdorfman. I think a CDN in general is not a bad idea. We could probably make use of SRI to ensure the integrity of the file.

However, there are other factors in this specific project: it is actually not served remotely, it's an addon. It's much better in our case to have all our assets served locally.

Thanks!

**Comment by k88hudson** [comment]
This will be closed by https://github.com/mozilla/activity-streams/issues/83

**Comment by jdorfman** [comment]
@oyiptong for sure, add-ons should never "call home".

Side note: I am glad you brought up SRI.  I have been working with two of your co workers (Frederik & Jonathan) bringing it to BootstrapCDN and [jQuery's CDN](https://github.com/jquery/codeorigin.jquery.com/issues/20) and love hearing others talking about the spec. =)

@k88hudson sounds good.  

Thanks everyone!

**Comment by oyiptong** [comment]
closing as a duplicate of #83
