### ISSUE TITLE
In Bookmarks screen, the time-stamp is updated for bookmarked websites when they are visited.

### ISSUE THREAD

**Issue by softvision-VladBacia** [mozilla/activity-streams#272]
### Prerequisites:
Have some bookmarked websites.

### Steps to reproduce:
1. Visit an old bookmarked website.
2. Click on Activity Stream button from the browser toolbar.
3. Click on "Bookmarks" button from the sidebar from Activity Stream.
4. Observe the bookmarked website that was visited.

### Actual results:
For the website that was visited, in Bookmarks screen, the time-stamp has been updated.

### Expected results:
In Bookmarks screen, the time-stamp should reflect the time at which the website was bookmarked, not visited.
**Note:** If the time-stamp update is the expected behavior then the position of the website in the list should also be updated.
![timeline](https://cloud.githubusercontent.com/assets/9248513/13572065/f20ac6e0-e480-11e5-8ff2-ec20c7a01b05.jpg)
**Figure 1:** The time-stamp and the position in "Just now" section from Timeline has been updated for the visited website.
<hr></hr>
![bookmarks](https://cloud.githubusercontent.com/assets/9248513/13572391/c012c5fa-e482-11e5-8406-a2a4caeb5d6f.jpg)
**Figure 2:** In Bookmarks screen, the time-stamp is updated for bookmarked websites when they are visited.

**Comment by stuartphilp** [comment]
+1. The mixing of dates is very confusing

<img width="277" alt="screen shot 2016-03-23 at 3 25 06 pm" src="https://cloud.githubusercontent.com/assets/2964961/13998114/c74af708-f10b-11e5-9185-615e8e524981.png">
