### ISSUE TITLE
Diminish non-network, first render latency

### ISSUE THREAD

**Issue by oyiptong** [mozilla/activity-streams#274]
On my computer, it takes > 1 second for the front-end to start making calls to embedly.
The page then finishes loading around the 1.5 sec mark, this is after a few parallel network calls to load images.

This is much too slow. And this is with caching. If I blow the cache, it takes 2 secs to render (including network calls).

We need to find out what the bottleneck is and bring this down to an acceptable level of performance.

To be clear, this is about diminishing latency before factoring network latency, which we'll account for in another bug.

**Comment by oyiptong** [comment]
Cached pageload:
<img width="2032" alt="screen shot 2016-03-06 at 10 45 06 pm" src="https://cloud.githubusercontent.com/assets/9365/13573785/48685818-e44f-11e5-8b39-1ef1651f9ada.png">

**Comment by k88hudson** [comment]
I ran some perf tests on the rendering and I didn't see anything really off -- I wonder if this has to do with query performance on a lot of history data? Are you testing this on a browser with a lot of history?

**Comment by oyiptong** [comment]
It is very possible that this is blocking on the queries. I have 100k history items.

**Comment by oyiptong** [comment]
Here are the milestones we need to keep track of:

1. User initiates a page load
2. DOMContentLoaded
3. React loaded
4. queries requested to Chrome
5. all query responses received
6. page rendered
7. all images loaded

The time taken for each milestone would be a good first step.

**Comment by pdehaan** [comment]
I think this is related to the work in #200.
I'd vote to say on initial page load we load our default set of @nchapman approved "Top Sites" (ideally without any pings to the Embedly proxy or any other service to get favicon info site/provider name), and then populate the "Spotlight" results using @bryanbell's https://github.com/mozilla/activity-streams/issues/200#issuecomment-192037469 suggestions (again without any network traffic, if possible).
Then we can still fire off our async requests to our APIs to fill in the real data as it comes in.
That way we'd get a fast first render for all users. New users just wouldnt see any changes because they have no browsing data to load async. And Existing users will see data immediately, and then their actual data load in 1-8s (which unfortunately will cause some tile reflows, but that's unavoidable).

**Comment by oyiptong** [comment]
After we take note of the time the addon spends between each milestone, we'll have a better idea of where to dig.

I already have some potential low hanging fruits in mind for the queries:

* remove favicon joins if we aren't using them (we're now using embedly exclusively, right?)
* perhaps do EXPLAIN on the queries to see if we're doing sequential scans where we shouldn't

**Comment by mzhilyaev** [comment]
actually, as i am looking at telemetry dumps, the query performance improves dramatically between the first page load and the consequent ones.  I think priming the pump by running queries before any page loaded will help a lot

**Comment by oyiptong** [comment]
I ran some preliminary tests using @mzhilyaev work on performance profiling, using my profile with 100k+ history items or an empty profile and on a Macbook Pro with an SSD, here are the numbers.

In order to isolate the non-network calls and to focus on the "average case", I have taken a few measures:

* These numbers are not the first-load numbers. The initial page loads probably has react creating the document elements. It takes ~850ms on my computer for the first load to complete. Subsequent loads may have the old document's DOM from a previous load and react just does the virtual DOM diff
* I also disabled the embedly network call for these measurements. Embedly network calls take ~100ms for me on a new profile and block page rendering
* There is actually still one network call: font-awesome
* I removed favicon DB joins for the benchmarks because they seem to add 100ms for the 100k history item scenario and not much for the new profile scenario. They made apples-to-apples comparisons harder

## First load

For the sake of comparison, here's a first load report, on a new profile:

> 0 TAB_OPEN
> 271 TAB_READY
> 273 TOP_FRECENT_SITES_REQUEST
> 276 RECENT_LINKS_REQUEST
> 278 FRECENT_LINKS_REQUEST
> 279 RECENT_BOOKMARKS_REQUEST
> 281 SEARCH_STATE_REQUEST
> 284 NOTIFY_TELEMETRY:BASE_MOUNTED
> 292 TOP_FRECENT_SITES_RESPONSE 19
> 294 RECENT_LINKS_RESPONSE 18
> 297 RECENT_BOOKMARKS_RESPONSE 18
> 302 SEARCH_STATE_RESPONSE 21
> 843 NOTIFY_TELEMETRY:NEWTAB_RENDER

Here's one with 100k history items:

> 0 TAB_OPEN
> 252 TAB_READY
> 254 TOP_FRECENT_SITES_REQUEST
> 256 RECENT_LINKS_REQUEST
> 259 FRECENT_LINKS_REQUEST
> 260 RECENT_BOOKMARKS_REQUEST
> 263 SEARCH_STATE_REQUEST
> 266 NOTIFY_TELEMETRY:BASE_MOUNTED
> 283 SEARCH_STATE_RESPONSE 20
> 574 TOP_FRECENT_SITES_RESPONSE 320
> 674 RECENT_LINKS_RESPONSE 418
> 677 RECENT_BOOKMARKS_RESPONSE 417
> 717 NOTIFY_TELEMETRY:NEWTAB_RENDER

It seems the DOM (and/or virtual DOM) is being constructed async from the DB queries.

## New Profile (only default links)

> 0 TAB_OPEN
> 124 TAB_READY
> 128 TOP_FRECENT_SITES_REQUEST
> 131 RECENT_LINKS_REQUEST
> 133 FRECENT_LINKS_REQUEST
> 134 RECENT_BOOKMARKS_REQUEST
> 137 SEARCH_STATE_REQUEST
> 144 NOTIFY_TELEMETRY:BASE_MOUNTED
> 148 TOP_FRECENT_SITES_RESPONSE 20
> 150 RECENT_LINKS_RESPONSE 19
> 152 RECENT_BOOKMARKS_RESPONSE 18
> 175 SEARCH_STATE_RESPONSE 38
> 181 NOTIFY_TELEMETRY:NEWTAB_RENDER

Here's the breakdown:

### 124 TAB_READY / DOMContentLoaded

124 ms elapses from the moment the user initiates a newtab open and the page to send the DOMContentLoaded event.
In between 0 and 124, the document is created and the initial DOM is created. The page load is blocked on the style headers and other things. We might want some more measurements on the various stages of document loading at that point. Not using font awesome is going to give us a moderate gain (it is a network call after all).

### 144 NOTIFY_TELEMETRY:BASE_MOUNTED

20 ms elapses from the moment DOMContentLoaded executes and the react component Base.js starts mounting.

The document fires a few requests in parallel to chrome.

### 175 SEARCH_STATE_RESPONSE

29 ms elapses since the base mounted (and 38 ms since the request fired). At this point, the content should have all the data it needs to render. In the case of an empty history, the DB calls add minimal latency.

### 181 NOTIFY_TELEMETRY:NEWTAB_RENDER

If embedly were enabled, after 100ms, the newtab page renders. This includes a blocking network call to embedly. The 100ms are taken up almost entirely by the network call, and the rendering blocks due to that call.

If we remove embedly from the equation, it takes ~5-6ms for the page to render after it receives the DB query results for a new profile.

## 100k history items

> 0 TAB_OPEN
> 131 TAB_READY
> 142 TOP_FRECENT_SITES_REQUEST
> 145 RECENT_LINKS_REQUEST
> 147 FRECENT_LINKS_REQUEST
> 148 RECENT_BOOKMARKS_REQUEST
> 151 SEARCH_STATE_REQUEST
> 153 NOTIFY_TELEMETRY:BASE_MOUNTED
> 170 SEARCH_STATE_RESPONSE 19
> 453 TOP_FRECENT_SITES_RESPONSE 311
> 548 RECENT_LINKS_RESPONSE 403
> 550 RECENT_BOOKMARKS_RESPONSE 402
> 597 NOTIFY_TELEMETRY:NEWTAB_RENDER

### 131 TAB_READY / DOMContentLoaded

Nothing interesting/different from the new profile scenario

### 153 NOTIFY_TELEMETRY:BASE_MOUNTED

Nothing interesting/different from the new profile scenario

### 550 RECENT_BOOKMARKS_RESPONSE

397ms after mounting Base.js completes, the last DB query responds. This dominates the latency to render.

### 597 NOTIFY_TELEMETRY:NEWTAB_RENDER

With a loaded history, this takes a bit longer: 50ms. React populates the components with new data.

## Analysis and Action Items

### TAB_READY / DOMContentLoaded

There seems to be a high variance in the latency to DOMContentLoaded. This will be mitigated when font-awesome is removed, and this will remove some latency. On my computer, it removes ~30ms latency.

This is a low hanging fruit, low gain, small effort work.

### RECENT_BOOKMARKS_RESPONSE / DB QUERIES

We should make sure that there are no DB queries on pageload. The page should load from cached DB results. This will ensure a very short latency.

We should store all results of DB queries in memory, and invalidate on history items. This will net us gains of ~50ms to ~600ms, and this is on a fast SSD. On spinning disk or slower SSD (e.g. on a Macbook Air) this will be far longer.

Removing favicons data from the queries shaves another 100ms. They are not being used at the moment, so, could be removed. That said, with caching, removing favicons could be moot anyway as they could still be used in favor of embedly queries, avoiding us a network call on image render.

This is high gain, medium effort work.

### NOTIFY_TELEMETRY:NEWTAB_RENDER

We can diminish first load latency by 300-400ms if we preload the newtab page on browser startup. This will diminish React's load latency.

This is high gain, low-medium effort work.

**Comment by oyiptong** [comment]
Tip of the hat to @mzhilyaev for the quick work on #278

**Comment by pdehaan** [comment]
> Removing favicons data from the queries shaves another 100ms. They are not being used at the moment, so, could be removed.

I think using the favicon from the queries would make the pages render much faster since we wouldn't be making potentially 25 external favicon requests to the network. That said, so far the favicons from the database seem to be 16px square and look pretty blurry.

---

Here's a funny screenshot where it took ~2s to resolve DNS for one of the favicons.
<img width="1343" alt="new_tab_and_diminish_non-network__first_render_latency_ _issue__274_ _mozilla_activity-streams" src="https://cloud.githubusercontent.com/assets/557895/13644617/90f3de76-e5db-11e5-9ddb-c76ba48ee702.png">

**Comment by ckarlof** [comment]
> We need to find out what the bottleneck is and bring this down to an acceptable level of performance.

Nice work! What's the target for acceptable? 

Also, it would be great to automatically test perf KPIs on each PR to prevent perf regressions. Sudden regressions are usually obvious, but gradual perf regressions are less so.

**Comment by oyiptong** [comment]
> Nice work! What's the target for acceptable? 

I would say ~250ms, but it's hard to have a real number as it depends on the machine as well. We'll need a "benchmark machine". We could perhaps investigate what the current performance is for the page we're replacing, newtab, and find what the delta is.

> Also, it would be great to automatically test perf KPIs on each PR to prevent perf regressions. Sudden regressions are usually obvious, but gradual perf regressions are less so.

I agree. I think we will be able to take advantage of talos when we land something in gecko. We'd get good performance regression testing.

**Comment by oyiptong** [comment]
This issue will be considered closed after issue #320 is resolved

**Comment by oyiptong** [comment]
Actually. I'll close this and let #320 stand by itself.
