### ISSUE TITLE
Engagement data collection

### ISSUE THREAD

**Issue by oyiptong** [mozilla/activity-streams#28]
Implement code in add-on to send messages to data-pipeline.

Maybe start with a few messages add-on side, we can do content in a follow-up ticket

**Comment by oyiptong** [comment]
* Number of newtab opens per user

**Comment by oyiptong** [comment]
* scroll depth

**Comment by k88hudson** [comment]
@oyiptong @emtwo to clarify

**Comment by oyiptong** [comment]
following a meeting with @nchapman, @tspurway jotted down some notes in #27.

The pings should be as follows:

When a user opens a newtab page, we make note of the time (start a counter).

We then capture an exit condition:

1. a user clicks on a link
2. a user enters something in the url bar and hits enter
3. a user closes the tab

In case #1, when that happens, we want to record:

1. the maximum scroll depth reached
2. the y-position of the link in px
3. the type of link they clicked (top sites, bookmark, etc)
4. the time they spent on the page

in case #2 we only want to record an impression, but that they used the URL bar

in case #3 we only want to record an impression, but that they closed it

There may be more things to record, or more use cases, but this should give a good idea
