### ISSUE TITLE
opening new tab clears url bar after i've type a couple characters

### ISSUE THREAD

**Issue by edmoz** [mozilla/activity-streams#285]
1. open new tab
2. type one or two keystrokes

actual: you see the first key, then when new tab is loading, the url bar is cleared out.  This seems to be a performance issue of typing just before the new tab loads which clears out the URL bar.

expected: any characters entered should not be deleted.

**Comment by edmoz** [comment]
this hurt me deeply and I think we need this fixed by public release

**Comment by rlr** [comment]
grabbing to work on today

**Comment by rlr** [comment]
landed fix.

**Comment by edmoz** [comment]
:heart:
