### ISSUE TITLE
icon displays wrong character on some articles

### ISSUE THREAD

**Issue by edmoz** [mozilla/activity-streams#286]
1. goto: https://news.ycombinator.com/item?id=11230084
2. open new tab and look at icon in history

actual:
<img width="747" alt="screen shot 2016-03-07 at 11 54 23 am" src="https://cloud.githubusercontent.com/assets/3698618/13654835/9a104646-e60f-11e5-943f-388e752bcd4c.png">

expected: should be the letter 'N' or 'Y' for subdomain or domain.

**Comment by pdehaan** [comment]
Ah yes, it's defaulting to the first char in the title. Looks like a byproduct of #284.

Using @k88hudson's awesome new debugger branch from #283, it looks like we're just not getting the embedly metadata injected into the response, which will make the [`<SiteIconFallback/>`](https://github.com/mozilla/activity-streams/blob/5f6bfdeabe607e8b538ef3d5268691e1ed826692/content-src/components/SiteIcon/SiteIcon.js#L58) fail.

```js
const SiteIconFallback = React.createClass({
  render() {
    const {favicon_colors, title, provider_name, provider_display} = this.props;
    const letter = (provider_name || provider_display || title || "")[0];
```
&mdash; via [/content-src/components/SiteIcon/SiteIcon.js:58](https://github.com/mozilla/activity-streams/blob/5f6bfdeabe607e8b538ef3d5268691e1ed826692/content-src/components/SiteIcon/SiteIcon.js#L55-L65)

---

```json
{
  "raw": {
    "TopSites": {
      "rows": [
        {
          "url": "https://news.ycombinator.com/item?id=11230084",
          "title": "“I've been working at Mozilla for many years, from peak to decline” | Hacker News",
          "lastVisitDate": 1457568060212,
          "frecency": 2000,
          "favicon": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABj0lEQVQ4jZWTP0gCURzHXf0DDaKoyZ06CTVHc3NLU1CrFpipd+dgTeXUFCFETbXU0pJr0SQotLS5VN69d2hpIaaWJIbfhtPr0tNsePDe7/H7/L6/fwbKMV3KsaAc06U8i4mOxseg/SAc07t71LeeTetjGFRAYm6QTYc2muIYcYDE3H8oiLkhJ/woJucVUN8enUZxdw5ywv8DURVoAVEX5K0ZdJqvKB+vQgxZIYXteNpfRKdWgrw9CxJ1jQBwDKjgQyFgQu3qAJ/FPMSQFeL6FFoPWbxdp1AImEAFn5rWsIJ+DXgWX80qnlNLKO0toFOvgAieX2npA3oqxDULqpc7aN1n8ZG/QTWdhBi0gAo+nS4MEAmngKSIE+3KI9ovIqSIc6ClYwEMaNyHQsCIRu4M9cwpCgEjaHw4ui6A8iyI4IUYNKORO0c9cwIxaAYRvLpTqQvoK3i/S6N5e6EqmBzAeyCF7SgfraB8uAwpbFdHeRigt0wco0A2bJDCNsVZm/+oUR5uqRdU8OoWb7yCf6zzN96LhjqimbbsAAAAAElFTkSuQmCC",
          "type": "history",
          "parsedUrl": {
            "hash": "",
            "query": {},
            "protocol": "https:",
            "pathname": "/item",
            "auth": "",
            "host": "news.ycombinator.com",
            "port": "",
            "hostname": "news.ycombinator.com",
            "password": "",
            "username": "",
            "href": "https://news.ycombinator.com/item"
          }
        }
      ],
      "error": false
    },
```

**Comment by pdehaan** [comment]
Yeah, looks like using `parsedUrl.hostname` as a last-ditch effort at least gives us "N" instead of double quotes.

```js
const SiteIconFallback = React.createClass({
  render() {
    const {favicon_colors, title, provider_name, provider_display, parsedUrl} = this.props;
    const letter = (provider_name || provider_display || parsedUrl.hostname || title || "")[0];
```

![new_tab](https://cloud.githubusercontent.com/assets/557895/13655191/7147d08c-e612-11e5-9ef3-bd6f7fa73546.png)

**Comment by chuckharmston** [comment]
For what it's worth, we're using some `Services` from the browser to do something similar on Universal Search:

    const {utils: Cu} = Components;

    Cu.import('resource://gre/modules/XPCOMUtils.jsm');
    XPCOMUtils.defineLazyModuleGetter(this, 'Services',
      'resource://gre/modules/Services.jsm');

    function firstLetterOfBaseDomain(url) {
      const uri_obj = Services.io.newURI(url, null, null);
      return Services.eTLD.getBaseDomain(uri_obj)[0];
    }

**Comment by k88hudson** [comment]
This will be fixed by https://github.com/mozilla/activity-streams/pull/293
