### ISSUE TITLE
Set search field placeholder on NewTab page?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#287]
I was testing an unrelated PR and noticed that if I enable logging, i see a bunch of "next state" logs which had a `Search` object.
Turns out that if I inspect the `Search` object, there is a `currentEngine.placeholder` string, which defaults to "Search with Yahoo" (but obviously changes if you change your default search provider).

This is pretty awesome, and it'd be pretty cool to use that placeholder on the NewTab page, as it'd let me know if I'm performing a web search, or searching my TopSites, or whatever.

![new_tab](https://cloud.githubusercontent.com/assets/557895/13679478/c73f799a-e6a8-11e5-9b1e-03970779103c.png)

I tried for ~15m to find out how to access that "next state `Search.currentEngine.placeholder`" object, but failed (which is why this is an issue instead of PR).

**Comment by k88hudson** [comment]
Hm, the current behaviour for Firefox on new tab is only show `Search`, not `Search with...`, so I think maybe we should leave it the way it is. @pdehaan  @bryanbell what do you think?

**Comment by nchapman** [comment]
Discussed this. Decided we want to A/B test changes to the label (icons, text, etc).

**Comment by pdehaan** [comment]
One suggestion was to change the prompt to generically say "Search the Web" to make it clear that it wasn't searching your activity stream or bookmarks, but not being as specific as to call out your search provider.

**Comment by pdehaan** [comment]
Fixed via #591
