### ISSUE TITLE
about:newtab doesnt display new tab page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#294]
### Steps to reproduce:
1. Open a new tab (you see the new UI)
2. Go to https://reddit.com/
3. Go to "about:newtab"

### Actual results:
(3) above should work, but shows a blank page.
I don't see any errors in my DevTools console, and I see a single network request for font-awesome.min.css, which looks like our page. The rest of the DOM looks like ours too, so I'm not sure why the page doesn't fully load.

### Expected results:
Explicitly going to <about:newpage> should show the new UI.

**Comment by oyiptong** [comment]
about:newtab will not take you to the activity streams UI ever, unless we're in gecko

**Comment by oyiptong** [comment]
well... "ever" is the wrong word. it could've taken you there depending on the firefox version, but my above comment was a simple contraction of how it's designed to be

**Comment by pdehaan** [comment]
@oyiptong I'm not sure I follow the exact rules, but does this mean we need to modify the reference to `about:newtab` in [./data_dictionary.md](https://github.com/mozilla/activity-streams/blob/master/data_dictionary.md):

> The `about:newtab` page will ping (HTTPS POST) Onyx every time the page loses focus.

**Comment by oyiptong** [comment]
Yes. that line is incorrect.

**Comment by pdehaan** [comment]
@oyiptong Can I just change it to something more generic like:

> "The Activity Stream page will ping (HTTP POST) Onyx every time the page loses focus."

or

> "The new tab page will ping..."

I can quickly PR it if somebody can approve some words.

**Comment by oyiptong** [comment]
The first line is more accurate

**Comment by pdehaan** [comment]
Thanks, PR incoming. Looks like I overlooked the `unload_reason` reference too, so I'll tweak that up while I'm at it.

`unload_reason` &mdash; The reason the about:newtab page lost focus.
