### ISSUE TITLE
Syncing a new device drops old bookmarks right in my stream even though they're old

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#297]
via @edmoz

### Steps to reproduce:
1. Browse a few pages and add a few history items to your activity stream.
2. Go to about:preferences > Sync and select Sign In, and sign in with an existing sync account with browsing data.

### Actual results:
Syncing a new device drops old bookmarks right in my stream even though they're old.

### Expected results:
Bookmarks and browsing data should be sorted based on when the bookmark was originally added, not when the account was synced.

**Comment by edmoz** [comment]
I suspect this may have gotten fixed, I don't see the bug anymore, sorry pdehaan for the noise

**Comment by edmoz** [comment]
This is fixed
