### ISSUE TITLE
Old Bookmarks don't make for fresh content.

### ISSUE THREAD

**Issue by bryanbell** [mozilla/activity-streams#302]
![oldbookmarks](https://cloud.githubusercontent.com/assets/228979/13783992/cddd77bc-ea8a-11e5-8a9e-df21b6ea9629.png)

My recent activity has been supplanted by revisits to places I've had bookmarks for since the Bush administration.

We should explore a rule that downcast bookmarked things that have very old bookmarks. The rationale is that apparently people know how to get there already if they repeatedly go there all the time. BTW this is what "Top Sites" is for. Top Sites shouldn't be mixed in with my recent activity.

**Comment by nchapman** [comment]
Yeah I've noticed the same. I feel like this query isn't currently giving us the results we hoped it would. Let's take another crack at it. @k88hudson can you link us to the current rules for this query?

**Comment by k88hudson** [comment]
Agreed, I think it needs some tweaking.

The query is here: https://github.com/mozilla/activity-streams/blob/master/lib/PlacesProvider.js#L230

The query is limited to history entries with a `last_visit_date` after 72 hours ago, and selected sorted in the following order:

```
bookmarkDateCreated DESC, frecency DESC, lastVisitDate DESC, url
````

**Comment by k88hudson** [comment]
Maybe we could limit `bookmarkDateCreated` as well?
