### ISSUE TITLE
Spotlight-item changes source after it was visited

### ISSUE THREAD

**Issue by softvision-VladBacia** [mozilla/activity-streams#303]
### Prerequisites:
https://vimeo.com/158818287 is in a Spotlight tile.

### Steps to reproduce:
1. Open Activity Stream Timeline page.
2. Click on the Spotlight tile with the video from prerequisites.
3. Click on "Back" button to return to Timeline.
4. Refresh Activity Stream Timeline.
5. Observe the Spotlight tile with the video.

### Actual results:
The Vimeo video link is replaced in the Spotlight tile with vimeo.com link and data.

### Expected results:
Spotlight tile contains the link and description for the Vimeo video.
The data from the Spotlight tile should not be altered. Only spotlight-context should be updated.

Video of the issue:
[Spotlight tile changes source.zip](https://github.com/mozilla/activity-streams/files/174284/Spotlight.tile.changes.source.zip)

**Comment by rlr** [comment]
Yeah, I noticed this same issue. This happens because the vimeo video will now move to top sites. I think we probably need to tweak the way that works. I personally expect top sites to only point to the root path of the domain (for example, vimeo.com in this case) and not to specific pages of the site.

**Comment by softvision-VladBacia** [comment]
I've noticed that this issue is reproducible also when the root path of the domain (vimeo.com in this case) is displayed in Top Sites area from New Tab.

**Comment by rlr** [comment]
Actually, ignore what I wrote. There are no Top Sites on the Timeline page. I'll try to repro your steps.

**Comment by rlr** [comment]
Starting with a fresh profile, I visit https://vimeo.com and https://vimeo.com/158818287 and follow your STR but am unable to reproduce. Weird.

**Comment by softvision-VladBacia** [comment]
This issue was reproducible with a new profile that had no data on Windows 8.1 x64 PRO with latest Nightly (48.0a1).

User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:48.0) Gecko/20100101 Firefox/48.0
Build ID: 20160315030230

**Comment by nchapman** [comment]
Thanks for the detailed report. We're going to change the way Highlights (Spotlight) works (#389) which will invalidate this problem.
