### ISSUE TITLE
Need to count clicks on share button

### ISSUE THREAD

**Issue by edmoz** [mozilla/activity-streams#306]
Currently we pop an alert when a user tries to share an URL. It would be great to know how many users are clicking this and the other elements in the hover menu: Delete, Share, Ellipsis. 

In prototyping the data: If 40% of users click delete, 20% share how would this direct our UI?  I'm not sure what actions we would take based on this data.

@nchapman is this useful count for us?

**Comment by mzhilyaev** [comment]
will be resolved in #387
