### ISSUE TITLE
Add load latency to telemetry ping

### ISSUE THREAD

**Issue by mzhilyaev** [mozilla/activity-streams#308]
per bug #27

**Comment by mzhilyaev** [comment]
Few questions to @ncloudioj  

Q1.  May we report events for latency?

It may be beneficial to return a load latency object rather then an integer.
The page may not always be loaded before a user closes it or links away from it.
Hence, returning something like:
```
{
  "event":  "dom loaded",
  "latency":  300
}
```
is more informative. 

Need confirmation from @ncloudioj  that backend can consume that format.
If it can't, then I suggest returning a positive integer if the page was fully loaded, or, if the page is not fully load, we return a negative integer which represents time-stamp to the last performance event before the tab session ended.

Q2.   Multiple tab session may have same latency

A user may switch back and forth between tabs, thus generating multiple sessions for the same tabID.
But the load latency is likely to be the same for the same tabID.  When we populate redshift we may want to take a note of that.

**Comment by ncloudioj** [comment]
A1. The current backend only takes one field, i.e. "load_latency", but we can definitely add more specific latency reads later on if necessary. Also, if the addon can not gauge it for whatever reason, you can simply leave it out in the payload, infernyx will fill it with the default value, which is -1 in this case. 

A2. This is a good point. I think we can leverage "load_reason" and "unload_reason" to handle this.
