### ISSUE TITLE
Add total_bookmarks and total_history_size to telemetry ping

### ISSUE THREAD

**Issue by mzhilyaev** [mozilla/activity-streams#309]
will require two separate queries against places.

**Comment by mzhilyaev** [comment]
@oyiptong @ncloudioj 

 *  Does this information gets added to each new-tab session, or only when tab is closed, or only ones per browser open?
 *  How fresh should it be?  Do we need to recompute sizes on every new-tab, or when the browser starts?

**Comment by ncloudioj** [comment]
@mzhilyaev 

Assuming that it's reasonably cheap to calculate these two sizes:
* Yes, they will be attached in every single ping, and, 
* they should be calculated right before the addon sends out the ping
