### ISSUE TITLE
Occasional mis-aligned item if you have a non-standard sized favicon/site image

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#313]
Randomly spotted this today (via npm run once &mdash; I'm guessing this was changed in #293).
I noticed that the featured image for Reddit seems to be non-square, which means the favicon and title don't align with the other items.

![new_tab](https://cloud.githubusercontent.com/assets/557895/13830183/48baffd8-eb88-11e5-9486-5318054bbfbe.png)

Link in question is: https://www.reddit.com/r/LifeProTips/comments/4aoft8/lpt_if_you_ever_get_mail_from_nielsen_the_tv/

Generated content is:

```html
<div class="feed-icon-image" style="background-image:url(https://www.redditstatic.com/icon.png);" data-reactid="...">
  <div class="site-icon feed-icon" style="width:20px;height:20px;background-color:white;" data-reactid="...">
    <div class="site-icon-background" style="background-color:rgba(210, 227, 242, 0.5);" data-reactid="..."></div>
    <div class="inner-border" data-reactid="..."></div>
    <div class="site-icon-wrapper" data-reactid="...">
      <img class="site-icon-favicon" src="https://www.redditstatic.com/favicon.ico" data-reactid="..." height="16" width="16">
      <span class="site-icon-fallback" style="color:black;font-size:14.4px;font-weight:400;" data-reactid="..." hidden="">r</span>
    </div>
    <div class="site-icon-title" data-reactid="..." hidden="">reddit.com</div>
  </div>
</div>
```

Two relevant-ish images are:

| URL | IMAGE | SIZE |
|----|----|:----:|
| https://www.redditstatic.com/icon.png | ![](https://www.redditstatic.com/icon.png) | 256 x 256 pixels
| https://www.redditstatic.com/favicon.ico | ![](https://www.redditstatic.com/favicon.ico) | 32 x 32 pixels

Not sure why the images are reporting as square in Firefox and Chrome, but skewing when used as the .feed-icon-image background-image.

**Comment by k88hudson** [comment]
this is a actually a flexbox issue, container needs a `flex-shrink: 0`

**Comment by k88hudson** [comment]
maybe?

**Comment by pdehaan** [comment]
@k88hudson adding `flex-shrink: 0` to `.feed-icon-image {}` in DevTools works for me:

**Before:**
![activity_stream](https://cloud.githubusercontent.com/assets/557895/13894417/c39bd388-ed24-11e5-9df0-5cf31fc4cd7e.png)

---

**After:**
![activity_stream](https://cloud.githubusercontent.com/assets/557895/13894428/d3351368-ed24-11e5-9925-c37618c291a8.png)
