### ISSUE TITLE
Time to remove the subtitles inside Top Activity 

### ISSUE THREAD

**Issue by bryanbell** [mozilla/activity-streams#314]
The subtitles in Top Activity are only somewhat helpful, but usually visually dilute the section title since they're exactly the same size and weight. Top Activity is often closely followed by a day of the week header. Let's just drop that. 

<img width="888" alt="pasted_image_3_16_16__3_09_pm" src="https://cloud.githubusercontent.com/assets/228979/13830469/1357c96e-eb8a-11e5-8492-6c81b92dab14.png">

Let's instead try the horizontal rules in the mockup. 

<img width="788" alt="mockup" src="https://cloud.githubusercontent.com/assets/228979/13830513/5b341922-eb8a-11e5-9018-f60a08295f09.png">

**Comment by pdehaan** [comment]
Unrelated, but in @bryanbell's screenshot above, I see a broken favicon image in his Spotlight result for Slate magazine bookmark.
Not sure if we have any way of detecting that and failing a bit more gracefully than a broken image icon (such as a fallback image of a blank 1px image).

**Comment by k88hudson** [comment]
To clarify, spec here is:

* use plain lines to divide sections
* Leave "Top activity" label at the top
* change the date display to be default settings for `moment.calendar()` (http://momentjs.com/docs/#/displaying/calendar-time/), so it will include the day as well

**Comment by rlr** [comment]
landed :ship:
