### ISSUE TITLE
Icons Smoosh 

### ISSUE THREAD

**Issue by bryanbell** [mozilla/activity-streams#327]
<img width="251" alt="pasted_image_3_17_16__2_56_pm" src="https://cloud.githubusercontent.com/assets/228979/13862458/a8bb89a2-ec50-11e5-893e-b16ce5326922.png">

This icon is narrow for some reason.

**Comment by bryanbell** [comment]
`<div class="feed-description" data-reactid=".0.0.0.1.2.0.1:$2016-03-17T00=200=200-07=200.$2016-03-17T00=200=200-07=200.$0.1.0"><h4 class="feed-title" data-reactid=".0.0.0.1.2.0.1:$2016-03-17T00=200=200-07=200.$2016-03-17T00=200=200-07=200.$0.1.0.0">fxa/README.md at rfeeley/eye-password-emoji · mozilla/fxa</h4><a class="feed-link" href="https://github.com/mozilla/fxa/blob/rfeeley/eye-password-emoji/features/FxA-80-eye-password-experiment/README.md" data-reactid=".0.0.0.1.2.0.1:$2016-03-17T00=200=200-07=200.$2016-03-17T00=200=200-07=200.$0.1.0.1">github.com/mozilla/fxa/blob/rfeeley/eye-password-emoji/features/fxa-80-eye-password-experiment/readme.md</a></div>`

**Comment by pdehaan** [comment]
Ref: #313

**Comment by pdehaan** [comment]
Should be fixed in [pending] PR #336
