### ISSUE TITLE
Replace conventional-changelog with anything else

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#330]
We seem to be struggling to get it to cleanly create a changelog for each release. Either we're doing something wrong in our Git flow, or we should consider finding a different tool to generate CHANGELOGs.

**Comment by gasolin** [comment]
How about adopt [commitzen](https://www.npmjs.com/package/commitizen) (from Angular), or even release with [semantic-release](https://github.com/semantic-release/semantic-release) ?

**Comment by pdehaan** [comment]
Closing. I haven't heard Oilivier complain about changelog stuff lately.

**Comment by oyiptong** [comment]
Oh it's incredibly annoying :-) but we should find a way to get this to work with `npm version`
