### ISSUE TITLE
twitter.com has broken favicon [because tracking protection is enabled]

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#334]
(via @leibovic on IRC)

the problematic icon URL is https://abs.twimg.com/favicons/favicon.ico

![irccloud_and_1__pdehaan_pdehaan____dev_github_activity-streams__zsh_](https://cloud.githubusercontent.com/assets/557895/13893602/29cc2386-ed1d-11e5-997b-81330d616998.png)

**Comment by pdehaan** [comment]
FWIW, I'm UTR locally w/ adding https://twitter.com/ to my activity stream.

![new_tab](https://cloud.githubusercontent.com/assets/557895/13893828/ef3b0e10-ed1e-11e5-9b89-4d310881a4e6.png)

**Comment by pdehaan** [comment]
> 3:38 PM \<margaret\> oh!
> 3:38 PM \<margaret\> The resource at "https://abs.twimg.com/favicons/favicon.ico" was blocked because tracking protection is enabled.

**Comment by pdehaan** [comment]
@k88hudson suggests having a better fallback for broken images where we show the letter of the site.

**Comment by oyiptong** [comment]
should be fixed by tippy top sites

**Comment by pdehaan** [comment]
Closing in favor of #449.
This exact use case of twitter.com should be resolved by the **tippy-top-sites** module (see #444).
