### ISSUE TITLE
Some favicons have odd contrast with background color

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#335]
(via @leibovic on IRC)

> What are you using to compute the icon background colors? some of them seem wrong.
> 
> Not sure if you could reuse it, but there is a module in the tree for getting colors from icons http://mxr.mozilla.org/mozilla-central/source/toolkit/components/places/ColorAnalyzer.js

![irccloud_and_1__pdehaan_pdehaan____dev_github_activity-streams__zsh_](https://cloud.githubusercontent.com/assets/557895/13893626/67a3e4fa-ed1d-11e5-912a-0473dff83f77.png)

**Comment by k88hudson** [comment]
This should be resolved by #337
