### ISSUE TITLE
Incorrect background colors in Top Activity

### ISSUE THREAD

**Issue by nchapman** [mozilla/activity-streams#337]
Background colors in Top Activity don't seem to be using dominant colors and instead seem to be mostly random and aren't consistent internally or with Top Sites.

![screen shot 2016-03-21 at 10 26 51 am](https://cloud.githubusercontent.com/assets/3095/13928722/1572ce88-ef54-11e5-92c9-4dba2239ba89.png)

**Comment by nchapman** [comment]
Probably related to #335.

**Comment by k88hudson** [comment]
We implemented a "random colour picker" for favicons that don't have colour information, but we probably only want to use that for items for which there is no image either

**Comment by pdehaan** [comment]
Ref: #293

**Comment by nchapman** [comment]
Now it appears to be behaving as expected... Notice Twitter and Github:

![screen shot 2016-03-21 at 12 51 12 pm](https://cloud.githubusercontent.com/assets/3095/13932061/a619c6f8-ef63-11e5-8920-bdf889be0972.png)
