### ISSUE TITLE
Date headers are slightly inconsistent

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#343]
Ref: #323

It looks like a small edge case where we're formatting dates slightly inconsistently based on whether it's the first item in a group. Since that was a garbage explanation, here's a free screenshot:

![activity_stream](https://cloud.githubusercontent.com/assets/557895/13934505/c9e6cd2c-ef6f-11e5-94c7-0480b61f2bea.png)
**Figure 1:** "2:11PM" versus "2:01 pm"

**Comment by k88hudson** [comment]
ah, good catch!

**Comment by softvision-VladBacia** [comment]
During testing I've observed this little issue regarding the date and time. For websites that were visited a long time ago, only the date is displayed for the last visited website from that day.
![date without time](https://cloud.githubusercontent.com/assets/9248513/13982548/6b0ed314-f0f3-11e5-9256-083934a4d179.jpg)
