### ISSUE TITLE
Create "spotlight" component

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-streams#35]
![image](https://cloud.githubusercontent.com/assets/1455535/12763708/ec210636-c9c3-11e5-85e2-ad37d3817aa2.png)

Should include lead image, title, and description/short summary

**Comment by tspurway** [comment]
@nchapman to donate some rules for this

**Comment by nchapman** [comment]
Here are the rules that Bryan and I came up with:

1. Up to 1 synced tab that was active in the last hour
2. Up to 2 bookmarks with images from the past 24 hours
3. Fill the rest with recent history items that have images

If no data is available, hide the spotlight section for now.

**Comment by rlr** [comment]
Landed the react component 1d8ad808ca9a561f4bd44de4f6a202f26e04a56b

We'll need a new issue for the "backend logic" where we'll apply the rules.
