### ISSUE TITLE
Add Activity Stream Favicon

### ISSUE THREAD

**Issue by stuartphilp** [mozilla/activity-streams#354]
In either the tab for activity stream or if you pin the tab, there isn't a favicon. would be nice to have :)

<img width="295" alt="screen shot 2016-03-23 at 3 12 47 pm" src="https://cloud.githubusercontent.com/assets/2964961/13997722/cddf1a1a-f109-11e5-8257-66a289822059.png">

**Comment by pdehaan** [comment]
@bryanbell Re: favicon, do we just want to use the [list-icon.svg](https://github.com/mozilla/activity-streams/blob/master/content-src/static/img/list-icon.svg)? ![](https://rawgit.com/mozilla/activity-streams/master/content-src/static/img/list-icon.svg)
