### ISSUE TITLE
All the new columns to be added into telemetry for Beta 2

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-streams#358]
As a meta bug, this tracks all the new columns to be added into the telemetry for Beta 2.

The current telemetry payload:

- client_id (str: unique id for user)
- tab_id (str: id for that user's newtab)
- addon_version (str: e.g. "1.0.0")
- load_reason (str: newtab, focus, restore, other)
- source (str: recent_links, recent_bookmarks, frecent_links, top_sites, spotlight, other)
- max_scroll_depth (int: use -1 for "N/A")
- click_position (int: index of object clicked on a click event, use -1 for non-click ping)
- total_bookmarks (int: total number of bookmarks for this user, use -1 for "N/A")
- total_history_size (int: number of entries in user's history, use -1 for "N/A")
- session_duration (int: in milliseconds) 
- unload_reason (str: click, search, close, unfocus, navigation, refresh, crash, other)
- receive_at (timestamp: auto-generated on the server side)

**Comment by ncloudioj** [comment]
#355 - Add a `date` column to facilitate the query

Infernyx will automatically populate it by using the `receive_at`

**Comment by tspurway** [comment]
We recently updated the data dictionary (https://github.com/mozilla/activity-streams/blob/master/data_dictionary.md).  Let's use this ticket to track the changes:

- [ ] change splice to include new table `activity_stream_events_daily` in it's migrations
- [ ] add migration to remove unused columns from `activity_stream_stats_daily`
- [ ] modify Infernyx rule to handle handle both `activity_stream_session` and `activity_stream_event` keysets, and route the data to the appropriate table

**Comment by ncloudioj** [comment]
- [ ] change splice to include new table `activity_stream_events_daily` in it's migrations
- [ ] add migration to remove unused columns from `activity_stream_stats_daily`
- [ ] modify Infernyx rule to handle handle both `activity_stream_session` and `activity_stream_event` 
- [ ] add `page` to both event and session pings, it's of of ["newtab", "timeline"]

**Comment by ncloudioj** [comment]
FYI @tspurway @mzhilyaev @emtwo 

All those changes above have been made available in stage. The endpoint of Onyx remains the same for both `activity_stream_session` and `activity_stream_event` pings. You can test it by pinging at here: `https://onyx_tiles.stage.mozaws.net/v3/links/activity-stream`

Once everything is ready on the addon side, we can light them up in production and start collecting new telemetry data.

**Comment by ncloudioj** [comment]
All changes on both client and server side have been deployed!

**Comment by oyiptong** [comment]
Yay!
