### ISSUE TITLE
Ensure that embedly URL and queried URL match

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-streams#371]
When querying Embedly for URL metadata, we must make sure to check that the URLs we receive from the Embedly proxy match the URLs we submitted (ie no transformations or injections have been made).  This is primarily for security purposes.

**Comment by jaredkerim** [comment]
This is related to #258 and could be folded in to that patch.

**Comment by tspurway** [comment]
verify  and close

**Comment by edmoz** [comment]
from tim's comments, closing.
