### ISSUE TITLE
"Recent Activity" and "Just now" headings show up even when they have no content

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#378]
I've been mis-reading #271 the whole time. I always thought they were about how the "Recent Activity" heading shows up on the new tab page when you have a blank profile, and similarly how "Just now" appears on the Activity Stream/Bookmarks pages when you have no history.

The New Tab case is actually pretty easy to get into, as you could potentially have 6 "Top Sites" and 3 "Featured" sites before you see any content in the "Recent Activity".

![new_tab](https://cloud.githubusercontent.com/assets/557895/14115897/f983f686-f591-11e5-911b-b45105c0d59f.png)
**Figure 1:** Orphaned "Recent Activity" heading when you have no browsing data.

---

![activity_stream](https://cloud.githubusercontent.com/assets/557895/14115912/1185f4a0-f592-11e5-9956-367d2953eda1.png)
**Figure 2:** Orphaned "Just now" heading on Activity Stream/Bookmarks pages when you have no browsing data.

---

Ref: #200

**Comment by rlr** [comment]
I was confused too! Grabbing this one too.

**Comment by rlr** [comment]
landed fix ^
