### ISSUE TITLE
Clear feedback about deleting items

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#382]
Currently when you delete an item from your "Top Sites" or Featured/Highlights or "Recent Activity", it dies in real life and is deleted from your history [which may not be what you want or what you were expecting].

Ref: #333 

This has confused some people in the past, which has lead to history items and bookmarks being accidentally deleted.

We should improve the messaging about what it means to "Delete" each of the following:
- Top Sites
- Featured / Highlights
- Recent Activity (and Bookmarks)

![screenshot_3_29_16__5_13_pm](https://cloud.githubusercontent.com/assets/557895/14128019/a74c60ca-f5d1-11e5-9060-9432f02d062f.png)

![new_tab](https://cloud.githubusercontent.com/assets/557895/14128026/b82beeb0-f5d1-11e5-87e3-bc44bc407c2d.png)

**Comment by pdehaan** [comment]
Ref: #105

**Comment by k88hudson** [comment]
This functionality is being dealt with and tracked in https://github.com/mozilla/activity-streams/issues/397
