### ISSUE TITLE
Block vs delete history items

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#383]
Ref: #382 

Currently when you delete a "Top Site" or "Featured" result, it is gone forever. Maybe it's more appropriate to "block" or "hide" results from Top Sites/Featured instead of deleting the history item.

Once we do this, @pdehaan will complain he hid something "accidentally" and will demand a system to undo that action because I certainly didn't want to perma-ban all github.com/ URLs permanently.

**Comment by k88hudson** [comment]
Dupe of #392
