### ISSUE TITLE
Implement tippy top sites

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#384]
I'm not currently :100: on how we're integrating [**tippy-top-sites**](https://github.com/nchapman/tippy-top-sites), although @k88hudson has an open PR; #368.

We should figure out if we should pre-filter sites against the tippy-top-sites list and not route those through Embedly or what our longer term strategy is.

**Comment by nchapman** [comment]
I think initial implementation implementation should be:

1. Match URL based on `domain` with optional www. e.g. `^https?:\/\/(www\.)?#{domain}/.*?$
2. Use icon as provided
3. Use color as provided without tinting

We have a title in there which I'd love to use, but I think we should experiment with that later.

**Comment by pdehaan** [comment]
Ref: #444

**Comment by k88hudson** [comment]
See #444 for additional details

**Comment by k88hudson** [comment]
All that needs to be done here is merging stuff into the preview data, so if that work is being done in #444 this can be closed
