### ISSUE TITLE
Verify async loading on new tab load after embedly caching lands

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#385]
I _think_ this was a discussion about whether we should block React rendering until we have all results from Embedly proxy and they have been deduped so we don't see a flash of results which may still move around and get moved to different sections.

Obvious "con" in this is that if Embed.ly takes a long time to return a result (due to needing to scrape the URL), it could block page rendering for 20-30s.

¯\\\_(ツ)\_/¯

**Comment by oyiptong** [comment]
Is this still an issue? There have been changes in caching recently and an embedly client implementation

**Comment by pdehaan** [comment]
I think this has all been resolved with the caching and everything seems super speedy.
