### ISSUE TITLE
Measure individual interaction events

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#387]
Metrics Rules Everything Around Me.

We should make sure we're absolutely tracking button clicks and user interactions so we can add metrics around how user's are interacting with the site so we can make sure it's working with/for them.
We can't measure what we don't know.

Ref: #306

**Comment by k88hudson** [comment]
In addition to tracking session-based data, which is already implemented, we must also track *individual interaction events* and associated meta data.

This includes interactions which do cause a session end, including:
* individual clicks on items such as spotlight, top sites, etc.
* search attempts

as well as interactions that do not cause a session end, including:

* delete
* share attempt
* "load more"
* navigation to timeline/changing between bookmarks and history view on timeline

**Comment by k88hudson** [comment]
We also need to know what page we were on

**Comment by mzhilyaev** [comment]
Agreed by @k88hudson to report NEW_USER_EVENT notification where data value is 
```
{
  "source";  "top sites, or bookamrks, or..."
  "action_position": 3,
 "type": "click or scroll or search",
  "page": "newtab or timeline"
}
```

**Comment by mzhilyaev** [comment]
This bug tracks UI implementation for generating user events, the bug #427 is for sending actual pings to backend

**Comment by emtwo** [comment]
Just one comment. In the comment above we have
`"type": "click or scroll or search"`
But in the documentation here: https://github.com/mozilla/activity-streams/blob/master/data_dictionary.md
it's called `"event"` rather than `"type"`

Which one are we using? I think I personally prefer `"event"`
@k88hudson @mzhilyaev

**Comment by mzhilyaev** [comment]
Yes,  you are correct, we should use "event".  good catch

**Comment by k88hudson** [comment]
This is done!
