### ISSUE TITLE
Verify delete behavior for spotlight

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#392]
Ref #382 

Currently it's too easy to delete a Featured/Highlighted site, when you probably wanted to hide it from featured section instead.

@bryanbell Also has mockups showing a subtle popup menu prompting the user if they wanted to:
- Remove from Activity Stream
- Block Site from Activity Stream

![firefox_start](https://cloud.githubusercontent.com/assets/557895/14128492/2568c576-f5d6-11e5-97b5-e6be6afcabeb.png)
&mdash; via http://people.mozilla.org/~shorlander/activity-stream/activity-stream-latest/start-page.html#

Regardless of what approach we take, we should probably ensure the behavior is consistent between Top Sites, Spotlight/Hightlighted sites, and Recent Activity.

**Comment by pdehaan** [comment]
Ref: #105

**Comment by k88hudson** [comment]
This is done
