### ISSUE TITLE
Add date divider headers to Timeline

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#398]
@nchapman showed his browsing history, and he had to page through 4 pages of results before he got to yesterday. Once we got there, it was a pretty subtle date divider. We should make it more obvious that you're browsing a different date by adding a header or something else more obvious.

![activity_stream](https://cloud.githubusercontent.com/assets/557895/14128824/3f4fe5e8-f5d9-11e5-8b9a-fabfeb16a867.png)

![new_tab](https://cloud.githubusercontent.com/assets/557895/14128841/6994ba0e-f5d9-11e5-8bad-a241a1f58b5c.png)

**Comment by oyiptong** [comment]
Needs prioritization

**Comment by pdehaan** [comment]
I noticed today that I get lots of "Today at ____" subheadings if there are gaps in my browsing history.

![activity_stream](https://cloud.githubusercontent.com/assets/557895/14397734/1c04729e-fd94-11e5-9e3c-df25901d4ea5.png)
