### ISSUE TITLE
Enhanced Data Collection via embedly server

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-streams#4]
We will be using **embedly** for this, we will need to:

* verify we can use @nchapman's API key or 
* write a small proxy server for http://embed.ly/extract (see https://github.com/mozilla/activity-streams/blob/master/embedly-server.js#L31 for exact endpoint)
* connect with ops to deploy the server

**Comment by k88hudson** [comment]
We will be using **embedly** for this, we will need to:

* verify we can use @nchapman's API key or 
* write a small proxy server for http://embed.ly/extract (see https://github.com/mozilla/activity-streams/blob/master/embedly-server.js#L31 for exact endpoint)
* connect with ops to deploy the server

**Comment by oyiptong** [comment]
Here's the embedly API we're using to extract page metadata: http://docs.embed.ly/docs/extract

**Comment by jaredkerim** [comment]
Deployed URL: https://github.com/JaredKerim-Mozilla/embedly-proxy

Github repo for issues: https://github.com/JaredKerim-Mozilla/embedly-proxy

**Comment by jaredkerim** [comment]
This is blocked by the following two issues:

https://github.com/mozilla/embedly-proxy/issues/3

https://github.com/mozilla/embedly-proxy/issues/4

**Comment by jaredkerim** [comment]
Unblocked on encoded GET parameters and CORS headers.

**Comment by jaredkerim** [comment]
Dev deployed url: http://embedly-proxy.dev.mozaws.net/extract

Repo with API docs: https://github.com/mozilla/embedly-proxy

Please file issues against that repo.

**Comment by k88hudson** [comment]
Sweet! This is done
