### ISSUE TITLE
ensure event-emitter is found

### ISSUE THREAD

**Issue by oyiptong** [mozilla/activity-streams#41]
This is used by PlacesProvider.

Porting it over allows us to run in versions of firefox < 45 Beta

**Comment by oyiptong** [comment]
Can be found at: https://dxr.mozilla.org/mozilla-central/source/devtools/shared/event-emitter.js

**Comment by oyiptong** [comment]
Alternatively, prior to 44, i.e. 43 and before, event-emitter.js was found at toolkit/devtools/event-emitter.js.

It might be preferable to do a conditional load on wherever that is served.

We also need to understand at what firefox release this dependency was added.

**Comment by marcoscaceres** [comment]
Worst case, we can write our own. Event emitters are usually around ~30 lines of code.

**Comment by k88hudson** [comment]
@nchapman can you confirm what version of Firefox we support and assign to @oyiptong for any follow-up?

**Comment by oyiptong** [comment]
Sounds like we are targeting Firefox 45 from a conversation yesterday

**Comment by oyiptong** [comment]
event-emitter is actually available before 45.
It is available in 44 in the current path and earlier at a different path

**Comment by oyiptong** [comment]
closing because 45 is now release
