### ISSUE TITLE
Bug 1258973 - History is not displayed in new tab & timeline when restarting FF with "Show my windows and tabs from last time" option set

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#460]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1258973

---

Created attachment 8733775 [details]
No history display after restart.png

#### [Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.3
- Activity Stream 1.0.4

#### [Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

#### [Prerequisites]:
- Latest Activity Stream add-on version (1.0.4) was previously installed on a profile.  

#### [Steps to reproduce]:

1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Navigate to a couple of pages in order to have some history stored.
3. Open the FF options page.
4. Change "When Firefox starts" option into "Show my windows and tabs from last time".
5. Open two new tabs, and in one of them open the "Activity Stream Timeline" page.
6. Wait for the pages to display the stored history and after close the browser.
7. Restart the browser with the same profile and observe both the opened pages .

#### [Expected results]:
The previously stored history is correctly displayed on both pages.

#### [Actual results]:
Both the pages have no history displayed, just the empty placeholders and activity areas (see attached screenshot).

**Comment by tspurway** [comment]
please mark as duplicate in bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1258973

**Comment by rlr** [comment]
actually, the commit for this was in a PR but without a test so I removed it from the PR. I'm still working on this.
