### ISSUE TITLE
Fix async issues with preview caching

### ISSUE THREAD

**Issue by oyiptong** [mozilla/activity-streams#466]
There are many bugs with preview caching, especially around handling async events.

The behavior becomes non-deterministic. Judicious use of Task.async and Task.spawn will solve the problems.

**Comment by oyiptong** [comment]
#481 renames async functions in PreviewProvider so they are clearly stated. This should help in identifying issues

**Comment by rlr** [comment]
This should be fixed now. 3ca6787b7285eb2323879eb67d5e8b6826f60a62
