### ISSUE TITLE
Bug 1262125 - The bookmarked websites are not displayed with bookmarked status and icon in “Activity Stream Timeline” and “New Tab” page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#468]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1262125

---

Created attachment 8738122 [details]
bookmarked websites are not displayed.mp4

#### [Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.7

#### [Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

#### [Prerequisites]:
- Latest Activity Stream add-on version (1.0.7) was previously installed on a profile.
- Have at least one website in "Highlights" area from Activity Stream Timeline.
- Multiple pages were previously visited in order to have items displayed in all areas of both “Timeline” and “New Tab” pages. 

#### [Steps to reproduce]:

1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Click on "Activity Stream" button from browser toolbar.
3. Click on a link from a website in Timeline.
4. Bookmark this page.
5. Return to Activity Stream Timeline.
6. Observe how the bookmarked page is displayed in “Highlights” and “Just now” areas.
7. Navigate to “Bookmarks” tab from Timeline page and observe the recently bookmarked page.

#### [Expected results]:
6\. The website that was bookmarked has a blue star in front of the favicon in the "Just now" area. In the "Highlights" area the status of the item was changed to "Bookmarked x seconds/minutes ago".
7\. The bookmarked website is correctly displayed in “Bookmarks” tab.

#### [Actual results]:
6\. The website that was bookmarked has no blue star in front of the favicon in the "Just now" area. And also the status of the page does not change in the "Highlights" area.
7\. The bookmarked website is not displayed in “Bookmarks” tab.

#### [Notes]:
This issue is reproducible also in New Tab page.

**Comment by SoftVision-PaulOiegas** [comment]
It seams that the entire functionality for bookmarks has update issues on the UI side. If you have a profile with previously bookmarked pages, the status and symbol is not updated when removing them from bookmarks.
