### ISSUE TITLE
Bug 1262174 - Last visited site is only displayed after a second refresh in "Activity Stream" and "New Tab" pages

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#472]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1262174

---

#### [Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.7

#### [Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

#### [Prerequisites]:
- Latest Activity Stream add-on version (1.0.7) was previously installed on a profile.

#### [Steps to reproduce]:
1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Visit a site and after the site is loaded click the "Activity Stream" button.
3. Observe the "Highlights" and "Just Now" areas.

#### [Expected results]:
Last visited site is displayed in the "Just Now" area of  "Activity Stream" page

#### [Actual results]:
Last visited site is only displayed after a second refresh in the "Just Now" area of  "Activity Stream" page

#### [Notes]:
-Sometimes this issue is observed after the first visited site and sometimes only after a couple of sites.
-This issue is also reproducible in the "New Tab" page.
-This is the link for the screen recording of the issue: https://goo.gl/7twXwh.

**Comment by rlr** [comment]
landed fix
