### ISSUE TITLE
Unable to delete Highlight sites from Activity Stream/Timeline page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#490]
In `activity-streams-experiment@1.0.8`, I'm noticing that I can delete Highlights results from the NewTab page, but not when I'm on the Timeline page.

![activity_stream_and_new_issue_ _mozilla_activity-streams_and_add_entry_for_gmail_com__mail_google_com__ _issue__26_ _nchapman_tippy-top-sites](https://cloud.githubusercontent.com/assets/557895/14392876/98538c2a-fd78-11e5-8f3e-26458f508c94.png)

**Comment by k88hudson** [comment]
Let's also add a test to catch this

**Comment by rlr** [comment]
landed fix
