### ISSUE TITLE
Strange event pings captured in 1.0.8

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-streams#493]
Seeing some invalid pings in the database as follows,

| "source" | "event" |
|----------|---------| 
|   topsites |  click  |

The correct values for those two fields should be both in uppercase as "TOP_SITES" and "CLICK", respectively.

Looks like we're using it as the test data in `test-TabTracker.js`, but it shouldn't send pings back to server in the test environment.

**Comment by ncloudioj** [comment]
I've been following this bug for a few days. Turns out it only showed up on 2016-04-08, no more strange pings found since then.

**Comment by ncloudioj** [comment]
Reopen it as we have capture those pings again. @emtwo is investigating this now.

**Comment by emtwo** [comment]
This issue can be avoided for now by never running `jpm test` without a config to point to the stage server. I also filed issue #525 which should avoid accidentally sending test pings to prod.

**Comment by k88hudson** [comment]
Closing this since CI no longer sends errant events.
