### ISSUE TITLE
Event pings are much fewer than the session pings

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-streams#494]
So far the total number of event pings is appr. 500 in the database, which is way behind of session pings. We need to investigate it to avoid potential data lose.

Infernyx will treat the event ping as an invalid payload, if any of following fields is missing:
* client_id
* addon_version
* page
* tab_id
* event

Let's make sure those required fields have been populated in the payload. Also, if any of those should not be required but optional, we need to change that for Infernyx.

@emtwo @k88hudson

**Comment by emtwo** [comment]
I confirmed that we do add all of these fields in the ping sent. I think it would be useful to look at the 500 pings that *were* received and see if there are perhaps certain `event` types not coming through or perhaps events from a certain `page` are not coming through. It would help narrow down the investigation.

**Comment by ncloudioj** [comment]
Thanks for confirming it! @emtwo 

I've also confirmed that the total # of events in the raw logs is exactly the same as the # in the database (about 480 by far). So the pings sent by the addon are all well-formatted. So, people just haven't clicked too much yet :)

As a side note, there are hundreds of event pings with page "topsites" and event "click", as mentioned in #493. Seems like those pings were sent in a quite short period of time (within a second). Perhaps generated by the testing server? Anyway, we should find it out and disable it in order to keep the telemetry data accurate and clean.
