### ISSUE TITLE
Recent Activity is sometimes truncated

### ISSUE THREAD

**Issue by nchapman** [mozilla/activity-streams#496]
Sometimes my Recent Activity is truncated on new tab:

![screen shot 2016-04-08 at 3 48 02 pm](https://cloud.githubusercontent.com/assets/3095/14399434/858931a2-fda1-11e5-96b1-41317c7e1621.png)

Notice that there are only 6 results here and no "See more activity" button. If I immediately open another new tab or reload, it seems to be fixed.

**Comment by bryanbell** [comment]
<img width="986" alt="pasted_image_4_11_16__10_31_am" src="https://cloud.githubusercontent.com/assets/228979/14436271/bf347304-ffd0-11e5-95d3-0498f5328bdb.png">
Often get one or 2 recent items... 

<img width="1141" alt="pasted_image_4_11_16__10_33_am" src="https://cloud.githubusercontent.com/assets/228979/14436303/dfffd600-ffd0-11e5-9135-7f808bae5d86.png">
On reload, I'm still not getting a complete Recent Activity section (note: show more is missing). 

After several reload I finally get the page to load.

**Comment by oyiptong** [comment]
this should've been fixed by #541. I'll leave it open until we can verify

**Comment by pdehaan** [comment]
FWIW, I don't seem to be able to reproduce this in 1.0.12.

**Comment by edmoz** [comment]
I'm not able to repro either. @nchapman please reopen if you're still seeing it.
