### ISSUE TITLE
Timeline view does not send USER_CLICK_EVENTS from ACTIVITY_FEED source

### ISSUE THREAD

**Issue by mzhilyaev** [mozilla/activity-streams#500]
* open newtab view
  * click on "Recent Activity" links 
  * the clicks will result in a user click event as below:
```
{
 "event": "CLICK",
 "page": "NEW_TAB",
 "source": "ACTIVITY_FEED",
 "action_position": 5,
 "action": "activity_stream_event",
 "tab_id": "-5-12",
 "client_id": "1dbf20c4-35c0-6440-b0e2-115d79c0c5e3",
 "addon_version": "1.0.8",
 "locale": "en-US"
}
```
   * bring timeline view
   * click on any link under "Just now" section
  * no event is generated

Expected to see same event generated by the timeline

**Comment by ncloudioj** [comment]
As a followup, I've been seeing similar missing events on the `Timeline` page,
- all clicks from the `Bookmark` section were not sent
- only sent `LOAD_MORE` events but not the following `CLICK` events

**Comment by rlr** [comment]
landed
