### ISSUE TITLE
Remove "source" property for tab session duration ping

### ISSUE THREAD

**Issue by mzhilyaev** [mozilla/activity-streams#501]
The "source" property only makes sense for the user action and is now handled by sending a user-event-ping as in https://github.com/mozilla/activity-streams/blob/master/data_dictionary.md#example-activity-stream-event-log.   Implemented in https://github.com/mozilla/activity-streams/pull/465

This make keeping "source" property in the tab-session ping meaningless, and it's always being set to "other".  Suggest removing it.
Need @ncloudioj  or @oyiptong , or @tspurway  OK on it.

**Comment by oyiptong** [comment]
I concur. Let's remove it.

**Comment by ncloudioj** [comment]
@mzhilyaev Yup, let's remove it. Infernyx already leaves "source" out before storing the pings in redshift.
