### ISSUE TITLE
Bug 1262752 - 'feed-icon-image' is not displayed for websites even if it is available

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#503]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1262752

---

Created attachment 8738907 [details]
Untitled.png

#### [Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.7
 
#### [Affected platforms]:
- All Windows
- All Mac OS
- All Linux

#### [Prerequisites]:
- Latest Activity Stream add-on version (1.0.7) was previously installed on a profile.
- Have more websites in "Recent Activity" area from Activity Stream New Tab.

#### [Steps to reproduce]:
1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Open a new tab and go to http://store.steampowered.com/app/380220/.
3. From the previously visited link, visit another URL that points to a game.
4. Repeat step 3 about three-four times.
5. Open a new tab and observe the "Recent Activity" section (if the visited websites are not displayed, please open another New Tab).

#### [Expected result]:
- The visited websites have displayed the feed-icon-image and site-icon-favicon.

#### [Actual result]:
- This issue has a random order.
- Some of the visited websites have displayed only the site-icon-favicon without feed-icon-image, although feed-icon-image exists.

#### [Notes]:
- This issue is also reproducible in Activity Stream Timeline.
- There is a task in GitHub (https://github.com/mozilla/activity-streams/issues/193) regarding this issue, but it is marked as Closed. This issue is still reproducible in Activity Stream v1.0.7.

**Comment by k88hudson** [comment]
This is working as expected, but perhaps we should consider adjustments to the experience here

**Comment by oyiptong** [comment]
This was resolved WONTFIX on bugzilla. Closing here.
