### ISSUE TITLE
Seeing duplicate pings in the raw event logs

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-streams#506]
@mzhilyaev @tspurway @k88hudson 

I've noticed that there are duplicate records in the "activity_stream_event" raw logs. Until now on 2016-04-12, 94 out of 391 are duplicate records in our system. 

Still investigating the cause of this issue, either it got duplicated on Onyx, or the addon has sent more than one pings for the same event at a time. Either way, we need to figure out what's going on. Since Infernyx will filter out the duplicates, it won't affect the Redshift database for now. 

Some sample records attached here:
```json
["activity_stream_event_stats","59f0e18f-e9d7-***-92dc742645b5","-3-59","TOP_SITES","2","1.0.8","en-US","NEW_TAB","CLICK","2016-04-12 07:39:46","2016-04-12","RO","Linux","Firefox","48.0","Other"]
["activity_stream_event_stats","59f0e18f-e9d7-***-92dc742645b5","-3-59","TOP_SITES","2","1.0.8","en-US","NEW_TAB","CLICK","2016-04-12 07:39:46","2016-04-12","RO","Linux","Firefox","48.0","Other"]
```

```json
["activity_stream_event_stats","33ebc20a-df0d-***-0c88a52950d9","-5-12","ACTIVITY_FEED","5","1.0.8","en-US","NEW_TAB","CLICK","2016-04-12 08:33:32","2016-04-12","RO","Windows XP","Firefox","48.0","Other"]
["activity_stream_event_stats","33ebc20a-df0d-***-0c88a52950d9","-5-12","ACTIVITY_FEED","5","1.0.8","en-US","NEW_TAB","CLICK","2016-04-12 08:33:32","2016-04-12","RO","Windows XP","Firefox","48.0","Other"]
```

**Comment by ncloudioj** [comment]
Update:

The duplicate pings showed up since the first day of 1.0.8. In some cases, there were up to 20 same pings got sent at a time. Also note that multiple clients have been observed with this issue.

**Comment by k88hudson** [comment]
Since this was caused by pings in tests and this is solved in our UI by https://github.com/mozilla/activity-streams/commit/5919d9e491a2d7e52703b77b152a22196e64e17a, I'm going to mark as resolved.
