### ISSUE TITLE
CSP policy blocks local development

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-streams#507]
Right now our CSP doesn't allow linking to remote scripts including localhost, which is required for local development.

**Comment by oyiptong** [comment]
hmm we should fix it ASAP

**Comment by oyiptong** [comment]
let's revert @emtwo's change for now and have a different rule for development?

**Comment by k88hudson** [comment]
@oyiptong yep sounds good to me :+1:

**Comment by oyiptong** [comment]
fixed by ddc9fb82e9b961dea186d918d8bbfc0ef8dab181
