### ISSUE TITLE
Sidebar and header on the timeline should not scroll. 

### ISSUE THREAD

**Issue by bryanbell** [mozilla/activity-streams#509]
<img width="1215" alt="sidebars" src="https://cloud.githubusercontent.com/assets/228979/14476204/3a09337c-00bb-11e6-8550-02197a530d65.png">
these items should never scroll.

**Comment by pdehaan** [comment]
Ref: #408

**Comment by bryanbell** [comment]
The timeline surface is a web-app, and therefore its controls need to remain visible at all times.

**Comment by rlr** [comment]
landed
