### ISSUE TITLE
toolbar icons needs to be changed

### ISSUE THREAD

**Issue by bryanbell** [mozilla/activity-streams#510]
<img width="56" alt="pasted_image_4_12_16__2_40_pm" src="https://cloud.githubusercontent.com/assets/228979/14476433/94500f94-00bc-11e6-9d1e-e8985b580ca5.png">
This icon is the wrong color and for the test is probably the wrong symbol.

**Comment by pdehaan** [comment]
FWIW, it looks like we have the following [very similar] icons in /content-src/static/img/:

| ICON | URL |
|:----:|----|
| ![](https://rawgit.com/mozilla/activity-streams/master/content-src/static/img/list-icon.svg) | [./content-src/static/img/list-icon.svg](https://github.com/mozilla/activity-streams/blob/master/content-src/static/img/list-icon.svg)
| ![](https://rawgit.com/mozilla/activity-streams/master/content-src/static/img/glyph-activityStream-16.svg) | [./content-src/static/img/glyph-activityStream-16.svg](https://github.com/mozilla/activity-streams/blob/master/content-src/static/img/glyph-activityStream-16.svg)

**Comment by pdehaan** [comment]
Hopefully one of those icons is right. And crossing my fingers that it's the latter one, because that's the same icon I used in #495 where I added an icon to the about:addons page.

**Comment by edmoz** [comment]
can i also add it looks the same as the bookmark list icon (to the right of the 'star')

**Comment by bryanbell** [comment]
![newicon](https://cloud.githubusercontent.com/assets/228979/14694469/955d0b46-071d-11e6-8202-fa54d6c6adc0.png)

**Comment by bryanbell** [comment]
> can i also add it looks the same as the bookmark list icon (to the right of the 'star')

That was on purpose... we intend to supplant the bookmarks menu eventually.

**Comment by edmoz** [comment]
I see a new icon - should we close this out bryan?

**Comment by pdehaan** [comment]
This is what I see in about:addons and my toolbar:

<img width="958" alt="add-ons_manager_and_irccloud_and_tippy-top-sites_top_sites_json_at_master_ _nchapman_tippy-top-sites_ _github" src="https://cloud.githubusercontent.com/assets/557895/14793862/0a2b7898-0ad6-11e6-85dd-f6add82c091a.png">

Closing.

**Comment by bryanbell** [comment]
yeah you can close this
