### ISSUE TITLE
Rename repo to "activity-stream" (singular) and any references to plural naming

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#517]
I think there is some confusion between singular vs plural and we aren't being entirely consistent.
Now would a pretty good time to make sure everything is proper, since it gets a lot trickier after we ship.

| SOURCE | TEXT | NOTES
|----|----|----|
| IRC: | **activity-stream** | singular
| GitHub: | **activity-streams** | plural
| package.json: | **activity-streams** | plural
| addon: | **activity-streams-_experiment_** | plural [w/ suffix]
| Test Pilot: | **Activity Stream** | singular
| Telemetry endpoint: | **activity-stream** | singular

**Comment by pdehaan** [comment]
From IRC:

\<bryanbell\> it’s STREAM 
\<shorlander\> bryanbell: ++

**Comment by edmoz** [comment]
I'd say we go with 'singular' as this conflicts less with other projects. However, any string changes would be post v1.  @nchapman what do you think?

**Comment by nchapman** [comment]
Talking to Marketing folks about this tomorrow.

**Comment by pdehaan** [comment]
I think @nchapman was saying the action on this was "switch to activity stream" singular, and we'll possibly do a rename in the distant future.

So i think the main action here is to rename GitHub repo to "activity-stream" (singular) and update any references in Test Pilot, etc. Probably best to do this before pushing the next XPI.
Plus, everybody will need to update their Git upstreams.

**Comment by edmoz** [comment]
Kate was suggesting that we do this Friday before we ship so that we don't break references after. This introduces some risk in broken links on test pilot, but updating urls in django admin shouldn't be too difficult.

**Comment by pdehaan** [comment]
Once this repo is renamed, we'll need to ping @ckprice so he can make sure all the URLs to changelogs and repos are updated in the Test Pilot Django admin site.

**Comment by nchapman** [comment]
> we'll need to ping @ckprice so he can make sure all the URLs to changelogs and repos are updated in the Test Pilot Django admin site.

I can make these changes so you may ping me instead 😄
