### ISSUE TITLE
New Tab, and Activity Stream should have different Tab icons 

### ISSUE THREAD

**Issue by bryanbell** [mozilla/activity-streams#545]
<img width="258" alt="pasted_image_4_20_16__9_57_pm" src="https://cloud.githubusercontent.com/assets/228979/14698381/07e3dc88-0743-11e6-9c3b-dd8e3ca22698.png">

We're overusing the activity stream icon.

**Comment by pdehaan** [comment]
What icon should we use for New Tab page?

**Comment by bryanbell** [comment]
I'm thinking about it.

**Comment by bryanbell** [comment]
example of how it will be. 
![newtab](https://cloud.githubusercontent.com/assets/228979/14753378/0274245e-088a-11e6-9f1c-e0006271d90c.png)

**Comment by ciprianmuresan** [comment]
Can we do something about how the icons look on Ubuntu? By default Ubuntu has a black theme on the New Tab bar, making the icon really hard to make out if the tab is unfocused.
![1 0 12 icons](https://cloud.githubusercontent.com/assets/18304511/14818107/dae2e168-0bc3-11e6-9f17-3d7d9ceca8f5.png)

**Comment by pdehaan** [comment]
Yeah, plus here's what they look like w/ Developer Edition's default dark theme on OSX.

![firefox_test_pilot_-_activity_stream_and_firefox_test_pilot_-_tab_center](https://cloud.githubusercontent.com/assets/557895/14831056/cefd22b6-0ba8-11e6-9816-8149a02a7352.png)

![firefox_test_pilot_-_activity_stream_and_job__10253_3_-_mozilla_fxa-content-server_-_travis_ci_and_firefox_test_pilot_-_experiments](https://cloud.githubusercontent.com/assets/557895/14831084/ed7decfc-0ba8-11e6-9e51-2a95d9f4f08b.png)
