### ISSUE TITLE
Final Assets for Test Pilot

### ISSUE THREAD

**Issue by johngruen** [mozilla/activity-streams#549]
[Here's spreadsheet for Test Pilot assets](https://docs.google.com/a/mozilla.com/spreadsheets/d/170wRKBJ6LV67wIwAm8flkyYaweYNejuuiZU6tENgbcg/edit?usp=sharing). Please add links/copy/etc. I'll be tracking this bug and pestering @nchapman and @bryanbell

**Comment by edmoz** [comment]
@nchapman can we call this done?

**Comment by nchapman** [comment]
Yep done enough!
