### ISSUE TITLE
Remove listeners will not actually remove listeners

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-streams#55]
I just noticed right now in ActivityStreams we have:

```
  _setupListeners() {
    PlacesProvider.links.on("deleteURI", this._handlePlacesChanges.bind(this));
    ...
```

```
  _removeListeners() {
    PlacesProvider.links.on("deleteURI", this._handlePlacesChanges);
    ...
```

I think `this.fn !== this.fn.bind(this)`, so we'll need to use a different strategy for this

**Comment by oyiptong** [comment]
You are correct.

event-emitter.js uses a `Map` to hold the listeners: https://dxr.mozilla.org/mozilla-central/source/devtools/shared/event-emitter.js#65

Also, this.fn.bind(this) !=== this.fn.bind(this)

**Comment by rlr** [comment]
landed
