### ISSUE TITLE
Bug 1266408 - The second YouTube video wrongly inherits the picture from the first when displayed in Highlights area

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-streams#555]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1266408
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.10

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.10) was previously installed on a clean profile.  

[Steps to reproduce]:
1. Open browser and visit YouTube.com.
2. Click on a video in order to play.
3. Click the Activity Stream button from the browser toolbar.
4. Refresh the Activity Stream Timeline page and then switch back to the YouTube video tab.
5. Click a different video in order to be played.
6. Switch back to the Activity Stream Timeline tab and refresh the page. 
7. Observe the Highlights area.

[Expected result]:
The tile from Highlights with the YouTube video is updated with the last played video.

[Actual result]:
The last played YouTube video that is displayed in Highlights has the same picture as the first played video.

[Notes]:
- In Highlights tiles, all YouTube videos that will be played will have the same picture as the first played video.
- Attached a screenshot of the issue.
![screenshot of the issue](https://cloud.githubusercontent.com/assets/17258026/14782149/1b080806-0af0-11e6-8e46-20f42a4240f4.png)

**Comment by k88hudson** [comment]
This looks like a `toLowerCase` issue

**Comment by k88hudson** [comment]
This is a problem with the cache key not including the querystring

**Comment by pdehaan** [comment]
Fixed by #563

**Comment by SoftVision-PaulOiegas** [comment]
Verified in Activity Stream add-on v1.0.15 using latest Nightly build (20160508030214) and it no longer occurs. Marked as verified - fixed in Bugzilla.
