### ISSUE TITLE
Bug 1266736 - Highlights tiles from Timeline and New Tab pages are populated by number of visits instead of recently viewed

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-streams#557]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1266736
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.11

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.11) was previously installed on a clean profile.  

[Steps to reproduce]:
1. Open the browser and visit a webpage
2. Open a new tab and visit the page from step #1
3. Repeat step #2 15 times.
4. Open a different webpage in a new tab.
5. Repeat step #4 10 times (close other tabs).
6. Open a third webpage in a new tab.
7. Repeat step #6 5 times (close other tabs).
8. Open a fourth webpage in a new tab.
9. Click the Activity Stream button from the browser toolbar.
10.Observe the Highlights tiles.

[Expected result]:
Webpages displayed in Highlights tiles are in reverse chronological order.

[Actual result]:
Webpages that are added to Highlights tiles are ordered by number of visits.

[Notes]:
- This is reproducible in the New Tab page, but only after Top Sites area is populated.
- A side effect to this issue is the fact that you can visit 3 pages an absurd amount of times and have them be stuck in the Highlights tiles.

**Comment by k88hudson** [comment]
This is expected since the current query is ordered by Frecency, not date visited. The query will change when https://github.com/mozilla/activity-streams/pull/546 lands.
