### ISSUE TITLE
Bug 1266741 - "Just now" area goes blank and history timeline is interrupted when fetching old visited websites

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-streams#558]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1266741
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.11

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- The used Firefox profile is an old one with a lot of data and history.
- Install the Activity Stream add-on on the old profile

[Steps to reproduce]:
1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Click on "Activity Stream" button from browser toolbar.
3. Click on "See more activity" button from Timeline.
4. Wait for the content to load.
5. Click on "See more activity" button from Timeline.
6. Repeat steps 3 to 5 multiple times.

[Expected results]:
Every time "See more activity" button is clicked, old history is fetched and displayed in timeline.

[Actual results]:
- After a few tries the entire content  of just now ares is removed
- If you wait for a few seconds, the "Just now" area is repopulated with content, but the previous displayed items are no longer visible. Instead of them the content requested at the last "Show more" operation is now displayed at the beginning of the section.
![timeline content](https://cloud.githubusercontent.com/assets/17258026/14782752/d310b42c-0af3-11e6-8fe1-a351f6b19df4.jpg)

**Comment by k88hudson** [comment]
Ok I was able to reproduce this, the reason is because the query is timing out before results are received ```
action Object { type: "RECENT_BOOKMARKS_RESPONSE", error: true, data: E_TIMEOUT }
```

**Comment by pdehaan** [comment]
+1. I was seeing this today on my main profile with a big browsing history.
But wasn't able to reproduce after refreshing the page and trying again (presumably because the results were then cached).
