### ISSUE TITLE
Bug 1267239 - After clicking on "See all activity" in "New Tab" page you are wrongly redirected to the middle of the "Timeline" page

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-streams#559]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1267239
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.11-dev-1461350837

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.11-dev-1461350837) was previously installed on a clean profile.  
- Multiple pages were previously visited (at least a day old) in order to have items displayed in all areas of both “Timeline” and “New Tab” pages. 

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites
2. Open a new tab and scroll down to the bottom of the page.
3. Click "See all activity" button.

[Expected result]:
You are redirected to the "Timeline" page and positioned at the top.

[Actual result]:
You are redirected to the "Timeline" page and positioned at the middle of the page. 

[Notes]:
- Attached a screen recording of the issue https://goo.gl/zJGw26

**Comment by k88hudson** [comment]
This can be fixed by adding a scroll to top when the route changes (see `history.listen` in`content-src/components/Routes/Routes.js`)

**Comment by rlr** [comment]
this landed a day or two ago e903760aca9671a9f9ea556d2b1dd3a1bdfa72f3

**Comment by SoftVision-PaulOiegas** [comment]
Verified in Activity Stream add-on v1.0.15 using latest Nightly build (20160508030214) and it no longer occurs. Please mark it as Resolve - Fixed in Mozilla so we can update it there too.
