### ISSUE TITLE
Bug 1267243 - Pages with no images are displayed in both "Timeline" and "New Tab" Highlights section

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-streams#560]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1267243
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.11 -dev-1461350837

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.11-dev-1461350837) was previously installed on a profile.

[Steps to reproduce]:
1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Visit a website without a lead image or a website that has no images al all (eg: http://goo.gl/PppycE).
3. Click on "Activity Stream" button from browser toolbar.

[Expected results]:
- The visited website is not displayed in the Highlights area because it has no images.

[Actual results]:
- The visited website is displayed in the Highlights area.

[Notes]:
- This issue is reproducible also in New Tab page.
- Attached screenshot off the issue.
![pages with no images displayed in highlights](https://cloud.githubusercontent.com/assets/17258026/14786733/e01327b2-0b08-11e6-9a5a-bddbe5956cd6.jpg)

**Comment by k88hudson** [comment]
This is the intended behaviour: image-less items will show up as a fallback if no items are available as a fallback
