### ISSUE TITLE
Bug 1267245 - Description is not displayed for pages with long title in "Highlights" section from "Timeline" and "New Tab" pages

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-streams#561]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1267245
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.11 -dev-1461350837

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.11 -dev-1461350837) was previously installed on a clean new profile.

[Steps to reproduce]:
1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Open a new tab and visit a page that has a long title (eg: http://goo.gl/DKW6Aw). 
3. Click on "Activity Stream" button from browser toolbar. 
4. Observe the description of the page in the "Highlights" area (refresh the page if the page is not displayed).

[Expected results]:
The description of the page is displayed in the designed area.

[Actual results]:
The description of the page is not displayed in the designed area.

[Notes]:
- This issue is reproducible also in New Tab page.
- Attached a screenshot of the issue.
![the description of the sites incorrectly truncated](https://cloud.githubusercontent.com/assets/17258026/14786835/6480bbcc-0b09-11e6-8559-3069ec6475e5.png)

**Comment by k88hudson** [comment]
This is the intended behaviour if a title exceeds the height of the highlight box. @bryanbell can you confirm this?

**Comment by SoftVision-PaulOiegas** [comment]
Since this was closed, should we understand that this is the intended behavior ? I haven't seen Bryan responding to Kate's question.
