### ISSUE TITLE
You Tube's are not being shown with the available cover art. 

### ISSUE THREAD

**Issue by bryanbell** [mozilla/activity-streams#562]
![pasted_image_4_25_16__10_21_am](https://cloud.githubusercontent.com/assets/228979/14792559/a48e1000-0acf-11e6-94a5-c34ccb615ad6.png)

You Tubes will have a high likelihood of being Featured, yet we should the single worst bit of art to display them.

**Comment by k88hudson** [comment]
I think this will be fixed by #555

**Comment by bryanbell** [comment]
<img width="727" alt="pasted_image_4_25_16__4_00_pm" src="https://cloud.githubusercontent.com/assets/228979/14801572/0c18abb6-0aff-11e6-8549-a27d5569deb0.png">
 this too?

**Comment by pdehaan** [comment]
@bryanbell Can you confirm this is fixed?

**Comment by nchapman** [comment]
Bryan says it's fixed!
