### ISSUE TITLE
Point add-on to production embedly-proxy server

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#565]
After https://github.com/mozilla/embedly-proxy/issues/69 is resolved, that is.

![](https://media.giphy.com/media/kxNQqpj1wTiX6/giphy.gif)

**Comment by edmoz** [comment]
@jaredkerim is our PROD server up and running and is this just changing the endpoint?

**Comment by jaredkerim** [comment]
The production embedly server is online at:

https://embedly-proxy.services.mozilla.com/

**Comment by pdehaan** [comment]
Is the only thing that needs to change the `embedly.endpoint` key in [package.json:129](https://github.com/mozilla/activity-streams/blob/0ff3de001ac0779fd341bf6ce3c52ac18b643d3c/package.json#L129) and the `EMBEDLY_ENDPOINT` key in [config.production.yml:4](https://github.com/mozilla/activity-streams/blob/3523ca26dbb4fc29156d696af9d47ae6e7651234/config.production.yml#L4)?

**Comment by oyiptong** [comment]
the config.production line doesn't need anything because content shouldn't use it
