### ISSUE TITLE
Point to production Onyx server?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#568]
Re: https://github.com/mozilla/activity-streams/search?utf8=%E2%9C%93&q=onyx

It looks like we have a couple instances of https://onyx_tiles.stage.mozaws.net/v3/links/activity-stream

Not sure if we need to change those to a production URL, or just leave those as stage since they are for "dev-prefs.json" and "test-prefs.json" (which we may not want pinging production).

**Comment by ncloudioj** [comment]
Yes, those are all for the dev/testing purposes, and intentionally being pointed to the stage onyx server.
