### ISSUE TITLE
clicking 'see more activity' in timline view repeatedly eventualy loads only one new row

### ISSUE THREAD

**Issue by edmoz** [mozilla/activity-streams#577]
1. i'm on 1.12 - have a profile with history
2. goto timeline and click 'see more activity'
3. do this 3-4 times. 

actual: on the 4th time - you'll start to see only one row of history display.

expected: i should see 5-10 items load for each click.

**Comment by pdehaan** [comment]
@k88hudson says this is resolved by recent commits. Closing.
