### ISSUE TITLE
hide checkboxes and urls in about:addons prefs

### ISSUE THREAD

**Issue by edmoz** [mozilla/activity-streams#579]
This was discussed to leave or hide checkboxes and urls in addon prefs

<img width="1169" alt="screen shot 2016-04-26 at 2 00 01 pm" src="https://cloud.githubusercontent.com/assets/3698618/14834067/46a44e1c-0bb7-11e6-88ec-20c795ecdb2c.png">

**Comment by oyiptong** [comment]
Howdy, @nchapman, @edmoz.

I think there is still value in keeping some checkboxes. In a previous patch, i hid the server endpoint prefs. However, toggling rich link previews and performance logging are still valuable to the end user.

As well, toggling Telemetry has historically been an important point for savvy Firefox users. Having the option doesn't hurt, and no one will actually go to that addon page unless they really want to.

And if they get to that page, they sure as hell want to change things.

Was there anything specific you wanted to remove there?

**Comment by pdehaan** [comment]
@oyiptong I disabled rich previews and the add-on stopped working for me. #581

**Comment by oyiptong** [comment]
That would arguably be a problem with the content side not working without previews.
We're already sending links without previews to content if they are not cached currently.

**Comment by nchapman** [comment]
Here's a screenshot of how it looks currently for reference:

<img width="1204" alt="screen shot 2016-05-04 at 8 03 36 am" src="https://cloud.githubusercontent.com/assets/3095/15018554/e94bbb60-11ce-11e6-952a-8591c6e478b0.png">

I think we should hide the following:

**Enable query caching mode**

I don't think there's any user value to disabling this and could end up causing a seriously degraded experience.

**Enable rich link previews**

I think this will provide value when we decide how to handle items without rich data in the front end. Until we do this, it just wrecks the entire UI.

I agree that the others are useful. What do you think @oyiptong?

**Comment by nchapman** [comment]
Another question while we're on the topic... should we enable performance logging by default?

**Comment by oyiptong** [comment]
1. I agree about query caching.
2. Links without rich previews *should* work. We should double check why it's breaking, because that's a very real scenario in the current implementation (e.g. new link, embedly proxy hasn't responded yet, link is returned without rich previews)
3. We are sending performance data via telemetry. Performance logging just enables the output in the browser console. I'm unsure we want that by default, but it's handy to turn it on if you know where to look.

**Comment by nchapman** [comment]
> Links without rich previews should work. We should double check why it's breaking, because that's a very real scenario in the current implementation (e.g. new link, embedly proxy hasn't responded yet, link is returned without rich previews)

@k88hudson do you know if this is something we'll address before v1? This would definitely help our perceived performance.

**Comment by nchapman** [comment]
> We are sending performance data via telemetry. Performance logging just enables the output in the browser console. I'm unsure we want that by default, but it's handy to turn it on if you know where to look.

Oh okay got it. Yeah let's leave that one in and unchecked.

**Comment by rlr** [comment]
landed.
