### ISSUE TITLE
UI shifts while loading more activity

### ISSUE THREAD

**Issue by nchapman** [mozilla/activity-streams#586]
![screen recording 2016-04-27 at 09 57 am](https://cloud.githubusercontent.com/assets/3095/14860791/35ac94cc-0c5f-11e6-8924-5512735a418f.gif)

The loading message should occupy the same amount of space as the "See more activity" button so that the UI doesn't shift when it's pressed.

**Comment by pdehaan** [comment]
Fixed via #634
