### ISSUE TITLE
Add larger icon in about:addons

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#599]
Found in 1.0.13:

### Steps to reproduce:
1. Install the activity-streams add-on via Test Pilot
2. Go to about:addons. 

### Actual results

Icon is small-ish (looks 16x16, whereas the Test Pilot one is 32x32, and the default Universal Search one looks the same size).

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/14903237/aacb05a4-0d54-11e6-8ca0-35900bf5d1cb.png)

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/14903263/cfc4cb9c-0d54-11e6-9542-118f05aeba80.png)

### Expected results:
Bigger SVG icon.

**Comment by bryanbell** [comment]
icon

[ActivityStream-32.svg.zip](https://github.com/mozilla/activity-streams/files/245576/ActivityStream-32.svg.zip)

**Comment by pdehaan** [comment]
PR incoming. Current status:

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/14964456/0a21d9e6-105d-11e6-81fa-5e29f55eb9fe.png)

---

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/14964495/32ff3ca0-105d-11e6-98c0-a5db38f6885e.png)
