### ISSUE TITLE
Tracking: Create new tables, api endpoints for reporting

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-streams#6]
We will collect key metrics to determine the success of the experiment sent to our data pipeline through TestPilot.

The reporting period will be from **April 1 to early June**.

We will instrument our add-on to collect the metrics we want, as well as collect control data from existing experiences in order to perform a comparison.

On the back-end, we will create new tables/an api endpoint to use with TestPilot. We also need a front-end analysis interface, such as a static visualization of our key metrics.

**Comment by k88hudson** [comment]
Blocked on #27

**Comment by ncloudioj** [comment]
This has been landed in production. The table schema was designed by referring to #27 

The implementation of endpoint will be blocked by #7
