### ISSUE TITLE
TypeError: this._populatingCache is undefined: _handlePlacesChanges@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/ActivityStreams.js:180:9

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#602]
OK, this is random.

Using latest (1.0.13) Activity Stream add-on, and randomly spotted this in the Browser Console:

![browser_console_and_search_results_and_jar_file____users_pdehaan_dev_github_ff-tool__temp_browsers_firefoxbeta_app_contents_resources_omni_ja__modules_console_jsm_and_irccloud](https://cloud.githubusercontent.com/assets/557895/14904021/2a17937c-0d5a-11e6-9326-dad21b87738f.png)

There are two suspicious bits with resource://activity-streams/ references:

> TypeError: this._populatingCache is undefined: _handlePlacesChanges@resource://gre/modules/commonjs/toolkit/loader.js -> [resource://activity-streams/lib/ActivityStreams.js:180:9](https://github.com/mozilla/activity-streams/blob/32009199fd3372166572152599f8a8a41a3d98e9/lib/ActivityStreams.js#L180)
EventEmitter_emit@resource://devtools/shared/event-emitter.js:147:11
historyObserver_onFrecencyChanged@resource://gre/modules/commonjs/toolkit/loader.js -> [resource://activity-streams/lib/PlacesProvider.js:122:9](https://github.com/mozilla/activity-streams/blob/32009199fd3372166572152599f8a8a41a3d98e9/lib/PlacesProvider.js#L122)

**Comment by pdehaan** [comment]
@oyiptong Are we investigating/fixing this for RC3, or bumping to Post V1?

**Comment by oyiptong** [comment]
Can we reproduce? I'm thinking this is related to addon upgrades.

This doesn't seem to be breaking or easily reproducible. Let's move it to Post V1

**Comment by pdehaan** [comment]
I'm not able to reproduce currently against master (2ce5e6d99c779313b2021539a2ebb8a307e6d9b6).
I'll close this out until somebody can see it in the wild.
