### ISSUE TITLE
Highlights I have rejected from the activity stream are still showing

### ISSUE THREAD

**Issue by lizzard** [mozilla/activity-streams#606]
I clicked the corner X to remove a highlight, and had a choice of "Remove from History" and "Never show on this page".  I chose "Never show" and got a message "We're still working on this feature". It's unclear if that means it's a known issue.   The highlight is removed from the page, but when I open another new tab, it came right back.

**Comment by pdehaan** [comment]
@lizzard We're still working on this feature. 🎤⬇️

But in all seriousness, I believe this will be resolved by pending PR #598, coming soon to an Activity Stream near you!

Thanks for reporting. Keep on rocking the free streams.

**Comment by pdehaan** [comment]
The back end PR (#598) has landed, now just waiting on front end (#607).

**Comment by tspurway** [comment]
linked to #607

**Comment by k88hudson** [comment]
Landed!
