### ISSUE TITLE
I'm seeing bookmarks I have not bookmarked and or looked at in many many months 

### ISSUE THREAD

**Issue by bryanbell** [mozilla/activity-streams#608]
<img width="766" alt="pasted_image_4_30_16__4_56_pm" src="https://cloud.githubusercontent.com/assets/228979/14939269/8f0de8ee-0ef4-11e6-8f09-c1cb0b3bdfc0.png">

<img width="576" alt="pasted_image_4_30_16__4_57_pm" src="https://cloud.githubusercontent.com/assets/228979/14939274/9ef19030-0ef4-11e6-8368-83293079c957.png">

**Comment by bryanbell** [comment]
![pasted_image_5_2_16__10_13_am](https://cloud.githubusercontent.com/assets/228979/14961487/a05bd4b6-104e-11e6-90f2-9dd0fcddb632.png)

**Comment by oyiptong** [comment]
Interesting. That might actually be a bug in SQLite and their group by clause. I'll look into it

**Comment by emtwo** [comment]
I had started working on this... I suppose you can take it if you're certain you know the source of the problem. So far it looks like `getRecentBookmarks()` in `PlacesProvider` is returning correct results and I'm actually suspecting a UI issue, not sure if there's a second query happening there.

**Comment by oyiptong** [comment]
No please go ahead!

**Comment by oyiptong** [comment]
:-) I'm glad to hear you're back!

**Comment by emtwo** [comment]
:)

**Comment by pdehaan** [comment]
Fixed via #623
