### ISSUE TITLE
Recent Activity has a half-second load time which makes the UI feel jerky

### ISSUE THREAD

**Issue by helenvholmes** [mozilla/activity-streams#610]
The Recent Activity section in Activity Stream takes a brief moment to load (maybe half a second). It's a really small lag, but I think it would benefit from having a loading gif to both 

a) make it seem like the UI isn't broken (for users loading up Activity Stream for the second or third time, expecting to see Recent Activity immediately) and 
b) make the UI feel less jerky.

I said a loading gif above; I don't think this would need to _literally_ be a loading gif as in a spinner. It could be a that we use divs with gray backgrounds that we replace with content à la Facebook.

**Comment by helenvholmes** [comment]
Hey, I see this got marked as ```Performance```. I just want to clarify to make sure I'm capturing that I think of this as a UX bug (although it might be relevant to have a Perf bug open too).

The performance part of this bug is the _actual loading time_. Y'alls probably can eventually make this actual loading time go from something very short to actually instantaneous. 

The UX part of this bug is the _feeling that the user gets for how fast this is_. To make something feel like it's not broken, it's typically to add a loading state just so the user knows the website/tab is fetching data and it will just be a moment.

I'll leave you to triage those two points as you see fit, just wanted to clarify!

**Comment by oyiptong** [comment]
@helenvholmes, do you see this lag occurring on the first load in a while or does it happen all the time?

**Comment by helenvholmes** [comment]
@oyiptong the lag is longer on first load, but there is still lag on subsequent tabs as well.

It's more obvious when on a screen large enough to have the "Recent Activity" visible when you first open the tab.

**Comment by k88hudson** [comment]
These are my logs:

Loading New Tab
```
console.info: activity-streams: -5-7 0 TAB_OPEN
console.info: activity-streams: -5-7 93 WORKER_ATTACHED
console.info: activity-streams: -5-7 302 TOP_FRECENT_SITES_REQUEST
console.info: activity-streams: -5-7 310 TOP_FRECENT_SITES_RESPONSE 8
console.info: activity-streams: -5-7 313 RECENT_LINKS_REQUEST
console.info: activity-streams: -5-7 320 RECENT_LINKS_RESPONSE 7
console.info: activity-streams: -5-7 322 HIGHLIGHTS_LINKS_REQUEST
console.info: activity-streams: -5-7 329 HIGHLIGHTS_LINKS_RESPONSE 7
console.info: activity-streams: -5-7 332 RECENT_BOOKMARKS_REQUEST
console.info: activity-streams: -5-7 339 RECENT_BOOKMARKS_RESPONSE 7
console.info: activity-streams: -5-7 341 SEARCH_STATE_REQUEST
console.info: activity-streams: -5-7 347 NOTIFY_PERFORMANCE:BASE_MOUNTED
console.info: activity-streams: -5-7 350 TAB_READY
console.info: activity-streams: -5-7 353 NOTIFY_PERFORMANCE:DOC_READY_STATE=interactive
console.info: activity-streams: -5-7 571 NOTIFY_PERFORMANCE:DOC_READY_STATE=complete
console.info: activity-streams: -5-7 621 NOTIFY_PERFORMANCE:NEWTAB_RENDER
console.info: activity-streams: SIZE=3 MEAN=613.33 STD=10.84 MEDIAN=621
console.info: activity-streams: -5-7 634 SEARCH_STATE_RESPONSE 293
```

Loading Timeline
```
console.info: activity-streams: -5-5 0 WORKER_ATTACHED
console.info: activity-streams: -5-5 205 TOP_FRECENT_SITES_REQUEST
console.info: activity-streams: -5-5 214 TOP_FRECENT_SITES_RESPONSE 9
console.info: activity-streams: -5-5 217 RECENT_LINKS_REQUEST
console.info: activity-streams: -5-5 223 RECENT_LINKS_RESPONSE 6
console.info: activity-streams: -5-5 226 HIGHLIGHTS_LINKS_REQUEST
console.info: activity-streams: -5-5 232 HIGHLIGHTS_LINKS_RESPONSE 6
console.info: activity-streams: -5-5 235 RECENT_BOOKMARKS_REQUEST
console.info: activity-streams: -5-5 241 RECENT_BOOKMARKS_RESPONSE 6
console.info: activity-streams: -5-5 244 SEARCH_STATE_REQUEST
console.info: activity-streams: -5-5 249 NOTIFY_PERFORMANCE:BASE_MOUNTED
console.info: activity-streams: -5-5 262 NOTIFY_PERFORMANCE:DOC_READY_STATE=interactive
console.info: activity-streams: -5-5 493 NOTIFY_PERFORMANCE:DOC_READY_STATE=complete
console.info: activity-streams: -5-5 531 SEARCH_STATE_RESPONSE 287
```

Loading more history (the data looks a bit messed up for RECENT_LINKS_REQUEST)

```
console.info: activity-streams: -5-12 6017 RECENT_LINKS_REQUEST:[object Object]
console.info: activity-streams: -5-12 6025 RECENT_LINKS_RESPONSE 8
```

**Comment by k88hudson** [comment]
I agree with @helenvholmes that having some kind of interstitial loading state might be a good idea, although @bryanbell mentioned he thought it would be kinda annoying to see every time. I'll re-open the discussion.

Thanks for the feedback @helenvholmes!! 👍

**Comment by helenvholmes** [comment]
🙌🏽
