### ISSUE TITLE
Add reference to testpilot.firefox.com in addon meta

### ISSUE THREAD

**Issue by ckprice** [mozilla/activity-streams#622]
We have to add something to the `about:addons` page that 

1. Links back to https://testpilot.firefox.com.
2. Identifies this a Test Pilot experiment.

Exact specifications provided by @nchapman, @johngruen 

Note: this is a blocker for launch.

**Comment by nchapman** [comment]
Add this text to the bottom of the description:

> Learn more about this Test Pilot experiment at https://testpilot.firefox.com/

Ideally that would be a clickable link...

**Comment by nchapman** [comment]
We decided to not worry about it being clickable. Plain text is a-ok!

**Comment by oyiptong** [comment]
![screen shot 2016-05-03 at 3 49 04 pm](https://cloud.githubusercontent.com/assets/9365/14996168/9c43a572-1146-11e6-9c2f-069b1c8a8024.png)

Does this work?

**Comment by ckprice** [comment]
Nit: period.
