### ISSUE TITLE
Toolbar icon not found

### ISSUE THREAD

**Issue by shinglyu** [mozilla/activity-streams#655]
I can't find the toolbar icon as shown in the Tour. I opened the "Customize" view and still can't find it anywhere. Not sure how to start the activity stream view.

Firefox Version: 42.0

**Comment by softvision-VladBacia** [comment]
Unfortunately the add-on is not compatible with Fx versions older than 45.0. Please try to install Activity Stream, on Firefox 45.0+ and report back if this is still an issue.

**Comment by k88hudson** [comment]
Thanks for reporting! We will work on adding a better notification that the add-on is only compatible with Firefox 45.0+

**Comment by wlzabi** [comment]
This is still happening - and I downloaded the latest version today so it's not an old version. I have spent a great deal of time trying to find out why this was happening. I would really like to see the "new timeline view"
