### ISSUE TITLE
Implement re:dash reporting/analytics MVP

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-streams#7]
We could use: 
- 3rd party BI tools like https://chartio.com/ or https://www.birst.com/?
- [re:dash](http://docs.redash.io/en/latest/)
- Tableau (gross)
- Splice Reporting (lots of work)

**Comment by tspurway** [comment]
I have a dashboard stood up with weekly engagement:

https://sql.telemetry.mozilla.org/dashboard/activity-stream-engagement

r? @ncloudioj @nchapman

**Comment by ncloudioj** [comment]
@tspurway It looks great! Hope it won't charge us by the size of database :)
