### ISSUE TITLE
Replace font-awesome with actual icons

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-streams#83]
Right now we're using font-awesome via the cdn, let's replace with real icons;

Should we use 

a) A subset of font-awesome?
b) Custom icon svgs?

If so, we should get final specs/assets for icons

**Comment by pdehaan** [comment]
Potentially useful: https://www.npmjs.com/package/react-svg-use

**Comment by pdehaan** [comment]
Interesting SVG post from GitHub: https://github.com/blog/2112-delivering-octicons-with-svg

**Comment by pdehaan** [comment]
I found the following FontAwesome [references in the code](https://github.com/mozilla/activity-streams/search?utf8=%E2%9C%93&q=fa):

| ICON | FILE |
|----|----|
| `fa-search` | [/content-src/components/Search/Search.js:17](https://github.com/mozilla/activity-streams/blob/a7f93917b357379b5c3c4f195439f978159e26e5/content-src/components/Search/Search.js#L17)
| `fa-arrow-right` | [/content-src/components/Search/Search.js:20](https://github.com/mozilla/activity-streams/blob/a7f93917b357379b5c3c4f195439f978159e26e5/content-src/components/Search/Search.js#L20)
| `fa-firefox` | [/content-src/components/TimelinePage/TimelinePage.js:11](https://github.com/mozilla/activity-streams/blob/728749aec929a441ac455672f0f2e8face945fcf/content-src/components/TimelinePage/TimelinePage.js#L11)
| `fa-star` | [/content-src/components/TimelinePage/TimelinePage.js:12](https://github.com/mozilla/activity-streams/blob/728749aec929a441ac455672f0f2e8face945fcf/content-src/components/TimelinePage/TimelinePage.js#L12)
| `fa-timeline` | [/content-src/components/TimelinePage/TimelinePage.js:17](https://github.com/mozilla/activity-streams/blob/728749aec929a441ac455672f0f2e8face945fcf/content-src/components/TimelinePage/TimelinePage.js#L17)
| `fa-chevron-down` | [/content-src/components/Header/Header.js:19](https://github.com/mozilla/activity-streams/blob/728749aec929a441ac455672f0f2e8face945fcf/content-src/components/Header/Header.js#L19)

**Comment by pdehaan** [comment]
In other _"@pdehaan never shuts up about SVG news"_...
Over the weekend, I found https://github.com/riobard/font-awesome-svg which extracts all the FontAwesome icons as individual SVGs. It seemed to work great for me locally (the extraction bit, I had issues trying to add the SVGs back into the page without things looking way off). But may be a quick temporary fix until we get our own SVGs. But this should be easy enough to install as a devDep and then copy the ~5 icons we actually need into a dist folder.

**Comment by oyiptong** [comment]
Can we get an update on this @bryanbell? This is currently impacting page rendering performance quite a bit.

If it will take a while, we can alternatively package font-awesome locally for now to improve our performance.

**Comment by bryanbell** [comment]
[activityStream-assets.zip](https://github.com/mozilla/activity-streams/files/183270/activityStream-assets.zip)

icons needed.

**Comment by edmoz** [comment]
removing blocked as assets have been uploaded

**Comment by rlr** [comment]
landed :dancer:
