### ISSUE TITLE
UI shifts awkwardly offscreen with narrow browsers

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#85]
### Steps to reproduce:
1. `$ git clone` and `$ npm install` the **mozilla/activity-streams** repo.
2. `$ npm start`
3. Open your favorite browser to <http://localhost:1963/activity-streams.html>.
4. Resize your browser horizontally.

### Actual results:
The content starts getting cramped and awkward at around 1220px wide.

### Expected results:
Add some CSS breakpoints so the contents wrap better on smaller devices.

---

![nightly](https://cloud.githubusercontent.com/assets/557895/12965222/5d2f3492-d009-11e5-992f-43f74734386d.png)

**Figure 1:** Lookin' good!

---

![nightly](https://cloud.githubusercontent.com/assets/557895/12965246/78269b64-d009-11e5-8864-6ed2cd4be586.png)
**Figure 2:** A bit narrower, and less good looking. Not even horizontal scrolling on the page will save us, as we're unable to see all of our Top Sites or Spotlight sites.

**Comment by pdehaan** [comment]
There is a similar issue w/ Google Chrome where the Top Sites disappear under the navigation bar at the top when your browser is too short (or you open Dev Tools). I can't repro in Firefox, but I assume that we aren't too concerned with Chrome rendering at the moment. :eyes:

**Comment by k88hudson** [comment]
@bryanbell are you happy with the small-screen view here: http://people.mozilla.org/~shorlander/activity-stream/activity-stream-04/start-page.html or do you want to do a bit of refinement/some more comps?

**Comment by bryanbell** [comment]
> are you happy with the small-screen view here

Yeah, it's good enough.  Might want to get top-sites to do something else eventually, but for now it's fine.

**Comment by k88hudson** [comment]
Ok, closing as resolved for now. Addressing further improvements in https://github.com/mozilla/activity-streams/issues/135
