### ISSUE TITLE
Replace nav on home with link to Timeline view

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#87]
We added some font-awesome icons in #80, but looks like there isn't an icon for the Home page, only the TImeline page (and the "All" and "Bookmarks" sections). This seems a bit inconsistent and causes an odd `undefined` to appear in the CSS.

<img width="404" alt="nightly" src="https://cloud.githubusercontent.com/assets/557895/12965907/cfb52fd0-d00e-11e5-9420-68ad08dddb44.png">
**Figure 1:** Home page.

---

<img width="435" alt="nightly_and_unravel_review__a_heartwarming_mix_of_challenge_and_charm___the_verge" src="https://cloud.githubusercontent.com/assets/557895/12965914/e2efd3ac-d00e-11e5-8288-4f55b826cc46.png">
**Figure 2:** Timeline page (with icon and child page icons).

---

<img width="661" alt="nightly" src="https://cloud.githubusercontent.com/assets/557895/12965935/0e95a9e6-d00f-11e5-9243-5f492e7dc2ed.png">
**Figure 3:** Home page `undefined` CSS class for font-awesome icon.

**Comment by pdehaan** [comment]
Huh... We could add an `icon` property to the `<IndexRoute ...>` in [/content-src/components/Routes/Routes.js:11](https://github.com/mozilla/activity-streams/blob/9e9e50ac099d1e1437ded431f8f8a7bd63fad277/content-src/components/Routes/Routes.js#L11), but it looks like the "fa-home" icon is a few pixels narrower than the `fa-timeline` icon, so the UI still shifts slightly.

**Comment by k88hudson** [comment]
The designs actually didn't spec a home icon, although the latest iteration removes the top bar altogether, so this will need some clarification.

Although... rendering undefined into the className is definitely :-1:,  probably about time we added `classnames`

**Comment by pdehaan** [comment]
I did a cheap fix and defaulted a missing/undefined icon to an empty string in https://github.com/mozilla/activity-streams/pull/92#discussion-diff-52556840. :shrug:

**Comment by k88hudson** [comment]
Instead of showing the top nav on `Home` we are going to have a button that links to Activity Streams

@bryanbell to determine icon

**Comment by k88hudson** [comment]
Closing since new UI no longer has a header.
