### ISSUE TITLE
Audit the files in the @activity-streams.xpi file

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#89]
Running `npm run once` I see some errors (see #88), but if I navigate to <resource://activity-streams/> then I seem to get a directory listing of a JAR file XPI.

Not too interesting, but I was a bit surprised that we're bundling .eslintrc and .jscsrc and the test/ directory. Not sure if we need the LICENSE and README.md files (but if not, we could reduce the file by another 22 KB). Maybe we just need to tweak the .jpmignore file a bit to reduce dead code.

![index_of_jar_file____var_folders_qc_g_f0szh95k1fzph34rhmf5jw0000gp_t_030adca6-62c7-4ba3-a444-c47e6f29f1ab_extensions__activity-streams_xpi__](https://cloud.githubusercontent.com/assets/557895/12966448/53df3cc0-d013-11e5-9d17-91c80250d2d5.png)

**Comment by k88hudson** [comment]
:+1:

**Comment by pdehaan** [comment]
Actually, looking at this again, I think I need some kind soul to explain to me what the XPI is and what we're bundling.
Specifically, do we need to bundle both the raw ./content-src/\*\*/\*.js and \*.scss files as well as the compiled ./data/content/{bundle.js,main.css}?

```sh
$ tree dist
.
├── activity-streams-1.0.0.xpi
└── activity-streams-1.0.0/
    ├── LICENSE
    ├── README.md
    ├── bin
    │   └── generate-html.js
    ├── bootstrap.js
    ├── content-src
    │   ├── actions
    │   │   └── action-manager.js
    │   ├── components
    │   │   ├── ActivityFeed
    │   │   │   ├── ActivityFeed.js
    │   │   │   └── ActivityFeed.scss
    │   │   ├── Base
    │   │   │   ├── Base.js
    │   │   │   └── Base.scss
    │   │   ├── Header
    │   │   │   ├── Header.js
    │   │   │   └── Header.scss
    │   │   ├── NewTabPage
    │   │   │   ├── NewTabPage.js
    │   │   │   └── NewTabPage.scss
    │   │   ├── Routes
    │   │   │   └── Routes.js
    │   │   ├── Search
    │   │   │   ├── Search.js
    │   │   │   └── Search.scss
    │   │   ├── SiteIcon
    │   │   │   ├── SiteIcon.js
    │   │   │   └── SiteIcon.scss
    │   │   ├── Spotlight
    │   │   │   ├── Spotlight.js
    │   │   │   └── Spotlight.scss
    │   │   ├── TimelinePage
    │   │   │   ├── TimelineBookmarks.js
    │   │   │   ├── TimelineHistory.js
    │   │   │   ├── TimelinePage.js
    │   │   │   └── TimelinePage.scss
    │   │   └── TopSites
    │   │       ├── TopSites.js
    │   │       └── TopSites.scss
    │   ├── lib
    │   │   ├── ActionManager.js
    │   │   ├── ReduxChannel.js
    │   │   ├── dedupe.js
    │   │   ├── embedly-middleware.js
    │   │   ├── fake-data.js
    │   │   ├── filters.js
    │   │   ├── logger.js
    │   │   ├── parse-url-middleware.js
    │   │   ├── shim.js
    │   │   └── utils.js
    │   ├── main.js
    │   ├── main.scss
    │   ├── reducers
    │   │   └── reducers.js
    │   ├── static
    │   │   └── img
    │   │       └── list-icon.svg
    │   ├── store.js
    │   └── styles
    │       ├── normalize.scss
    │       └── variables.scss
    ├── data
    │   ├── content
    │   │   ├── activity-streams.html
    │   │   ├── bundle.js
    │   │   ├── img
    │   │   │   └── list-icon.svg
    │   │   └── main.css
    │   └── content-bridge.js
    ├── install.rdf
    ├── lib
    │   ├── ActivityStreams.js
    │   ├── PlacesProvider.js
    │   ├── TabTracker.js
    │   └── main.js
    ├── package.json
    └── test
        ├── lib
        │   ├── PlacesTestUtils.js
        │   ├── httpd.js
        │   └── utils.js
        ├── resources
        │   ├── dummy-activitystreams.html
        │   └── dummy-other.html
        ├── test-PlacesProvider.js
        ├── test-TabTracker.js
        ├── test-awesomebar-empty.js
        ├── test-httpd.js
        ├── test-message-passing.js
        └── test-workers.js

27 directories, 66 files
```

**Comment by oyiptong** [comment]
we probably don't need `content-src`
IIRC, the contents of it are packaged up in `data/content/bundle.js`

**Comment by pdehaan** [comment]
Awesome!
I assume we also don't need the ./bin/* folder.
That only leaves the ./lib/ and ./test/* folders.

This also seems to drop the XPI from ~400KB down to ~314KB &mdash; which still seems rather large, but the ./data/content/bundle.js is 1.4MB.

**Comment by pdehaan** [comment]
FWIW, if I add the following lines to the .jpmignore file, here's the beautiful new slim `tree` output:

```diff
+content-src/
+test/
+bin/
```

```sh
$ tree
.
├── @activity-streams-1.0.0.update.rdf
├── LICENSE
├── README.md
├── bootstrap.js
├── data
│   ├── content
│   │   ├── activity-streams.html
│   │   ├── bundle.js
│   │   ├── img
│   │   │   └── list-icon.svg
│   │   └── main.css
│   └── content-bridge.js
├── install.rdf
├── lib
│   ├── ActivityStreams.js
│   ├── PlacesProvider.js
│   ├── TabTracker.js
│   └── main.js
└── package.json

4 directories, 15 files
```

(I'm also mildly suspicious of the awkwardly named "@activity-streams-1.0.0.update.rdf" file. Not sure if that should just be "update.rdf" or something else.)

**Comment by oyiptong** [comment]
hah, jpm names the file that way. it also doesn't need to be in the package

**Comment by oyiptong** [comment]
we should also slim down bundle.js

**Comment by oyiptong** [comment]
i so wish that .jpmignore's whitelist actually worked. we need to file a bug for that.

**Comment by pdehaan** [comment]
Actually, `tree` isn't showing hidden files, so we can slim down a few more hidden dotfiles too (and possibly remove package.json):
```
➜  tmp git:(gh225) ✗ ls -lash
total 120
 0 drwxr-xr-x  13 pdehaan  staff   442B Mar  1 13:06 .
 0 drwxr-xr-x   5 pdehaan  staff   170B Mar  1 12:57 ..
 8 -rw-r--r--   1 pdehaan  staff   929B Mar  1 12:57 .eslintrc
 8 -rw-r--r--   1 pdehaan  staff   316B Mar  1 12:57 .jscsrc
 8 -rw-r--r--   1 pdehaan  staff   638B Mar  1 12:57 .sass-lint.yml
 8 -rw-r--r--   1 pdehaan  staff   976B Mar  1 12:57 @activity-streams-1.0.0.update.rdf
40 -rw-r--r--   1 pdehaan  staff    16K Mar  1 12:57 LICENSE
16 -rw-r--r--   1 pdehaan  staff   5.3K Mar  1 12:57 README.md
 8 -rw-r--r--   1 pdehaan  staff   593B Mar  1 12:57 bootstrap.js
 0 drwxr-xr-x   4 pdehaan  staff   136B Mar  1 12:57 data
 8 -rw-r--r--   1 pdehaan  staff   968B Mar  1 12:57 install.rdf
 0 drwxr-xr-x   6 pdehaan  staff   204B Mar  1 12:57 lib
16 -rw-r--r--   1 pdehaan  staff   4.1K Mar  1 12:57 package.json
```

**Comment by oyiptong** [comment]
we have to see if we can remove package.json. maybe all the info needed is in install.rdf

**Comment by pdehaan** [comment]
> _i so wish that .jpmignore's whitelist actually worked. we need to file a bug for that._

I may be reading the docs wrong, but I'm wondering if instead of running `$ jpm xpi` from the root dir, we either:

1. Copy _ONLY_ the files that we want into a /dist/ folder and run `cd dist && jpm xpi` from within there ([source](https://github.com/mozilla-jetpack/jpm#examples)).

2. Same as 1. but instead see if we can use the `--addon-dir <path>` CLI flag ([source](https://github.com/mozilla-jetpack/jpm#usage)).

By shifting the root `addon-dir` we'd make our .jpmignore file significantly smaller and readable (or possibly remove it entirely).
