### ISSUE TITLE
Clean up merged/closed branches in GitHub

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#90]
https://github.com/mozilla/activity-streams/branches/active

Looks like ~11 branches that are merged that can be deleted. I seem to lack the administrative powers to remove them (but I'm happy to do the housekeeping if somebody wants to bless my account in this repo).

Also, once we get CI passing, we should make sure we set up some protected branches and make sure nobody can merge without the Travis Status Checks passing.

**Comment by k88hudson** [comment]
@pdehaan https://www.youtube.com/watch?v=_BRv9wGf5pk

**Comment by pdehaan** [comment]
All merged branches have been deleted. :tada: 

![](http://vignette4.wikia.nocookie.net/adventuretimewithfinnandjake/images/a/a8/Aw_Yeah.png/revision/latest?cb=20120701211318)
