### ISSUE TITLE
intermittent failure of test_Links_getTopFrecentSites_Order

### ISSUE THREAD

**Issue by marcoscaceres** [mozilla/activity-streams#93]
Log:
https://gist.github.com/marcoscaceres/2f0dd9d744c51adc1fe7

**Comment by oyiptong** [comment]
@6a68 Moving conversation here

**Comment by oyiptong** [comment]
So, it looks like there is some code we could look at importing if need be:

https://github.com/mozilla/addon-sdk/blob/master/test/addons/places/lib/places-helper.js

Still uses asyncHistory.

**Comment by oyiptong** [comment]
This does pretty much what we do.

A test that also does what we do: https://github.com/mozilla/addon-sdk/blob/master/test/addons/places/lib/test-places-history.js#L27

**Comment by marcoscaceres** [comment]
Argh... and Promise.jsm :/

**Comment by marcoscaceres** [comment]
@oyiptong, sorry, I missed previous discussions about "asyncHistory" - what's the alternative? Having a look at the test and what we have seems ok.

**Comment by oyiptong** [comment]
I didn't mind `deferred`s. But then again, maybe I'm a brute compared to your fancy approaches :-)

**Comment by oyiptong** [comment]
The alternative would be to use synchronous inserts, using `Placesutils.history`, i.e. the nav-history-service, to create a statement and execute it synchronously

**Comment by oyiptong** [comment]
e.g. https://dxr.mozilla.org/mozilla-central/rev/ac39fba33c6daf95b2cda71e588ca18e2eb752ab/toolkit/components/places/PlacesUtils.jsm#934

**Comment by marcoscaceres** [comment]
Ah, ok. Got it.

**Comment by oyiptong** [comment]
That said, since we query with another connection in the actual test, it remains to be seen if that buys us much.

Also, if we do the synchronous inserts, we lose the notification machinery. Instead of hitting the `asyncHistoryService` codepaths, we'd be inserting directly in the database.

**Comment by oyiptong** [comment]
@6a68 is that what you had in mind?

**Comment by marcoscaceres** [comment]
Maybe more issues: https://travis-ci.org/mozilla/activity-streams/builds/108467742 ... but might just be I introduced a new bug :scream:

**Comment by pdehaan** [comment]
Probably unrelated, and my own ignorance, but does this JPM error from Travis-CI mean anything?
Wasn't sure if this was from somewhere in our code, or just some generic deprecation notice.

> _"JPM [error] JavaScript warning: resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/system/environment.js, line 15: Proxy.create and Proxy.createFunction are deprecated, use new Proxy instead"_

**Comment by oyiptong** [comment]
Thanks for chiming in @pdehaan. This seems to just be a deprecation warning, not an error.

**Comment by oyiptong** [comment]
hah, @marcoscaceres, you didn't do too bad, only broke two tests:
```
console.info: activity-streams: executing './test/test-PlacesProvider.test_Links_getTopFrecentSites'
console.info: activity-streams: pass: empty history yields empty links
console.error: activity-streams: 
  fail:
  adding a visit yields a link - 0 == 1
console.trace: activity-streams: 
_ecated/unit-test.js 108 fail
_/sdk/test/assert.js 88 fail
_/sdk/test/assert.js 123 equal
_t-PlacesProvider.js 44 exports.test_Links_getTopFrecentSites
_re/modules/Task.jsm 319 TaskImpl_run
_/Promise-backend.js 937 Handler.prototype.process
_/Promise-backend.js 816 this.PromiseWalker.walkerLoop
```

and

```
console.error: activity-streams: 
  fail:
  links[0] is undefined
console.trace: activity-streams: 
_ecated/unit-test.js 108 fail
_/sdk/test/assert.js 88 fail
_/Promise-backend.js 940 Handler.prototype.process
_/Promise-backend.js 816 this.PromiseWalker.walkerLoop
console.info: activity-streams: pass: This test is done.
```

> 48 of 50 tests passed.

In my experience so far, changing the command travis executes to run the tests multiple times doesn't help. But it may be useful to you? who knows?

In yamscripts.yml, which, when you run `npm run yamscripts` will generate a package.json, you can enter `jpm test ... --times N` where N is the number of tests to run.

**Comment by oyiptong** [comment]
Also, the intermittent issues don't seem to happen for any one particular test.

Maybe there's a problem with how the test is set up?

**Comment by oyiptong** [comment]
I think I've implemented a workaround to the bug.

I've found out that `waitUntil` requires a synchronous function. Making the check synchronous seems to have solved the concurrency issue.

Note that this is still a workaround. Async db access is still mysteriously unsafe. But as far as we're concerned, the intermittents are done I think.

**Comment by oyiptong** [comment]
So, I think this issue is fixed, but with intermittents we never know. I suggest we close this for now and re-open if we identify another issue. Since you opened the bug, @marcoscaceres, how about you make that call?
