### ISSUE TITLE
Implement correct url in awesome bar

### ISSUE THREAD

**Issue by nchapman** [mozilla/activity-streams#94]
Opening a new tab shows the resource URL and puts the cursor insertion point is at the end of the resource URL which makes it hard to type things into the Awesome Bar:

![screen recording 2016-02-10 at 07 25 pm](https://cloud.githubusercontent.com/assets/3095/12968843/7482b2ae-d02c-11e5-8784-99432d76aa32.gif)

**Comment by k88hudson** [comment]
What we probably want is is the awesome bar to be blank for the New Tab page and  `about:timeline` for the Timeline, does that sound right?

**Comment by oyiptong** [comment]
That's easy to fix, @nchapman, we just need the correct url to show

**Comment by nchapman** [comment]
> What we probably want is is the awesome bar to be blank for the New Tab page and about:timeline for the Timeline, does that sound right?

Yes this sounds great. New tab should look like this:

![screen shot 2016-02-11 at 2 23 11 pm](https://cloud.githubusercontent.com/assets/3095/12992774/3073920a-d0cb-11e5-9a72-33af968d4ece.png)

**Comment by oyiptong** [comment]
That means that they are two different documents.

Meaning that when a user switches, it will cause a full page reload.

I'll have to see how that impacts the plumbing if we use pushState.

**Comment by oyiptong** [comment]
@nchapman, can we for now keep it in one page, where the URL is hidden in both cases?

**Comment by nchapman** [comment]
@oyiptong Yep that's fine with me. Is it possible for the Awesome Bar to be focused on new tab but not on the Timeline?

**Comment by oyiptong** [comment]
I think we may be able to do that, yes
