### ISSUE TITLE
Make the spotlight-image elements clickable

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#97]
Currently only the [`spotlight-title`](https://github.com/mozilla/activity-streams/blob/3a42234353fb93845e7966ed66da6aed1b9a0731/content-src/components/Spotlight/Spotlight.js#L13) elements are clickable. I expected to be able to click on the big image as well, but it doesn't seem to be clickable.

Seems to work if we wrap the whole [`spotlight-image`](https://github.com/mozilla/activity-streams/blob/3a42234353fb93845e7966ed66da6aed1b9a0731/content-src/components/Spotlight/Spotlight.js#L7-L9) block in an `<a href={site.url} ref="link">...</a>` block. There isn't a big UI change (image zoom, fade image, etc), but the mouse cursor changes to the hand, signaling that the image is clickable.

**Comment by k88hudson** [comment]
:+1:

**Comment by rlr** [comment]
@k88hudson did this in 15234fce37ae7f9c991f57c347d9f854e9d4694d
