### ISSUE TITLE
Add URL hint to spotlight results

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#99]
Currently I see 3 search results for CNN, but if we didn't have a favicon for the site, then there wouldn't be much hint about what site you're going to.

Not sure if we want to add a "source: www.cnn.com" or something above the "Last opened on iPhone" tag at the bottom of the card. I imagine we can get that data back via embedly, or even just grab the [sub]domain name from the URL and display that. That way I don't feel like I'm blindly clicking articles without knowing where the link goes.

**Comment by k88hudson** [comment]
@bryanbell suggests we use `History Item` or `Recent Bookmark` as a context label

and  replace the context text with the url on hover;

**Comment by k88hudson** [comment]
@bryanbell to add comps

**Comment by bryanbell** [comment]
![on hover show url](https://cloud.githubusercontent.com/assets/228979/13236552/febda3ba-d979-11e5-808e-2cedd10a0ff5.png)

On hover, we should show the URL like this.

**Comment by bryanbell** [comment]
For now, until a user says this is an issue, let’s rely on the built in utility that shows what URL is about to be opened (bottom left of all Firefox windows).

![pasted_image_2_23_16__9_07_am](https://cloud.githubusercontent.com/assets/228979/13259589/e2f513f0-da0c-11e5-82d1-5ed13dea67cd.png)
